tc39/proposal-temporal

- polyfill/test/intl.mjs
This test would otherwise fail with Node.js 17.x because there wasn't a
snapshot key for `node17`. Add an `other` fallback key which is equal to
the latest `node16` snapshot. (If that later becomes incorrect, the
snapshots can be updated.)
> Handle other Node.js versions in localized calendar tests

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/plaintime.html
Previously, ToTemporalTimeRecord (called for PlainTime, PlainDateTime,
ZonedDateTime, and relativeTo property bags) would throw a TypeError
unless all six time properties were present: hour, minute, second,
millisecond, microsecond, and nanoseconds. This was not intended. Instead,
if any of these are missing then they should default to 0, and a TypeError
should only be thrown if all of them are missing.
This only affected PlainTime and relativeTo property bags, since all code
paths involving PlainDateTime and ZonedDateTime property bags ensured via
other means that the properties were present.
No polyfill or documentation changes needed, as the intention was already
correctly reflected there.
Closes: #1803
> Normative: Fix PlainTime and relativeTo property bags

- polyfill/lib/zoneddatetime.mjs
- spec/zoneddatetime.html
As discussed in https://github.com/tc39/proposal-temporal/pull/1762#discussion_r695948180
This changes ZonedDateTime.prototype.with() to throw slightly earlier
(before calling calendar methods in user code) in the unlikely case that
the offset field is messed up or missing.
> Normative: Throw earlier in ZonedDateTime.with if offset field is missing

- spec/abstractops.html
ParseTemporalMonthDayString could be simplfy for not dealing impossible condiction
https://tc39.es/proposal-temporal/#sec-temporal-parsetemporalmonthdaystring
Since we throw in step 2. If isoString does not satisfy the syntax of a TemporalMonthDayString (see 13.33), then
we know we have a TemporalMonthDayString which is either DateSpecMonthDay or DateTime
DateSpecMonthDay =  --opt DateMonth -opt DateDay
and
DateTime = Date TimeSpecSeparatoropt TimeZoneopt
and we know Date is either of the following two
DateYear - DateMonth - DateDay   
DateYear DateMonth DateDay
so in all three cases we have both DateMonth and DateDay
and if either DateMonth or DateDay is not presented then step 2 will throw.
Therefore, both 5. If month is undefined, and 7. If day is undefined,  can never happen
@pdunkel …
> Editorial: Simplify ParseTemporalMonthDayString

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Move the following code into RejectTemporalCalendarType
```
1. Let _calendarProperty_ be ? Get(_temporalDateLike_, *"calendar"*).
1. If _calendarProperty_ is not *undefined*, then
1. Throw a *TypeError* exception.
1. Let _timeZoneProperty_ be ? Get(_temporalDateLike_, *"timeZone"*).
1. If _timeZoneProperty_ is not *undefined*, then
1. Throw a *TypeError* exception.
```
> Editorial: Move common code into RejectTemporalCalendarType

- spec/zoneddatetime.html
On step 6 of this algorithm, instant is created with "Let instant be".
On step 10, it uses "Let instant be" again, when instant already exists.
This changes it to "Set instant to" to match withPlainDate.
> Editorial: Use "set" instead "let" when updating instant in ZonedDateTime#withPlainTime

- docs/calendar-draft.md
- docs/cookbook.md
- docs/duration.md
- docs/plaindate.md
- docs/plaindatetime.md
- docs/plaintime.md
- docs/timezone.md
I split this out of #1875 so that this part is not blocked on anything.
> Use US spelling in docs (behaviour => behavior)

- spec/duration.html
Current definition:
```
7.5.15 DaysUntil ( earlier, later )
1. Assert: earlier and later both have [[ISOYear]], [[ISOMonth]], and [[ISODay]] internal slots.
2. Let difference be ! DifferenceISODate(earlier.[[ISOYear]], earlier.[[ISOMonth]], earlier.[[ISODay]], later.[[ISOYear]], later.[[ISOMonth]], later.[[ISODay]], "day").
3. Return difference.[[Days]].
```
> Editorial: Mark DaysUntil as infallible

- spec/duration.html
relativeTo was made into a requirement in this commit: 7a9cf7ac0b0b0516bf03ec74d26784e05f706b46
However, it forgot to remove the presence check.
> Editorial: Remove relativeTo presence check in UnbalanceDurationRelative

- spec/duration.html
- spec/instant.html
- spec/zoneddatetime.html
Current `RoundTemporalInstant` definition:
```
1. Assert: Type(ns) is BigInt.
2. If unit is "hour", then
a. Let incrementNs be increment × 3.6 × 1012.
3. Else if unit is "minute", then
a. Let incrementNs be increment × 6 × 1010.
4. Else if unit is "second", then
a. Let incrementNs be increment × 109.
5. Else if unit is "millisecond", then
a. Let incrementNs be increment × 106.
6. Else if unit is "microsecond", then
a. Let incrementNs be increment × 103.
7. Else,
a. Assert: unit is "nanosecond".
b. Let incrementNs be increment.
8. Return ! RoundNumberToIncrement(ℝ(ns), incrementNs, roundingMode).
```
Current `RoundNumberToIncrement` definition:
```
1. Assert: x and increment are mathematical values.
2. Assert: roundingMode is "ceil", "floor", "trunc", or "halfExpand".
3. Let quotient be x …
```
> Editorial: Mark RoundTemporalInstant as infallible

- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainyearmonth.md
- docs/zoneddatetime.md
This commit fixes #1706 by updating docs to clarify that calendars and time zones are ignored by `compare` methods in PlainDate, PlainDateTime, PlainYearMonth, and ZonedDateTime types.
It also fixes #1846 by clarifying that the first day of the month is used to compare PlainYearMonth instances.
This reflects a change in behavior made shortly before this proposal reached Stage 3.
> Docs: `compare` methods now ignore calendar/TZ

- spec/duration.html
This is both more performant when implemented literally, and much more common across the spec in general when testing a single variable for multiple values. Additionally we can add an Assert to the final else branch to ensure that all possible values have been handled.
This now looks very similar to RoundTemporalInstant, RoundTime, and RoundDuration.
> Editorial: Turn Temporal.Duration.prototype.total unit if branches into else-if's

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/test/duration.mjs
- spec/abstractops.html
- spec/duration.html
The Temporal.Duration constructor, unlike Temporal.Duration.from(), would
previously drop the fractional part of numbers given to it. from() throws
if given a non-integer number, because Temporal.Duration.from('PT1.1H')
results in 1 hour, 6 minutes, but Temporal.Duration.from({ hours: 1.1 })
cannot be exact, yet should not silently drop the .1, as discussed in
issue #938.
Temporal.Duration(0, 0, 0, 0, 1.1) should now throw the same exception as
Temporal.Duration.from({ hours: 1.1 }) in order to be consistent and avoid
the surprise to users of silently dropping the .1.
Closes: #1832
> Normative: Temporal.Duration constructor throws if given a non-integer

- spec/timezone.html
Discussed this in bi-weekly meeting 2021-09-16
1. If the timeZone is not a Custom time zones and the caller does not modify timeZone then "If getOffsetNanosecondsFor is undefined" will be false and this step is no-op
2. If the timeZone is a Custom time zones which is  from an object of " a class inheriting from Temporal.TimeZone" , then "If getOffsetNanosecondsFor is undefined" will be false and this step is no-op
3. If the timeZone is a Custom time zones which is "a plain object implementing the Temporal.TimeZone protocol, without subclassing." then it will not have a [[InitializedTemporalTimeZone]] internal slot, and the 
step 2. Perform ? RequireInternalSlot(timeZone, [[InitializedTemporalTimeZone]]).
in 11.4.4 Temporal.TimeZone.prototype.getOffsetNanosecondsFor ( instant ) will throw …
> Normative: Remove step 2 of GetOffsetNanosecondsFor

- docs/duration.md
- docs/instant.md
- docs/plaindatetime.md
- docs/plaintime.md
- docs/zoneddatetime.md
- polyfill/index.d.ts
- polyfill/lib/duration.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/duration.mjs
- polyfill/test/instant.mjs
- polyfill/test/plaindatetime.mjs
- polyfill/test/plaintime.mjs
- polyfill/test/zoneddatetime.mjs
- spec/duration.html
- spec/instant.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
This PR addresses reviewer feedback from @ljharb that required parameters should not only be an options bag if some of those "options" are actually required properties. With this PR, all affected methods (`round` on multiple types, and `total` on Duration) now also accept a string as their single required parameter. 
For advanced use cases, the string can be substituted with a property bag containing the string parameter as a property, plus additional optional properties.
The champions met this morning and came to consensus that we support this change because it makes the API more ergonomic without breaking any existing use cases. 
This is a normative change but not a breaking change. Fixes #1756.
Examples:
* `duration.total('hours')` is equivalent to `duration.total({ unit: 'hours' })`
* …
> Normative: allow strings as required param in `round` and `total` methods

- polyfill/lib/ecmascript.mjs
- polyfill/test/expected-failures.txt
- polyfill/test/regex.mjs
This fixes some polyfill code that no longer applies. Ever since the change to allow UTC offsets to be rounded to minutes in ISO strings (#1871), the `identifier !== offset` line has been incorrect, but there are no tests for this case in our test suite. No change to the specification is needed, since this algorithm didn't exist in this form in the spec text, which is also why I originally overlooked it.
Rename the abstract operation TemporalTimeZoneFromString to ParseTemporalTimeZone so that it matches [the spec](https://tc39.es/proposal-temporal/#sec-temporal-parsetemporaltimezone), and simplify its logic to match what is written in the spec as well.
I'm in the process of adding test262 tests that cover this, but this PR includes a quick test in the old test suite just so that it's …
> Bring polyfill in line with ParseTemporalTimeZone operation in specification

- spec/timezone.html
otherwise step 13  may have string-concatenationof undefined in FormatTimeZoneOffsetString
```
13. Return the string-concatenation of sign, h, the code unit 0x003A (COLON), m, and post.
```
@ptomato @ljharb @justingrant @ryzokuken @Ms2ger
> Initialize post as empty String in FormatTimeZoneOffsetString

- spec/duration.html
Current definition (https://tc39.es/proposal-temporal/#sec-temporal-totaldurationnanoseconds):
```
1. Assert: offsetShift is an integer.
2. Set nanoseconds to ℝ(nanoseconds).
3. If days ≠ 0, then
a. Set nanoseconds to nanoseconds − offsetShift.
4. Set hours to ℝ(hours) + ℝ(days) × 24.
5. Set minutes to ℝ(minutes) + hours × 60.
6. Set seconds to ℝ(seconds) + minutes × 60.
7. Set milliseconds to ℝ(milliseconds) + seconds × 1000.
8. Set microseconds to ℝ(microseconds) + milliseconds × 1000.
9. Return nanoseconds + microseconds × 1000.
```
> Editoral: Mark use of TotalDurationNanoseconds inside AdjustRoundedDurationDays as infallible

- polyfill/lib/ecmascript.mjs
- polyfill/test/expected-failures.txt
- polyfill/test/plaindatetime.mjs
- polyfill/test/plaintime.mjs
- polyfill/test/plainyearmonth.mjs
- polyfill/test/regex.mjs
- spec/abstractops.html
Accepting this kind of string in Plain types poses a risk when
deserializing from databases, as some attach local-time-zone semantics to
this kind of string. This could cause user-facing off-by-one-day bugs.
(Note: this could probably be refactored to have these strings actually be invalid according to the ISO 8601 grammar, but this PR is set up so that could be done separately as an editorial change.)
Closes: #1751
> Normative: Don't accept Z designators in strings for Plain types

- spec/abstractops.html
TemporalZonedDateTimeString is a subset of TemporalDateTimeString
no need to list both under TemporalRelativeToString
Fix https://github.com/tc39/proposal-temporal/issues/1939
@ptomato @pdunkel @ljharb @gibson042 @ryzokuken @justingrant
> Editoral: Simplify TemporalRelativeToString

- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainmonthday.md
- docs/plaintime.md
- docs/plainyearmonth.md
In #1874, we removed the ability to parse Z strings with Plain types' `from` methods. This PR explains this change and documents workarounds.
The docs for PlainYearMonth and PlainMonthDay (where Z strings are rare) get only minimal text. PlainDate, PlainDateTime, and PlainTime (where Z-string use cases are most likely) get a little more explanation and a short code sample.
> Document workarounds for parsing Z strings

- polyfill/index.d.ts
This PR fixes bugs in the TS types RoundTo and TotalOf where plural unit names were not being accepted in a few places.
> Fix TS types of RoundTo and TotalOf to allow plural unit names

- spec/abstractops.html
- spec/calendar.html
Similar to #1897, we want to move any validation that is not purely syntactic out of ParseTemporal___String abstract operations. This accomplishes that for Calendar. However, it affects nothing observable, just reorganizes code.
Closes: #1901
> Editorial: Move calendar validation out of ParseTemporalCalendarString

- polyfill/lib/ecmascript.mjs
Update GetFormatterParts implementation in polyfill to avoid failed tests on the latest Intl implementations in newer JS engines (e.g. FF nightly).
Port of https://github.com/js-temporal/temporal-polyfill/pull/97
> Support newer DateTimeFormat output

- polyfill/index.d.ts
The [docs](https://tc39.es/proposal-temporal/docs/calendar.html#custom-calendars) say: 
> The other, more difficult, way to create a custom calendar is to create a plain object implementing the `Temporal.Calendar` protocol, without subclassing. The object must implement all of the `Temporal.Calendar` properties and methods except for `id`, `fields()`, `mergeFields()`, and `toJSON()`.
The TS types currently allow many CalendarProtocol methods to be undefined other than the 4 above. This PR aligns the TS types to the docs.
@sffc @ptomato holler if the docs are wrong.
> Fix TS types for required CalendarProtocol methods

- spec/duration.html
It was previously instantiated on step 9.a.
> Editorial: Use set instead of let when updating moveResult on BalanceDurationRelative step 9.e

- polyfill/lib/ecmascript.mjs
- spec/duration.html
Align spec and polyfill `RoundDuration` spec text with similar text used in `BalanceDurationRelative` and `UnbalanceDurationRelative`.
Fixes #1958.
> Editorial: minor DRY refactor for RoundDuration

- polyfill/lib/ecmascript.mjs
This PR is a few minor refactors for issues caught in temporal-polyfill. The common theme here is to better align polyfill code with current spec text.
1. PrepareTemporalFields should throw (not return false) if its input is not an Object, which is what the spec says. Fixes #1963.
2. Refactor ToPartialRecord to better align wtih the spec text. Also removes parameter `callerCast` which isn't in the spec and isn't used elsewhere in the polyfill. (Thanks to TS for finding that!)
3. Add assertion (like the spec has) in `DisambiguatePossibleInstants` to catch bad option values.
> Refactors to align ecmascript.mjs with spec text

- polyfill/lib/ecmascript.mjs
Per @ptomato's suggestion in https://github.com/js-temporal/temporal-polyfill/pull/109/files#r768187244, these two AOs can never have non-object inputs, so these runtime assertions shouldn't be necessary.
> Polyfill: remove unnecessary runtime assertions in PrepareTemporalFields and ToPartialRecord

- polyfill/lib/intl.mjs
- polyfill/lib/shim.mjs
This PR fixes #1965:
1. For Intl.DateTimeFormat, sets `writeable: false` on  `prototype` because it's created using `function` (which has a writeable `prototype`, unlike `class` which is not writeable).
2. For Temporal classes, there's a Babel bug that causes prototypes to be writeable (https://github.com/babel/babel/issues/2025) and this PR works around it.
There are corresponding Test262 tests to check prototype writability here: https://github.com/tc39/test262/pull/3344
> Polyfill: Ensure that Temporal prototypes aren't writable

- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
The `zoneRequired` option in `ES.ParseTemporalTimeZoneString` doesn't work, because the `zonesplit` regex in regex.mjs matches any string. (It does correctly match each component, it just doesn't fail if none match.) Furthermore, callers of this option don't really follow the spec that requires throwing as soon as we know that it's not the right regex for the type.
This PR fixes #1973 by:
* Removing the `zoneRequired` option
* Removing the now-unused `datetime` regex, and renaming the `instant` regex to `zoneddatetime` to better reflect what it's doing.
* Refactoring a few of the parsing methods to better match the spec, which expects that strings that don't satisfy the production will throw before doing non-parsing work. After this PR, every `Parse*` AO will throw if the string doesn't …
> Remove `zoneRequired` option in ParseTemporalTimeZoneString & better align parsing to spec

- docs/buildDocs.js
- docs/package.json
- package-lock.json
- package.json
- polyfill/package.json
- polyfill/test/duration.mjs
- polyfill/test/zoneddatetime.mjs
- spec/intl.html
- update_deps.sh
This PR adds an "update dependencies" script (`npm run update`) and uses it to update deps in the root, polyfill, and docs folders. All deps except Demitasse is upgraded by the script. Demitasse is kept at an old version because our tests are incompatible with latest. 
This PR removes a duplicate `aoid` from the 402 version of `IsBuilltinCalendar` in the Intl section of the spec to avoid ecmarkup "Duplicate AOID" errors, per the guidance here: https://github.com/tc39/ecmarkup/issues/394.
> Update dependencies and add update script

- polyfill/lib/ecmascript.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/duration.mjs
- polyfill/test/zoneddatetime.mjs
Ensure that the correct RangeError is thrown when an invalid offset is passed to ParseTimeZoneOffsetString. 
Note that validation of the offset in ISO strings is handled separately; this PR only fixes cases where an offset is parsed on its own, e.g. when property bag inputs are used in `ZonedDateTime#(with|from|equals|until|since|compare)` or as `relativeTo` options  passed to `Duration#(add|subtract|compare|round|total)`. The problem was also present in `TimeZone.from` and `ZonedDateTime#withTimeZone` but was caught downstream so didn't fail any previous tests.
Fixes #1972.
> Polyfill: Throw RangeError if there's an invalid `offset` string in `ZonedDateTime`-representing property bags

- polyfill/index.d.ts
- polyfill/lib/calendar.mjs
This contains commits from #1977 which @Ms2ger or I already reviewed. (I can't merge it myself since I opened it, so just needs a rubber-stamp review.)
> Non ISO calendar refactor, part 1

- polyfill/lib/calendar.mjs
Fix a few non-ISO calendar issues:
- Update documentation comment for era metadata d458938 (the current in-code documentation for internal-only era definitions are out of date)
- Call maximumMonthLength with correct args efe4498
- Additional validation for hard-coded era data 592b100
- Fix bad code ordering in adjustCalendarDate ba96615
This PR used to have a larger scope but @ptomato helpfully split some of the easier ones into #1983.
> Polyfill: fix a few non-ISO calendar issues

- spec/calendar.html
- spec/timezone.html
Fix https://github.com/tc39/proposal-temporal/issues/1692
I assume these missing RequireInternalSlot is mistake.
> Normative: Add missing RequireInternalSlot

- spec/abstractops.html
...as mentioned in #1759. This also fixes some spec bugs from use of `floor` with negative values.
This also requires care with respect to using mathematical values rather than approximations, and I'd like to see a test for input like ±PT46H66M71.50040904S (which produced an off-by-one error at the nanoseconds level when I was evaluating a JS-based implementation of the new algorithm that took too many liberties in that respect).
Fixes #1754
> Normative: Simplify Duration parsing

- spec/plaindate.html
Instead of setting `testYear` to `year + 1`, and therefore discarding the previous distinction of leap years vs. regular years, just increment it by one.
This matches the polyfill's implementation and yields expected results for all inputs.
Closes #1923.
> Normative: Fix off-by-one in BalanceISODate for leap year inputs

- spec/duration.html
- spec/instant.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
Fixes incorrect property names `"_smallestUnit_"` -> `"smallestUnit"` when creating options objects from a string argument, which was introduced as a new feature in #1875.
Fixes  #1961.
> Normative: Fix "smallestUnit" property name for options objects created from string argument

- spec/abstractops.html
Unfortunately, this incorrect indentation caused the algorithm to have a
different result than was intended.
Closes: #1910
> Normative: Fix indentation error

- spec/plaindate.html
To bring the default for largestUnit in PlainDate's since() and until()
methods in line with other types' since() and until() methods, we have to
add an algorithm step for LargerOfTwoTemporalUnits.
Without this, code such as
date1.until(date2, { smallestUnit: 'months' })
would throw because the default largestUnit is days. As per
https://github.com/tc39/proposal-temporal/issues/827#issuecomment-685248205
this was not intended.
PlainDate seems to be the only place where this was not working as
intended. ZonedDateTime, Instant, PlainTime, PlainYearMonth, and
PlainDateTime either already have this step or their default largestUnit
is already the largest one so they wouldn't have this problem.
The reference polyfill code is already correct in this regard.
Closes: #1864
> Normative: Make PlainDate difference methods units handling consistent

- spec/abstractops.html
In ParseISODateTime, where the algorithm refers to "the part of
_isoString_ produced by the |TimeFractionalPart| production", it is
ambiguous whether this means the fractional part of the seconds in the
time representation, or the fractional part of the seconds in the
UTC-offset-named time zone.
That is, in the following string,
2021-09-01T02:03:04.56789+23:12:07.987654321[+11:22:33.444445555]
it could refer to "56789" or "444445555"
This fixes the ambiguity by making Fraction not include
TimeFractionalPart.
Closes: #1794
> Normative: Fix ambiguity in FractionalPart grammar

- spec/timezone.html
I had previously changed this from modulo to remainder in [baaa8fd], but
that was incorrect. I was probably confused by the fact that the
reference code used BigInteger.divmod() here, which performs remainder,
but I missed that we add some extra code after that which ensures the
operation performed on the BigInteger is equivalent to modulo.
Closes: #1927
> Normative: Use modulo instead of remainder in GetISOPartsFromEpoch

- polyfill/test/validStrings.mjs
- spec/abstractops.html
This was mistakenly left out when we added calendar annotations to
Temporal.
Note that PlainTime currently only supports the iso8601 calendar and
Temporal.PlainTime.from() will throw if any other calendar is specified in
the calendar annotation. This keeps open the possibility to support more
calendars in PlainTime in a future proposal.
Note also that only the YYYY-MM-DD forms of PlainMonthDay and
PlainYearMonth support calendar annotations. The YYYY-MM and MM-DD forms
always require the iso8601 calendar, because otherwise there is no
reference ISO year or reference ISO day, respectively.
Closes: #1896
Closes: #1912
> Normative: Add optional calendar to PlainTime, PlainYearMonth, and PlainMonthDay productions

- polyfill/lib/ecmascript.mjs
- polyfill/test/duration.mjs
- spec/duration.html
Previously, code that combined zero subsecond units with a specified
precision, such as the following:
Temporal.Duration.from({ years: 3 }).toString({ fractionalSecondDigits: 5 })
would not render the seconds with the correct precision. The above example
would return 'P3Y' and not 'P3YT0.00000S'.
Closes: #1763
> Normative: Fix fractionalSecondDigits behaviour in Duration.toString()

- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- polyfill/test/plaintime.mjs
- polyfill/test/regex.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
Includes #1950 to avoid rebase conflicts. I'll make sure that one is merged before this one.
Closes: #1765
> Normative: Support 'T' prefix in time-only strings and require it in cases of ambiguity

- polyfill/lib/ecmascript.mjs
- polyfill/test/plaintime.mjs
Slightly refector the implementation of #1952 to enable a clearer error message when the user tries to parse a date-only string with `PlainTime.from`.
This is the same pattern that's used for other polyfill parsing: `ParseISODateTime` is used for generic, regex-only parsing
while type-specific validation happens in the calling method, e.g. `ParseTemporalTimeString` or `ParseTemporalZonedDateTimeString`.
Also add tests to verify that date strings are not allowed, and that space is not accepted as a time designator prefix even though space is accepted as a date/time separator.
> Improve "missing time in string" error message

- spec/abstractops.html
This is already covered by step 2:
> 2. Let _year_, _month_, _day_, _hour_, _minute_, _second_, _fraction_, and _calendar_ be the parts of _isoString_ produced respectively by the |DateYear|, |DateMonth|, |DateDay|, |TimeHour|, |TimeMinute|, |TimeSecond|, |TimeFractionalPart|, and |CalendarName| productions, or *undefined* if not present.
> Editorial: Remove duplicate assignment of year in ParseISODateTime

- spec/intl.html
- spec/timezone.html
> Editorial: Restrict IsValidTimeZoneName case folding to ASCII

- spec/abstractops.html
- spec/timezone.html
- spec/zoneddatetime.html
This commit looks like it just moves a few things around, moving the
validation of time zone names from ParseTemporalTimeZoneString to its
callers. But the important part to note is that the validation no longer
takes place in ParseTemporalInstantString, one of the callers of
ParseTemporalTimeZoneString.
This is already covered by test262 tests.
Closes: #1897
> Normative: Do not validate time zone names when parsing Instant string

- spec/instant.html
When `newTarget` is not provided, it falls back to `%Temporal.TimeZone%` & the only fallible operation in `CreateTemporalTimeZone`,  the call of `OrdinaryCreateFromConstructor`, becomes infallible.
See also:
https://github.com/tc39/proposal-temporal/blob/2a81fbca981eb684f1dc10ec479b5a8e872d8c37/spec/timezone.html#L584
> Editorial: Mark CreateTemporalTimeZone("UTC") as infallible

- spec/abstractops.html
- spec/plainyearmonth.html
- spec/timezone.html
I noticed that in a few places we parse a UTC offset string into a nanosecond offset, only to turn it back into an offset string later. This can be simplified with an editorial change.
While I was working on this, I changed the UTC offset parsing algorithms to use ParseText like @gibson042 did in #1907.
> Editorial: Simplify parsing UTC offset strings

- spec/timezone.html
75490b98 inadvertently made an observable change: a non-canonical offset
string would be stored in the time zone's [[Identifier]] internal slot,
and would be visible to user code via toString(). This change restores the
previous behaviour so that the editorial change is actually editorial.
Closes: #2007
> Editorial: Fixup "Don't parse and re-format offset string in ParseTemporalTimeZoneString"

- spec/timezone.html
...and not the identifier itself, which would fail the assertion in the first step of the AO:
1. Assert: offsetNanoseconds is an integer.
---
I even LGTM'd this in the PR, but only noticed this while implementing the change :upside_down_face:
> Editorial: Call FormatTimeZoneOffsetString with identifier parse result

- polyfill/index.d.ts
This was missed in https://github.com/tc39/proposal-temporal/commit/bc0b188c0e07657319f03489d7b8caa89c420a5d, and is a port of https://github.com/js-temporal/temporal-polyfill/pull/121
> Include the valueOf function in Temporal.Duration.

- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainmonthday.md
- docs/plaintime.md
- docs/plainyearmonth.md
Using a `Z` designator when creating an instance of the these `PlainX` types is incorrect.
> Remove bad examples

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
In #1753 there was some discussion of what to do about dates with an extended year equal to "-000000". It was decided to reject such cases. Here's a simple solution to that.
Alternatives considered:
+ Change the regexp for the year part of dates. This would have the desired effect of rejecting "-000000" as ungrammatical. This alternative wasn't chosen because it seems to me that the invalidity is a domain decision, not a grammar decision. Thus, "-000000" remains grammatically valid and thus *potentially* meaningful; we just reject this one case by a domain convention.
closes #1753
> Normative: Reject '-000000' as extended year

- spec/calendar.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/temporal.html
Rename variable which need to pass through ToTemporalCalendar*()
from calendar to calendarLike.
motivation: https://chromium-review.googlesource.com/c/v8/v8/+/3380305/6/src/objects/js-temporal-objects.h#120
@syg
> EDITORAIL: Rename to calendarLike

- spec/abstractops.html
Discovered while implementing the most recent normative change, h/t @idanHo.
Additionally, one of the -000000 checks is nonsensical and has been removed.
> Editorial: Mark uses of ParseISODateTime as fallible

- polyfill/lib/ecmascript.mjs
ToTemporalDurationOverflow is no longer used anywhere.
> Remove dead code

- polyfill/lib/calendar.mjs
Works around https://bugzilla.mozilla.org/show_bug.cgi?id=1752253 by allowing either `'a'` or `'ad'` for the CE era and `'b'` or `'bc'` for the BCE era.
This bug only occurs with Firefox and our tests don't use FF, so there wasn't any way to add a test for it. But I did verify it on the docs playground and it works great in FF 97.
Fixes #2020.
> Work around Firefox bug with `'gregory'` calendar era names

- polyfill/lib/calendar.mjs
The ICU formats for the Hebrew calendar no longer output a month number, only the name. This PR works around this change. See https://bugzilla.mozilla.org/show_bug.cgi?id=1751833 for more context.
Fixes #2015.
> Handle number-less DateTimeFormat Hebrew month

- .github/workflows/test.yml
- polyfill/test/intl.mjs
Add Node 17 to CI for both Demitasse and cookbook tests, and switch Test262 from Node 16 to Node 17.
This PR is stacked on top of #2034 because without #2034 our tests will fail in Node 17.
> Add Node 17 to CI

- polyfill/lib/calendar.mjs
- polyfill/lib/timezone.mjs
- polyfill/test/usertimezone.mjs
References:
+ https://github.com/tc39/proposal-temporal/pull/1693
> Add missing branding checks

- polyfill/test/duration.mjs
- polyfill/test/instant.mjs
- polyfill/test/intl.mjs
- polyfill/test/plaindatetime.mjs
- polyfill/test/plaintime.mjs
- polyfill/test/zoneddatetime.mjs
test262 gained these tests as part of the recent batches of tests that
represented normative changes from the October and December TC39 plenary
meetings. We can now remove them from the Demitasse test suite.
> Remove tests that were ported to test262

- docs/calendar.md
- polyfill/index.d.ts
The [spec](https://tc39.es/proposal-temporal/#sec-temporal.calendar.prototype.fields) defines the return type of `Calendar.fields` as an Array. This commit aligns the docs and the TS types to what the spec says.
Fixes #2052
> Update return type of `Calendar.p.fields` in docs and TS types to match the spec

- polyfill/test/intl.mjs
Similar to the Node 14 breakage, this seems to be due to an update of ICU
on the Node 16 stable branch:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#commits
(search for "icu")
> Fix ICU text for Node 16 tests

- docs/strings.md
> Update docs about month/day standardization

- docs/plaindate.md
- docs/plaindatetime.md
This PR removes leftover text in the docs for `withCalendar` in PlainDate and PlainDateTime that is no longer true after we disallowed `.with({calendar})`.
> Remove incorrect text from `withCalendar` docs

- .github/workflows/test.yml
- polyfill/test/validStrings.mjs
It looks like the `validStrings.mjs` test tool had bitrotted somewhat. The commit that broke it (causes it to die very early, usually in the very first example string that it generates) is f6ac475e6131ab0f11dc641ae55dcf72e6ab1118. I can confirm that this simple change is enough to restore it to life.
In addition, I've added a run of `validStrings.mjs` to the pipeline. Had we had this check in place, we would have detected the breakage earlier.
> Unbreak validStrings.mjs

- polyfill/test/validStrings.mjs
- spec/abstractops.html
~~Also, remove redundant check in `ParseISODateTime`.~~
> Editorial: Adjust grammar for years to exclude -000000

- polyfill/test/instant.mjs
- spec/instant.html
Without this check, we hit an assertion failure in CreateTemporalInstant, so I'm considering the change to be editorial.
> Editorial: Add missing check in ParseTemporalInstant.

- spec/calendar.html
The markdown link is not understood by ecmarkup, and the table number might change in the future.
> Editorial: Fix rendering of table reference in ResolveISOMonth

- docs/strings.md
While answering https://github.com/tc39/proposal-temporal/issues/2109 I noticed a few typos and some unclear text in the string parsing page in the docs. This PR fixes these issues.
> Fix typos and add clarifications in parsing docs

- spec/timezone.html
Also add structured header, while we're at it.
Ref: #1413.
> Editorial: Fix number types in GetISOPartsFromEpoch

- spec/intl.html
CanonicalizeTimeZoneName ended up with two headers, probably due to a
rebase error.
Adds a zero-width space to the operation name, otherwise ecmarkup will not
allow a 262 and 402 version to be defined in the same document.
Finally, moves the note about superseding the previous definition to the
end of the clause. Otherwise ecmarkup will not render the "It performs the
following steps" text.
> Editorial: Fix CanonicalizeTimeZoneName formatting

- polyfill/lib/ecmascript.mjs
- polyfill/test/validStrings.mjs
The ParseISODateTime abstract operation instructs to throw a RangeError
exception if either the date string or time string is not a valid ISO 8601
string.
Previously, in the polyfill, when converting an ISO string to a PlainDate,
this validation would only happen for the date components and not the
time components. This brings the polyfill code into conformance, for which
I will add test262 tests shortly.
> Make polyfill ParseISODateTime conform to spec text

- spec/abstractops.html
See commit message for details.
> Normative: Don't validate numeric timezone in ToRelativeTemporalObject

- spec/plainyearmonth.html
The duration has to be negated up front, otherwise the _sign_ < 0 test is
wrong.
No change in functionality in the polyfill, which already handled this
correctly. This is already covered by tests.
Closes: #1863
> Normative: Fix sign in PlainYearMonth.subtract

- polyfill/lib/duration.mjs
- spec/duration.html
Thanks to DST, some dates in a year may have more or less
than 24 hours. We need to change the implementation of
`Duration.compare` when handling such cases. The solution is
to work only with years, months, weeks, and days; working
with more fine-grained data (hours, minutes, etc.) might be
mistaken in such cases because they may contain the
assumption that all days have 24 hours.
Thanks @justingrant for the solution!
closes #1791
> Normative: Fix compare for dates with unusual number of hours

- polyfill/lib/ecmascript.mjs
- spec/plainmonthday.html
- spec/plainyearmonth.html
> Normative: Emit reference information when calendarName = 'always'

- spec/intl.html
`sameTemporalType` checks for all Temporal types, but randomly omits `MonthDay`. It should be added. This probably is a normative change.
See discussion in https://github.com/tc39/proposal-temporal/issues/2037
> Normative: sameTemporalType checks for InitializedTemporalMonthDay

- spec/abstractops.html
fixes https://github.com/tc39/proposal-temporal/issues/1993
> Normative: Define unpadded hours and fix offset Etc/GMT timezones

- spec/plainyearmonth.html
Previously, the algorithm would mix a day in calendar space with a month
and year in ISO space.
An example of where this would go wrong immediately would be subtracting
a duration from a PlainYearMonth from a calendar where the month occurred
in ISO February but had more days in it than ISO February.
For example,
calendar = Temporal.Calendar.from('chinese');
m = Temporal.PlainYearMonth.from({ year: 2021, month: 1, calendar })
// (internally results in ISO reference date 2021-02-12)
m.daysInMonth  // => 29
m.subtract({ months: 1 })
This would previously try to call CreateTemporalDate(2021, 2, 29) and fail
due to mixing the day 29 in Chinese calendar space with year and month in
ISO calendar space.
However, in most cases this wouldn't even throw, but just produce wrong
results.
This was …
> Normative: Correct PlainYearMonth arithmetic for non-ISO calendars

- docs/cookbook/makeExpandedTemporal.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/test/timezone.mjs
- polyfill/test/zoneddatetime.mjs
- spec/plaindate.html
Fixes: https://github.com/tc39/proposal-temporal/issues/2082
Old format: `+000YYY`, e.g. `+000098-10-29T10:46:38`
New format: `0YYY`, e.g. `0098-10-29T10:46:38`
> Normative: Adjust ISO8601 representation for years between 1 BCE and 999 CE

- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindatetime.html
- spec/plaintime.html
This changes the internal slots of Duration to store mathematical values
instead of Number values. However, only mathematical values that are (1)
integers, and (2) representable by Number values, are allowed. This is
achieved by storing ℝ(𝔽(_value_)) in the internal slots of Durations and
in the fields of Duration Records.
This should solve the problem of type confusion between Number values and
mathematical values, and eliminate places where operations only defined on
mathematical values (such as abs() and floor()) were applied to the Number
domain.
This is a normative change because it means that it is now impossible for
the Number values NaN, +Infinity, -Infinity, and -0, as well as any
non-integer Number values, and not-exactly-representable Number values >MAX_SAFE_INTEGER, to be …
> Normative: Change internal slots of Duration to store mathematical values

- package-lock.json
- package.json
- spec.html
- spec/biblio.json
- spec/intl.html
cc @gibson042 
See https://github.com/tc39/ecma262/pull/2548 for a description of the annotation. The relevant information is now propagated in the biblio, so it can be used in proposals. In ecmarkup the annotation off by default because it may require manual annotation to be correct, but I've enabled it in this PR: I don't think any sites in this PR need annotation - there's no use of `[[Get]]` and friends directly, no weird stuff with generators, etc. (I didn't review extremely carefully, though.)
Also
- makes use of https://github.com/tc39/ecmarkup/pull/428 to get rid of the `&ZeroWidthSpace;` hack.
- marks a couple of uses of the phrase "time value" as not being [in the more precise ecma262 sense of the term](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-time-values-and- …
> Bump ecmarkup and enable "user code" annotation

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Where possible, observable calls originating from within Temporal, that
require an options argument, should pass `undefined` as that options
argument, rather than `{}` or `Object.create(null)`.
This allows the options parameter to be omitted when calling the abstract
operations CalendarDateAdd, DateFromFields, MonthDayFromFields, and
YearMonthFromFields, and assumes that it is `undefined` if omitted, so
that user code sees `undefined` as well when the options value is passed
along.
Whenever one of these abstract operations is invoked from within Temporal
with the default options, pass `undefined` instead of
! OrdinaryObjectCreate(null).
This also requires changing ToTemporalOverflow, ToTemporalDisambiguation,
and ToTemporalOffset to accept `undefined` in addition to a normalized
options …
> Normative: Consistently call observable operations with undefined options

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/calendar.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Naming these in line with all the other CalendarFoo operations that call
the 'foo' method of the given calendar, makes them easier to understand
when reading the spec text.
Closes: #1670
> Editorial: Rename DateFromFields to CalendarDateFromFields, etc.

- .eslintrc.yml
- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/fromLegacyDate.mjs
- docs/cookbook/fromLegacyDateOnly.mjs
- docs/instant.md
Following up from #2131, this PR makes a few minor clarifying changes to the `Instant` docs:
* Adds code samples to intro section to clarify the concepts discussed in the intro, and side-stepping some of the contentious questions raised in #2130.
* Wordsmiths the intro section
* Adds reference to RFC 3339
* Removes unnecessary (and, IMHO, confusing) unary `+` in a code sample
Fixes #2130.
> Clarify Temporal.Instant docs

- spec/abstractops.html
- spec/duration.html
- spec/zoneddatetime.html
The term "integral part of" isn't defined anywhere. Instead, we have an
abstract operation for this already.
Closes: #1890
> Editorial: Drop "integral part of" language

- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
Fixes #1548
Ref https://github.com/tc39/ecma262/pull/2730
* subtraction and negation as `-` (U+002D HYPHEN-MINUS) rather than `−` (U+2212 MINUS SIGN)
* multiplication as `&times;`
* loose inequality as `&le;`/`&ge;`
* inequality as `&ne;`
* infinity as `&infin;`
> Editorial: Improve consistency of mathematical conventions

- spec/duration.html
- spec/instant.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Most of the operations between add and subtract are the same except negative value. Refactor to shared AOs between them with a sign which either 1 or -1.
> Editorial: Refactor add/subtract to common AOs

- spec/instant.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
This introduces constants for 8.64 × 10^13 (nanoseconds per day) and
8.64 × 10^21 (max range of epoch nanoseconds) similar to msPerDay and
friends which are already in ECMA-262. ~~These constants are BigInt-valued.~~
Closes: #1589
> Editorial: Replace magic nanosecond numbers with constants

- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/timezone.html
This reuses several of the ECMA-262 operations dealing with time values, instead of duplicating the logic or resorting to a handwavy description. If the spec already contains this logic, we may as well use it, even if it means some awkward conversions between the ℝ and 𝔽 domains. Overall, it seems simpler.
See: #1641 (but doesn't close the issue, as there is still no reference yet for an ISO week-of-year algorithm)
> Editorial: Use time value operations in date calculations

- spec/plaintime.html
- spec/plainyearmonth.html
I think the normative change can be merged without consensus as it merely fixes a bug introduced by refactoring. If not, please let me know and I'll split it out into a separate PR to not hold up the editorial changes.
cc @FrankYFTang
> Editorial/Normative typo: Fix errors introduced in #2166

- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Most of the operations between until and since are the same except negative value. Refactor to shared AOs between them with a direction which either 1 or -1.
> Editorial: Refactor common alg of since/until into AOs

- spec/calendar.html
- spec/intl.html
Unlike the removed ToISODayOfYear AO, ECMA-262's DayWithinYear AO is zero-based.
Regression introduced in 6117d90.
---
If this is considered editorial again, please just reword the commit while squashing if necessary - still learning the rules there :)
> Normative typo: Fix off-by-one in Temporal.Calendar.prototype.dayOfYear()

- spec/duration.html
- spec/instant.html
- spec/zoneddatetime.html
This replaces more magic numbers with meaningful constants. (I missed this when I was grepping for "864" and "8.64")
> Editorial: use 2 × nsMaxInstant for the maximum difference of two Instants

- spec/abstractops.html
cf. https://tc39.es/ecma262/multipage/text-processing.html#sec-countleftcapturingparenswithin
> Editorial: Compare Parse Node positions using "contained within" rather than "enclosed by"

- spec/plaintime.html
> Editorial: Swap 'until' and 'since' arguments to DifferenceTemporalZonedDateTime

- spec/intl.html
- spec/plaindate.html
- Introduces an ISO Date Record type, to make it easier to write structured headers for PlainDate operations.
- Fixes some inadvertent consequences of #1928 by describing the circumstances under which the calendar-specific operations CalendarDateToISO and CalendarDateAddition may throw.
> Editorial changes around ISO Date Records

- spec/duration.html
This assertion was added in 7d5584c, but was not correct. Without the
assertion, the spec text is already correct because an undefined
relativeTo will throw RangeError in the ToTemporalDate step, but checking
explicitly is clearer to readers.
Closes: #2124
> Editorial: Remove faulty assertion

- spec/intl.html
* Reference arguments by the correct name
* Remove redundant operation argument type qualification
* Clarify the description of return values
* Add more helpful notes for month number/code operations
> Editorial: Improve the spec for Intl operations

- spec/plaintime.html
Old spec text diff (`until()` / `since()`):
> Editorial: Align DifferenceTemporalPlainTime with other Difference* AOs

- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
- Clause ID corrections
- Omit a default argument in an abstract operation invocation
- Use the machinery from Intl.NumberFormat v3 to perform our rounding operations (preparation for #1038 and #2191)
- ~~Finish standardizing the prose describing functions and methods (rest of #1465)~~
Closes: #1465
> Various editorial changes

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
This fixes the
```
(!) Circular dependency
lib/ecmascript.mjs -> lib/calendar.mjs -> lib/ecmascript.mjs
```
message when building.
> Polyfill: Move IsBuiltinCalendar to ecmascript.mjs.

- spec/calendar.html
- spec/intl.html
For clarity in the resulting state of ECMA-262.
> Editorial: Rename DefaultMergeFields to DefaultMergeCalendarFields

- spec/abstractops.html
- spec/timezone.html
* Add structured headers.
* Consistently employ ParseText.
* Consistently check parse results for Parse Nodes rather than productions.
* Consistently read and interact with code points from Parse Nodes ("source text matched by" or "an empty sequence" fallbacks) rather than strings/code units.
* Correctly use CodePointsToString for conversion.
* Create new "MV" aliases rather than replacing text/string values.
* Always use the same approach when reading fraction components:
1. substring of CodePointsToString(…) from 1
2. string-concatenation with *"000000000"*
3. substring
4. ToIntegerOrInfinity
> Editorial: Refactor Parse operations

- spec/instant.html
This commit editorially refactors `DifferenceTemporalInstant` to use a similar algorithm to what's used in other `Difference*` AOs like `DifferenceTemporalPlainTime` and `DifferenceTemporalPlainDateTime`.
> Editorial: Align `DifferenceTemporalInstant` with similar AOs

- spec/duration.html
- spec/instant.html
There is only one caller to ToLimitedTemporalDuration so there are no need to make it general and pass in a _disallowedFields_
> Editorial: Remove unnecessary ToLimitedTemporalDuration

- polyfill/lib/calendar.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
The [Abstract operations](https://tc39.es/proposal-temporal/#sec-temporal-abstract-ops) section has gotten rather unwieldy, and this is an attempt to pare it back a bit.
* Replace the narrow ToLargestTemporalUnit, ToSmallestTemporalUnit, and ToTemporalDurationTotalUnit operations with a single GetTemporalUnit.
* Move the Temporal units table into that operation.
* Leverage the units table in GetTemporalUnit and other operations.
Further tweaking could also simplify e.g. [DefaultTemporalLargestUnit](https://tc39.es/proposal-temporal/#sec-temporal-defaulttemporallargestunit).
> Editorial: Simplify operations

- spec/calendar.html
Fixes #2233
Also added extra assertions, so it's clearer why the `ℝ(...)` conversions are valid.
> Editorial: Add missing conversion to integer values

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/duration.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
There was a lot of redundancy between operations that construct "partial" vs. complete objects/records. These changes consolidate them with argument-based control, and leverage a single base PrepareTemporalFields wherever possible.
> Editorial: Consolidate partial operations

- spec/abstractops.html
Ensure inputs like `-0.5` and `9.1` are still throwing a RangeError instead of being treated as `0`.
> Editorial: Revert normative changes from #2243

- spec/calendar.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
"with duplicate elements removed" can be ambiguous, for example the result of `«"a", "b", "a"»` could either be `«"a", "b"»` or `«"b", "a"»`.
> Editorial: Add an explicit operation for merging calendar field names

- spec/calendar.html
- spec/intl.html
> Normative: Allow non-402 implementations to support non-iso8601 calendars

- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/plaindatetime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
This extracts the editorial aspects of #2245.
> Editorial: Use consistent invocations of Difference{Zoned,ISO}DateTime and alias names for object-copy steps

- spec/duration.html
> Editorial: Mark CreateDateDurationRecord in RoundDuration as fallible

- spec/calendar.html
This was a request from Kevin during editor review prior to Stage 3. I had
overlooked that it would cause an observable change, so I had prioritized
it for later.
However, Ms2ger pointed out that it is unfortunately a normative change
in these two cases (but not in the case of ISOYearMonthFromFields.)
I checked for other uses of PrepareTemporalFields where we could be using
the requiredFields argument. It appears to be only these three, and
ISOYearMonthFromFields is not an observable change.
Closes: #2099
> Normative: Adjust order of operations in ISO{Date,MonthDay}FromFields

- spec/abstractops.html
- spec/zoneddatetime.html
`MergeLargestUnitOption` is no longer called with `options == undefined`.
> Editorial: MergeLargestUnitOption is always called with an Object options value

- spec/plaintime.html
`RoundDuration` is infallible, because:
- The only possibly fallible step is the call to `CreateDurationRecord` in step 19. All other fallible steps aren't executed for this call site.
- `CreateDurationRecord` isn't fallible, because its inputs are computed from `DifferenceTime`, which can only return small enough numbers.
`BalanceDuration` is infallible, because:
- The only possibly fallible step is the call to `CreatTimeDurationRecord` in step 15. All other fallible steps aren't executed for this call site.
- And `CreatTimeDurationRecord` isn't fallible, because its inputs are small enough so they can't exceed `Number.MAX_VALUE`.
> Editorial: Mark two calls as infallible in DifferenceTemporalPlainTime

- spec/calendar.html
- spec/mainadditions.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
* ~~Refactor CalendarFields for better linearity~~
* Generalize CalendarMergeFieldNames into non-Temporal ECMA-262 amendments
> Editorial: Generalize CalendarMergeFieldNames out of Temporal

- spec/duration.html
- spec/plainyearmonth.html
AddDurationToOrSubtractDurationFromPlainYearMonth before this fix pass
a Duration Record to CreateNegatedTemporalDuration which expect the
input as Temporal.Duration (but not Duration Record) and output
is Temporal.Duration. This also cause the duration in
AddDurationToOrSubtractDurationFromPlainYearMonth could be either
a Temporal.Duration or a Duration Record. Change the first call to call ToTemporalDuration instead
> Use ToTemporalDuration in AddDurationToOrSubtractDurationFromPlainYearMonth 

- polyfill/lib/ecmascript.mjs
- spec/instant.html
This check was erroneous. It would throw if the wall-clock time
corresponding to the Instant, taken as if it were UTC, would be out of
range. We don't care about that, we only care if the actual Instant is out
of range.
This would throw when parsing the following valid Instant strings:
Temporal.Instant.from('-271821-04-19T23:00-01:00').epochSeconds === -86400e8
Temporal.Instant.from('+275760-09-13T01:00+01:00').epochSeconds === 86400e8
The reference polyfill requires a slightly different fix, because it uses
Date math in GetEpochFromISOParts. In this regard, it doesn't follow the
spec exactly, but the difference should not be observable.
> Normative: Remove check for Instant range before subtracting UTC offset

- spec/instant.html
- spec/intl.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
Split out from #2207, this applies the agreed-upon standard wording for functions and methods. (See https://github.com/tc39/ecma262/issues/2304#issuecomment-1157129964 and https://github.com/tc39/ecma262/pull/2592)
Closes: #1465
> Editorial: Consistent prose for functions and methods

- spec/plaintime.html
`RoundTime` always returns a valid time, so `CreateTemporalTime` can't fail.
> Editorial: Mark CreateTemporalTime in PlainTime.prototype.round as infallible

- spec/abstractops.html
- spec/timezone.html
ParseTemporalTimeZoneString erroneously assumed that any bare time zone
identifier or bracketed name would be an IANA name. That is not the case,
it can be a UTC offset name as well.
Closes: #1805
> Normative: Fix production for time zone name in time zone strings

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/intl.html
- spec/plainyearmonth.html
Use OrdinaryObjectCreate(null) in a few more places where we are creating
a plain object and then looking up properties on it, in order to avoid
prototype pollution. This is for consistency with most places where
GetOptionsObject is used.
Use it for fields objects as well, even though those are not passed to
user code; properties are still looked up on them, which may be observable
in the case of partial fields objects (in the with() methods).
Closes: #2098
> Normative: Use null-prototype objects in a few more places

- spec/calendar.html
`ToPositiveInteger(undefined)` calls `ToIntegerThrowOnInfinity(undefined)`, which in turn calls `ToIntegerOrInfinity(undefined)`, which in turn calls `ToNumber(undefined)`. `ToNumber` returns `NaN`, `ToIntegerOrInfinity` then returns `0`, `ToIntegerThrowOnInfinity` returns `0` unchanged, and finally `ToPositiveInteger` will throw a RangeError for `0`. That means it's not necessary to handle `undefined` before calling `ToPositiveInteger`.
----
Split from #2265.
> Editorial: Remove unnecessary checks for undefined before ToPositiveInteger

- polyfill/lib/ecmascript.mjs
- spec/plaindate.html
- spec/plaindatetime.html
In the fast paths for Temporal objects in ToTemporalDate and
ToTemporalDateTime, the overflow option should be validated (even though
it isn't used.) We do this for property bags and also for the case where
we call Temporal.PlainDate.from(plainDate) and
Temporal.PlainDateTime.from(plainDateTime), so it should be consistent.
The status quo wasn't the result of any decision, it was an oversight.
Closes: #2220
> Normative: Consistently check overflow options

- spec/abstractops.html
This was typo'd by accident while refactoring in ccef468, and therefore included the UTCDesignator production as well.
Closes #2342.
> Editorial: Correct TimeZoneNumericUTCOffsetNotAmbiguousWithDayOfMonth

- docs/ja/README.md
The added note means as follows:
> NOTE: This documentation is a partial translation of the original into Japanese. If you'd like to read the complete documentation and the most up-to-date information, please refer to the original.
> Add note about docs/ja

- spec/duration.html
- spec/zoneddatetime.html
Draft until https://github.com/tc39/ecmarkup/commit/3a872ca5c19872bf1ed5cd84ff8db1ecf7c3ddef is included in an ecmarkup version published to npm.
Ref https://github.com/tc39/proposal-temporal/pull/2306
Ref https://github.com/tc39/ecmarkup/pull/460
> Editorial: Remove unnecessary explicit link suppression

- spec/zoneddatetime.html
User-defined time zones can produce negative day lengths.
```js
class TimeZone extends Temporal.TimeZone {
#count = 0;
#nanoseconds;
constructor(nanoseconds) {
super("UTC");
this.#nanoseconds = nanoseconds;
}
getPossibleInstantsFor(dateTime) {
if (++this.#count === 2) {
return [new Temporal.Instant(this.#nanoseconds)];
}
return super.getPossibleInstantsFor(dateTime);
}
}
function test(epochNanoseconds, tomorrowEpochNanoseconds, testCases) {
for (let [roundingMode, expected] of Object.entries(testCases)) {
let timeZone = new TimeZone(tomorrowEpochNanoseconds);
let zoned = new Temporal.ZonedDateTime(epochNanoseconds, timeZone);
let result = zoned.round({ smallestUnit: "days", roundingMode });
console.log(result.epochNanoseconds, expected);
}
}
const oneDay = 24n * 60n * 60n * 1000n * 1000n …
```
> Normative: Disallow negative day lengths

- spec/plainmonthday.html
`new Temporal.PlainMonthDay(9, 30, "iso8601", 999_999_999_999_999)` will
now throw an error.
The spec polyfill already implements the same limitation.
> Normative: Disallow arbitrary integers for the reference ISO year in PlainMonthDay

- spec/timezone.html
In GetIANATimeZonePreviousTransition and GetIANATimeZoneNextTransition,
disallow returning a number of epoch nanoseconds that is outside of the
allowed range for Temporal.Instant, and return null instead.
Not throwing here is consistent with also not throwing in
SystemUTCEpochNanoseconds.
> Normative: Disallow out-of-range return from previous / next transition

- spec/abstractops.html
The IANA time zone database contains some legacy names which don't
follow the normal identifier guidelines, see <https://data.iana.org/time-zones/theory.html#naming>.
From <https://github.com/eggert/tz/blob/main/etcetera>, add:
- `Etc/GMT0`
From <https://github.com/eggert/tz/blob/main/backward>, add:
- `GMT0`
- `GMT-0`
- `GMT+0`
From <https://github.com/eggert/tz/blob/main/northamerica>, add:
- `EST5EDT`
- `CST6CDT`
- `MST7MDT`
- `PST8PDT`
But DO NOT add other names which don't follow normal identifier guidelines, like `SystemV/PST8PDT` or `Canada/East-Saskatchewan`, from <https://github.com/unicode-org/icu/blob/main/icu4c/source/tools/tzcode/icuzones>.
This changes ensures that `Temporal.TimeZone.from("PST8PDT")` works in addition to the already suppported `new …
> Normative: Support IANA legacy names

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
Fixes #2296
The result is consistent with my ECMA-402 proposal at https://github.com/tc39/ecma402/issues/691 (reject non-numeric input and perform validation of numeric input after truncation).
> Normative: Validate fractionalSecondDigits after truncation

- spec/duration.html
In BalanceDurationRelative, the handling of the relativeTo date was not
correct. Before several loops, it should not have been updated if the loop
was not entered.
Closes: #2341
> Normative: Correct BalanceDurationRelative algorithm

- spec/duration.html
The first three variables 'years', 'months', and 'weeks' of the infinity check added in 10e0ab3 are not defined anywhere, only 'days' and onward.
> Editorial: Remove undefined variables in BalancePossiblyInfiniteDuration

- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
`TemporalZonedDateTimeToString` doesn't call `ToString(timeZone)` when
`showTimeZone == "never"`. Do the same for `ToString(calendar)`.
`TemporalYearMonthToString` and `TemporalMonthDayToString` weren't
changed because both have to special-case non-ISO-8601 calendars.
> Normative: Avoid `ToString(calendar)` when the calendar-id is unused

- spec/duration.html
The declaration of newRelativeTo in step 10.b. is still 'in scope', so step 10.j. should use 'Set ... to' instead of 'Let ... be', like the assignment to newRelativeTo in step 10.f.
> Editorial: Fix duplicate 'Let newRelativeTo' in BalanceDurationRelative

- spec/abstractops.html
Remove the unnecessary " but not `Etc/GMT` ASCIISign UnpaddedHour" from TimeZoneIANANameTail line for TimeZoneIANAName :
because TimeZoneIANANameTail is defined as 
TimeZoneIANANameComponent
TimeZoneIANANameComponent / TimeZoneIANANameTail
and  "`GMT` ASCIISign UnpaddedHour" does not match TimeZoneIANANameComponent anyway with ASCIISign and UnpaddedHour
@ptomato @ryzokuken @sffc
> Editorial: Remove unnecessary exception rule

- polyfill/test/validStrings.mjs
- spec/abstractops.html
Technically normative in adding support for edge case like the following:
* HHMMSS[timeZoneName] where HHMMSS on its own is ambiguous with YYYYMM
(e.g. "112312[America/New_York]")
* HHMM-HH[timeZoneName] where HHMM-HH on its own is ambiguous with YYYY-MM
(e.g., "1001-12[-00:01]")
...but the polyfill already works like that.
> Normative: Improve the "NotAmbiguous" grammar

- polyfill/lib/ecmascript.mjs
- polyfill/package.json
- polyfill/test/validStrings.mjs
- spec/abstractops.html
> Normative: Reject an ambiguous time string even with a calendar

- spec/calendar.html
- spec/intl.html
Also refactor ToISODayOfYear and ToISODayOfWeek.
@ptomato Based on algorithm in https://github.com/tc39/proposal-temporal/blob/main/polyfill/lib/ecmascript.mjs#L2387
> Editorial: Spec out ToISOWeekOfYear w/ algorithm

- polyfill/lib/calendar.mjs
- spec/intl.html
Previously, the spec hardcoded "era" and "eraYear" as extra fields that
should be accessed on the property bags passed to the dateFromFields(),
yearMonthFromFields(), and monthDayFromFields() methods of
Temporal.Calendar.
Instead, the extra fields should be obtained by ~~calling~~consulting the calendar's
fields() method. This accommodates calendars that require additional extra
fields, beyond "era" and "eraYear".
~~I'm not sure whether this is ultimately a normative change or not, but if
it, is then we can also fix an observable inconsistency in the order of
operations between the three ...FromFields() methods, while we are here
anyway. (If not, then revert that line before submitting this.)~~ (I'm moving the normative change to another PR.)
Closes: #1789
> Editorial: Accommodate calendar-specific fields in non-ISO ...FromFields() methods

- polyfill/test/validStrings.mjs
- spec/abstractops.html
Parsing an Instant string already ignores the time zone name annotation if
one is present, and only takes the offset into account. It's inconsistent
to throw if a calendar annotation is present but not if a time zone name
annotation is present.
Closes: #2143
> Normative: Accept and ignore calendar annotation in Instant string

- spec/calendar.html
TemporalInstantToString calls TemporalDateTimeToString with undefined
for calendar and "never" for showCalendar, which then forwards these
values to MaybeFormatCalendarAnnotation as is.
This means that the current type description is inaccurate; correct this
by also considering undefined a valid value and add an assertion to
ensure undefined is never passed if showCalendar is "auto" or "always".
> Editorial: Allow undefined for calendar in MaybeFormatCalendarAnnotation

- spec/duration.html
- spec/instant.html
- spec/zoneddatetime.html
In DifferenceInstant, the difference between the two epoch nanoseconds values is conceptually a Duration. It's not correct to call RoundTemporalInstant on it. This normative change brings the spec text in line with what was intended (and is currently tested in test262, which means those [failing tests](https://github.com/tc39/proposal-temporal/pull/2210) should pass if the change in this PR is made.)
Closes: #2320
> Normative: Fix rounding in DifferenceInstant

- polyfill/lib/calendar.mjs
- spec/calendar.html
- spec/intl.html
Previously, the monthDayFromFields() method of non-ISO calendars behaved
differently from dateFromFields() and yearMonthFromFields(), checking the
overflow option after accessing the fields whereas the other two checked
the overflow option first.
This normative change fixes this inconsistency.
Split out from #2199 which does not need to be normative. Note this will need a rebase when #2199 is merged.
> Normative: Fix inconsistency in order of observable operations in ...FromFields() for non-ISO calendars

- docs/duration.md
- docs/instant.md
- docs/plaindate.md
- docs/plaindatetime.md
- docs/plaintime.md
- docs/plainyearmonth.md
- docs/zoneddatetime.md
- polyfill/lib/ecmascript.mjs
- polyfill/test/ecmascript.mjs
- polyfill/test/expected-failures.txt
- spec/abstractops.html
- spec/zoneddatetime.html
after the landing of https://github.com/tc39/proposal-temporal/pull/2207
GetUnsignedRoundingMode now includes additional RoundingModes
expand, halfCeil, halfFloor, halfTrunc and halfEven.
Sync spec text in RoundNumberToIncrement, ToTemporalRoundingMode,
NegateTemporalRoundingMode to match it.
@sffc @ptomato
> Normative: Sync the set of RoundingMode

- spec/calendar.html
- spec/intl.html
- spec/plainyearmonth.html
* Simplify ResolveISOMonth
* Improve alias names in ResolveISOMonth
* Merge ISOMonthCode and BuildISOMonthCode
* Remove trivial operation IsValidISOMonth
* Remove trivial operations ISO{Year,Month,Day}
> Editorial: Simplify ISO calendar operations

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/duration.html
`CalendarDateAdd` was changed to avoid repeated lookups of `"dateAdd"`, but we still repeatedly lookup `"dateAdd"` when `CalendarDateAdd` is called from `MoveRelativeDate`.
> Normative: Perform a single "dateAdd" lookup for MoveRelativeDate

- polyfill/lib/ecmascript.mjs
- polyfill/test/expected-failures.txt
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- Several changes to the reference code to avoid precision loss or rounding errors due to the use of Numbers, in cases where the spec uses reals and therefore doesn't lose precision. Hopefully this will be helpful to implementors as well. Thanks to @anba who wrote a bunch of tests exercising these cases.
- Other minor changes.
> Editorial: Bring reference code in line with spec re. precision

- spec/zoneddatetime.html
Step 5.2 uses the non-existent "balanceResult", which was forgotten to be updated in e192f2c3a870c29be4d586d423f7f47361d88543.
This changes "balanceResult" to "result" to match all the other uses of DifferenceInstant.
> Editorial: Rename balanceResult to result on step 5.2 of DifferenceTemporalZonedDateTime

- spec/abstractops.html
This was forgotten in 96133586f0f413f27a037a68301c83409df723d3
I'm not sure if this is editorial or normative. I went for editorial as it's just changing the accepted values in the parameter and was not observably enforced elsewhere.
> Editorial: Sync the set of rounding modes for RoundNumberToIncrementAsIfPositive

- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
The validation was already mentioned in the preamble of each operation, but it wasn't actually performed.
> Normative: Validate results of Calendar operations

- spec/duration.html
These 2 assertions are currently not always true in the spec caused by bug in upper part of the spec but they need to be true before calling CreateTemporalDuration the line after.  Step 6-e currently cause the violation. We need days to be integer to pass into CreateTemporalDuration
```
e. Set days to days + result.[[Days]] + result.[[Nanoseconds]] / result.[[DayLength]].
```
@anba @ptomato @ryzokuken 
It does not fix https://github.com/tc39/proposal-temporal/issues/2246 but make the fix of https://github.com/tc39/proposal-temporal/issues/2246 easier to spot the issue
> Editorial: Add explicit assertion for days in RoundDuration

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/package.json
Various changes for things I have in progress, that can already be reviewed:
- Update of es-abstract to use the ES2022 versions of the operations
- Avoid observably calling `Array.prototype[Symbol.iterator]` in several places; more of this to follow
> Polyfill: avoiding observable operations

- polyfill/lib/ecmascript.mjs
- spec/calendar.html
...and to prevent unnecessarily-observable calls to iterator methods for purely internal purposes.
> Normative: Refactor CalendarFields for better linearity

- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainmonthday.md
- docs/plainyearmonth.md
- docs/zoneddatetime.md
- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
The IETF SEDATE Working Group Internet-Draft, "Date and Time on the Internet: Timestamps with additional information" has reached agreement on all the open issues. This implements the conclusions of that draft RFC, which defines a date-time format called Internet Extended Date-Time Format (abbreviated IXDTF).
IXDTF defines a grammar and semantics for annotations that can be appended to RFC 3339 strings. We were already using these annotations informally in Temporal for time zones and calendars. The main things that have to change are that annotations can have a "critical" flag ("!") which in Temporal has no effect on time zone and calendar annotations; and that multiple annotations are possible, where unknown ones are ignored unless they are marked critical.
As part of this, the last two …
> Implement IETF SEDATE conclusions

- spec/timezone.html
The bug was introduced in 654e300db9882fc985840e11f35525864848f8fd
> Editorial: Fix missing variable in CreateTemporalTimezone

- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindate.mjs
- spec/calendar.html
- spec/instant.html
- spec/plaindate.html
- spec/timezone.html
The current spec requires an unnecessary observable HasProperty operation when you call `Temporal.Calendar.from(temporalCalendarInstance)` and likewise for TimeZone. This change adds a fast path for these objects.
Closes: #2355
> Normative: Fast-path ToTemporal{Calendar,TimeZone} when the object is already an instance

- polyfill/lib/ecmascript.mjs
This early return is present in the spec text but was missing from the reference code. No change in the spec text, this just brings the code in line with the specification.
A test for this is in https://github.com/tc39/test262/pull/3686, we'll need to update the pinned test262 version before merging this, since otherwise the (faulty) existing test will break.
> Polyfill: Implement early return in UnbalanceDurationRelative as per spec

- package-lock.json
- package.json
- spec/calendar.html
- spec/intl.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
This version of ecmarkup brings in a few linters which require some fixes in the spec text.
- Fixes for typos in variable names
- Fixes for "Set _x_ to" without a preceding "Let _x_ be"
- Add suppression for false-positive lines that refer to the _comparefn_ parameter of %Array.prototype.sort%
- Remove the  workaround for avoiding auto-linking to deleted AOs
> Editorial: Upgrade to ecmarkup 15.0.2

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/package.json
- polyfill/rollup.config.js
- spec/abstractops.html
- spec/calendar.html
- spec/intl.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
The first three commits are editorial cleanup, while the rest include technically normative changes (albeit minor).
This stemmed from the surprising observation that [AddDurationToOrSubtractDurationFromPlainYearMonth](https://tc39.es/proposal-temporal/#sec-temporal-adddurationtoorsubtractdurationfromplainyearmonth) uses `key+value` enumeration to clone _options_, while [MergeLargestUnitOption](https://tc39.es/proposal-temporal/#sec-temporal-mergelargestunitoption) and [ECMA-402 Temporal.Calendar.prototype.mergeFields](https://tc39.es/proposal-temporal/#sup-temporal.calendar.prototype.mergefields) and [DefaultMergeFields](https://tc39.es/proposal-temporal/#sec-temporal-defaultmergefields) use `key` enumeration followed by a for-each loop that Gets each source property in analogous …
> Normative: Always use CopyDataProperties for object copy/merge

- docs/cookbook/stockExchangeTimeZone.mjs
- polyfill/lib/ecmascript.mjs
- spec/zoneddatetime.html
- Stricter validation for values returned from NanosecondsToDays AO, to protect against custom time zones / calendars doing inconsistent things
- ~~Removal of 24-hour limit for getOffsetNanoseconds - this limit was leading to inconsistencies in custom time zones (see cookbook example)~~
- Add some code to the NYSE custom time zone cookbook example that exercises these corners
Closes: #2357
> Normative: Validation of NanosecondsToDays and getOffsetNanoseconds

- docs/zoneddatetime.md
> Docs: mention `timeZone` property being used by `ZonedDateTime.from`

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
This implements the proposed renames of:
- ToIntegerThrowOnInfinity → ToTruncatedInteger
- ToPositiveInteger → ToTruncatedPositiveInteger
- ToIntegerWithoutRounding → ToEnforcedInteger
The abstract operations get structured headers and are rewritten so that they call ToNumber instead of ToIntegerOrInfinity, which should make it easier to tell what's going on when reading them.
Throws in a couple of fixes for editorial bugs that had to do with these integer conversion operations.
See: #2112
Closes: #2240 
Closes: #2389
> Editorial: Changes around integer conversion operations

- docs/zoneddatetime.md
- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/mainadditions.html
- spec/plaintime.html
- spec/timezone.html
This implements the part of #2254 that is possible to do without any changes that are observable from JS. It reorders the tables of Duration Record fields and TemporalTimeLike Record fields so that the fields are in magnitude order, and enforces the property access in alphabetical order by sorting the list of fields. The net result is that nothing changes, but the spec text is more robust against accidental observable modifications.
Also includes some minor editorial and docs fixes.
> Editorial: Reorder table fields by magnitude

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
- Fix a bug in the reference code so that it's compliant with the spec text
- Fix faulty assertions in Calendar methods (#2384) (cc @rkirsling)
- Give a couple of AOs clearer names (#2223)
> A few editorial improvements

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/instant.html
- spec/zoneddatetime.html
- Mark a few operations as infallible
- Fix a few places in the reference code where observable operations were ordered differently than in the spec
> Editorial change and reference code compliance

- spec/instant.html
- spec/zoneddatetime.html
In Temporal.{Instant,ZonedDateTime}.epoch{S,Millis,Micros}econds, the rounding should use floor instead of truncate semantics, in order to always truncate towards the beginning of time, as .toString() and .round() do.
Closes: #2423
> Normative: Use floor instead of truncate in epoch time getters

- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/timezone.html
In order to prevent bugs like `new Temporal.ZonedDateTime(0n, cal, tz)` (where the calendar and time zone arguments are switched, silently poisoning the object) ToTemporalCalendar should throw if it encounters a Temporal.TimeZone instance, and ToTemporalTimeZone should throw if it encounters a Temporal.Calendar instance.
Includes implementation in the reference code.
Co-authored-by: @Aditi-1400 
Closes: #2354
> Normative: Throw on conversion from TimeZone to Calendar and vice versa

- docs/calendar.md
- docs/plaindate.md
- docs/plaindatetime.md
- docs/zoneddatetime.md
- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/calendar.html
- spec/intl.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/zoneddatetime.html
This implements the yearOfWeek support that we discussed in the Temporal champions meeting of 2022-10-13: https://github.com/tc39/proposal-temporal/issues/2405#issuecomment-1279342034
Test262 tests are in https://github.com/tc39/test262/pull/3696
I've split it into 3 separate commits (normative change, docs, reference code) for ease of review. For the TC39 plenary, only the first commit is the normative change that we are discussing; the rest is informational.
Closes: #2405
> Normative: yearOfWeek support

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
Previously, the abstract operation ToTemporalRoundingIncrement was technically unimplementable because of trying to calculate ℝ(infinity).
Address this by separating out the case where there is no maximum for roundingIncrement into a separate code path from the case where there is a maximum (which goes into a separate abstract operation, ValidateTemporalRoundingIncrement.)
The separation is a bit awkward; it would be better if the truncated integer was returned from ToTemporalRoundingIncrement, instead of the original Number value, but that's not possible without a normative change because currently, the range check is done with the original Number value. (This is inconsistent with fractionalSecondDigits, where the range check is done with the truncated integer.) I'm planning to make this …
> Editorial: Separate validation of roundingIncrement option

- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
Summary of discussion from https://github.com/tc39/proposal-temporal/issues/2379#issuecomment-1248557100:
In keeping with the IXDTF format which extends the grammar of RFC 3339 with any number of annotations, we should allow annotations after the short YYYY-MM PlainYearMonth and MM-DD PlainMonthDay forms.
If we were to allow UTC offsets ±UU[:UU] alongside the time zone annotation, that would be ambiguous in one case: YYYY-MM-UU would be ambiguous with YYYY-MM-DD. This forced us to take another look at ISO 8601 and realize that YYYY-MM-DD-UU and YYYY-MM-DDZ are actually not defined by ISO 8601. Although they are not forbidden either, but we don't have any reason to introduce this notation given the set of Temporal types. Therefore, UTC offsets are disallowed after any date-only notation …
> Normative: Allow annotations after YYYY-MM and MM-DD

- polyfill/lib/calendar.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
Spec algorithms should do one of two things to an object that is passed in from user code, depending on the situation:
- Perform a Get on each of a list of predefined property keys in alphabetical order, and read them into a Record. The alphabetical order should be enforced rather than implicit by table order. This action is appropriate when the list of property keys is known beforehand (although it may include extra calendar fields, so not necessarily known at spec-writing time) and/or when some of the properties are allowed to be absent from the object. An example of this is [ToTemporalTimeRecord](https://tc39.es/proposal-temporal/#sec-temporal-totemporaltimerecord).
- Use CopyDataProperties to access each property on an object in iteration order and copy it onto a null-prototype …
> Normative: Alphabetize observable property accesses

- docs/README.md
Fixes #2418. Related to #2175.
Creating a PR as suggested.
> Remove Unix Epoch references from Temporal.Now.instant()

- polyfill/lib/ecmascript.mjs
- spec/zoneddatetime.html
While working on test262 coverage for the varied edge cases of NanosecondsToDays, I realized step 21 and step 23 - respectively, `nanoseconds < 0 and sign = 1` and `abs(nanoseconds) ≥ abs(dayLengthNs)` - are dead code. Step 21 can never be true without step 19 also being true, so the step will never be reached. Step 23 can never be true without either step 21 or 22 being true, and so the step will also never be reached.
I talked to @anba about it, and he helped me immensely by coming up with concrete proofs of both of those assertions, which makes this a non-normative change.
A summary of the proof for step 23 is as follows:
Because all of the assertions can only be reached following step 18.c: `(nanoseconds - dayLengthNs) × sign ≥ 0`, if `sign = 1`, this means `nanoseconds < …
> NanosecondsToDays: Change unreachable RangeErrors to assertions.

- spec/calendar.html
- spec/intl.html
- spec/plaindate.html
...rather than e.g. the number of the last day.
Fixes #1315
> Editorial: Clarify that DaysInMonth operations return a count of days

- spec/duration.html
- spec/instant.html
- spec/zoneddatetime.html
There were a few remaining abstract operations that operate on numeric types, that didn't have those types spelled out either via structured headers or via assertions.
This converts those operations to use structured headers. That also allows ecmarkup to point out places where a ! notation was used superfluously.
This revealed that the return type of RoundTemporalInstant wasn't correct: it should have been a BigInt, since it returns a number of epoch nanoseconds.
Closes: #1413
> Editorial: Convert operations with numeric arguments to structured headers

- polyfill/lib/ecmascript.mjs
- spec/duration.html
At this point in the algorithm, we need to find the number of whole years contained within _days_. Contrary to the assertion, and to the requirement of CreateTemporalDuration, _days_ is not an integer. The algorithm is faulty and unimplementable as written.
However, the answer (_yearsPassed_) is still correct if we temporarily discard the fractional part in the call to CreateTemporalDuration.
Rename the variables _daysLater_ and _daysDuration_ to _wholeDaysLater_ and _wholeDaysDuration_, respectively, to emphasize that they potentially represent a different value from _days_.
The bug was not present in the reference code because it calculates slightly differently with floats, instead of reals as in the spec text. Still, rename the variables there as well. While we are here, correct the …
> Editorial: Avoid faulty assertion in RoundDuration about integer days

- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/now.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/instant.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
Renames and clarifications to address a few of the remaining checklist items in #1502. While we're here, convert the renamed AOs to have structured headers.
> Various editorial issues from Anba's feedback

- meetings/agenda-minutes-2022-02-03.md
- meetings/agenda-minutes-2022-02-17.md
- meetings/agenda-minutes-2022-03-03.md
- meetings/agenda-minutes-2022-03-17.md
- meetings/agenda-minutes-2022-04-28.md
- meetings/agenda-minutes-2022-05-11.md
This is the minutes backlog from the champions meetings in the first half of 2022.
> Publish minutes backlog, part 1

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- polyfill/ci_codecov_test262.sh
- polyfill/package.json
Support CI tests in Node 19, and specifically supports running with ICU 72 which contains CLDR 42 which broke a lot of tests. 
This PR is a counterpart to https://github.com/js-temporal/temporal-polyfill/pull/203, but this PR was somewhat easier because there's no TS-specific issues to contend with like there are in the other repo. 
* Update GH actions to latest versions
* Use Node19 on all other actions and tests
* Run Test262 against Node 19 ~~,18, 16, 14~~ _Removed older Node version testing at @ptomato's request; instead, he'll work with Test262 maintainers to avoid downlevel-incompatible tests from getting into Test262._
* ~~Extend expected-failures.txt handling so that some tests can be expected to fail only on some Node versions, but pass on later versions.~~
* Upgrades …
> Run CI tests in Node 19 / ICU 72 / CLDR 42

- polyfill/index.d.ts
This was implemented in d450be195a81228d284777969bedd9e0475400bd, but the types were not updated to reflect the newly acceptable rounding modes.
> Update d.ts file with new rounding modes.

- spec/instant.html
- spec/intl.html
Elements are _technically_ allowed inside ecmarkdown `*` language value format wrappers, but it seems like bad form and slightly confusing (since there is no similar form within the language to express those values). This PR replaces such uses, all of which involve BigInt powers of 10.
```diff
-*10<sup>x</sup>*<sub>ℤ</sub>
+ℤ(10<sup>x</sup>)
```
> Editorial: Remove non-text content from `*` format wrappers

- docs/balancing.md
- docs/calendar.md
- docs/cookbook/makeExpandedTemporal.mjs
- docs/duration.md
- docs/plainmonthday.md
- docs/plainyearmonth.md
- docs/strings.md
- docs/zoneddatetime.md
- polyfill/lib/zoneddatetime.mjs
- spec/intl.html
- spec/plaindatetime.html
- spec/zoneddatetime.html
- Refer to "ISO 8601 calendar" instead of "ISO calendar"
- Remove some dead code that became dead when 'rebasing' the proposal on a newer commit of ECMA-402 that already included this code
- Minor language and readability tweaks
> Editorial: Various changes

- spec/instant.html
Made changes to DifferenceInstant operation to prevent loss of precision.
The approach is to convert the nanoseconds into seconds, milliseconds ≤ 999, microseconds ≤ 999, and
nanoseconds ≤ 999 before passing those values to `RoundDuration`. 
Fixes: #2419
> Normative: Fixed DifferenceInstant

- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/intl.html
Fixes #2443
It looked to me like the TimeZone operations already behaved appropriately[^1], but please verify in review (along with confirmation that I have preserved the distinction between fields that must be positive vs. those that can be zero or negative).
test262 pull request: https://github.com/tc39/test262/pull/3761
[^1]: [GetOffsetNanosecondsFor](https://tc39.es/proposal-temporal/#sec-temporal-getoffsetnanosecondsfor) requires `getOffsetNanosecondsFor` to return an integral Number with absolute value no greater than [nsPerDay](https://tc39.es/proposal-temporal/#eqn-nsPerDay), and [GetPossibleInstantsFor](https://tc39.es/proposal-temporal/#sec-temporal-getpossibleinstantsfor) requires `getPossibleInstantsFor` to return an iterable of Temporal Instant instances.
> Normative: Reject invalid output from custom Calendar/TimeZone methods

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Changes to the order of observable operations in
- PlainDate.p.with
- PlainDateTime.p.with
- PlainMonthDay.p.with
- PlainTime.p.with
- PlainYearMonth.p.since
- PlainYearMonth.p.until
- PlainYearMonth.p.with
- ZonedDateTime.p.with
Swapping the PrepareTemporalFields calls in ZonedDateTime.p.with exposed another unnecessary user call: the 'timeZone' field was observably read from the receiver and from the object returned from mergeFields(), but never used. This is fixed as well.
Closes: #2462
> Normative: Validate receiver fields before fields of any param objects

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
Rounding increments are usually limited. In a few cases (years, months, weeks, and days for Temporal.Durations), they were previously only limited by being required to be finite. This introduces a limit of 1e9 for these previously unlimited cases.
1e9 fits in a 32-bit integer, to make things simpler for implementations, but is clearer to explain in end-user documentation than UINT32_MAX.
Closes: #2458
> Normative: Upper limit on rounding increments

- spec/calendar.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
As per TC39 plenary, the specification should include informative notes indicating where ECMA-402 extends prototypes with additional properties.
Closes: #2169
> Editorial: Add notes about extension points for ECMA-402

- docs/plaindate.md
- docs/plaintime.md
There's some typos in code samples of docs of `toZonedDateTime` for both PlainDate and PlainTime.  While I was there, I moved around a sentence for clarity.
> Fix broken code in `Plain{Date|Time}.p.toZonedDateTime` docs

- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/intl.html
Fixes: https://github.com/tc39/proposal-temporal/issues/2310
Also renames `DefaultMergeCalendarFields` to `ISOMergeCalendarFields` since it is no longer a default.
> Normative: Remove fallback paths in CalendarFields and CalendarMergeFields

- spec.html
Thanks to @bakkot for teaching me about [`<emu-not-ref>`](https://tc39.es/ecmarkup/#emu-not-ref) !
> Prevent auto-link of "safe" in "DST-safe"

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/intl.html
Note, DefaultMergeCalendarFields still exists in this branch but one use of it would be removed in #2310, and #1418 would consolidate this definition of Temporal.Calendar.prototype.mergeFields() with the earlier one in the 262 part of the proposal. So ultimately, this would be the only definition of mergeFields.
To do, if we decide this is the right approach:
- Check that all the places that might produce abrupt completions are correct
- Change the reference code to follow this spec
Closes: #2407
> Normative: tighten language in non-ISO-calendar mergeFields()

- polyfill/lib/calendar.mjs
- spec/intl.html
The process for choosing the reference ISO day and reference ISO year for non-ISO calendars was missing from the descriptions of `yearMonthFromFields` and `monthDayFromFields`, respectively.
`monthDayFromFields` gets a separate operation CalendarMonthDayToISOReferenceDate explaining how to choose the reference year. Update the description of CalendarDateToISO to match the new, more detailed, language added there.
Closes: #2461
> Normative: Clarifications of calendar-dependent parts of yearMonthFromFields and monthDayFromFields

- docs/calendar.md
Adds documentation to address calendars that vary across years, most commonly because of leap days/months, or (rarely) for other reasons like the Julian=>Gregorian transition.
Also describes invariants that custom calendars that skip dates are expected to follow, and that Temporal users can rely on.
> Docs for leap days/months and skipped dates

- spec/timezone.html
The definition is already being added to ECMA-262 by https://tc39.es/proposal-temporal/#sec-ecmascript-language-types-string-type .
> Editorial: Remove redundant redefinition of "ASCII-case-insensitive"

- polyfill/lib/calendar.mjs
- spec/calendar.html
- spec/intl.html
Fixes #2504
test262 PR: https://github.com/tc39/test262/pull/3789
> Normative: Prevent mergeFields from reordering properties

- polyfill/lib/calendar.mjs
- polyfill/package.json
- polyfill/runtest262.mjs
- polyfill/test/expected-failures.txt
Fixes #2383.  Fixes #2537.  These two fixes were in adjacent code so it made sense to combine them into one PR. (Albeit in separate commits.)
Also updates temporal-test262-runner so we can use the `timeoutMsecs` option to avoid future infinite loops like #2383 from preventing our tests from running to completion.
> Fix two bugs in non-ISO calendar `dateUntil`

- docs/calendar.md
- docs/timezone.md
- polyfill/index.d.ts
- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/timezone.html
Closes: #2104 
Note, this PR is staged on top of #2482. For review purposes, look only at the last four commits, or look at [this comparison](https://github.com/tc39/proposal-temporal/compare/1808-string-builtin-calendar...2104-nested-property-bags-iso-strings?expand=1).
> Normative: nested property bags and ISO strings in Calendar/TimeZone.from

- polyfill/lib/intl.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/intl.html
See PR #2479 about which a consensus was not reached. This is a fallback solution. This change allows Temporal.ZonedDateTime.prototype.toLocaleString to work by overriding the time zone at the time of creating an Intl.DateTimeFormat object and formatting the corresponding Temporal.Instant, but disallows calling any of the Intl.DateTimeFormat methods on a Temporal.ZonedDateTime.
NOTE: The reference code does not implement the spec exactly as written. It observably modifies the options before passing them to the real Intl.DateTimeFormat constructor. The behaviour described in the spec is the correct behaviour.
> Normative: Make ZonedDateTime.toLocaleString work without DateTimeFormat

- polyfill/lib/ecmascript.mjs
I assume this was used in the past, but it's not used anymore.
> Remove unused es-abstract ToLength import

- polyfill/lib/ecmascript.mjs
The spec says that this AO returns `~unused~`, but the polyfill currently returns an object.
See https://github.com/tc39/proposal-temporal/blob/main/spec/mainadditions.html#L160
> Adjust polyfill CopyDataProperties return type to match spec

- polyfill/ci_codecov_test262.sh
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/legacydate.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/package.json
- polyfill/runtest262.mjs
- polyfill/test/expected-failures.txt
- spec/abstractops.html
- spec/calendar.html
- spec/timezone.html
- Some minor editorial commits to the spec
- Some optimizations to the reference code
- Particularly to GetNamedTimeZoneNextTransition and GetNamedTimeZonePreviousTransition so that we can correctly run some test262 tests that Anba wrote
I recommend reviewing this commit by commit.
> Editorial fixes and time zone optimizations

- polyfill/lib/calendar.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/legacydate.mjs
- polyfill/lib/now.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/ecmascript.mjs
- polyfill/test/validStrings.mjs
It'd be a lot easier to port commits to temporal-polyfill if `ecmascript.mjs` exported functions instead of a huge object.
Would it be OK to do this refactor here in this repo?
No worries if for some reason this isn't OK. 
cc @12wrigja 
When reviewing this, you'll probably want to use GitHub's "Hide whitespace" option, because indentation changed in ecmascript.mjs and without ignoring whitespace the diffs get confused and it looks like almost every line has changed.
> Polyfill: Refactor ES object into exported functions

- polyfill/lib/ecmascript.mjs
Currently `CalendarEqualsOrThrow` (which is an AO in the polyfill but not in the spec, per comments in the code), returns `true`, returns `undefined`, or throws. This variation in return values doesn't break anything because the return value is never used by any callers, but to prevent future problems this commit renames it to `ThrowIfCalendarsNotEqual` and always returns `undefined`.
> Polyfill: rename CalendarEqualsOrThrow => ThrowIfCalendarsNotEqual

- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/plaindate.html
- spec/timezone.html
This PR fixes issue #2315, by redefining following [Date operations](https://tc39.es/ecma262/#sec-date-objects) to calculate in mathematical values instead of Number values:
- MakeDay -> ISODateToEpochDays
- MakeDate -> EpochDaysToEpochMs
- DaysInYear -> MathematicalDaysInYear
- DayFromYear -> EpochDayNumberForYear
- TimeFromYear -> EpochTimeForYear
- YearFromTime -> EpochTimeToEpochYear
- InLeapYear -> MathematicalInLeapYear
- MonthFromTime -> EpochTimeToMonthInYear
- DayWithinYear -> EpochTimeToDayInYear
- DateFromTime -> EpochTimeToDate
- WeekDay -> EpochTimeToWeekDay
These operations would be unified when https://github.com/tc39/ecma262/issues/1087 is fixed
> Normative: Change date AOs to accept mathematical values

- polyfill/lib/ecmascript.mjs
- spec/plainyearmonth.html
Addresses #1315.
Updates Plain Year Month arithmetic to use a version of `.with({ day: 1 }).add({ months: 1 }).subtract({ days: 1}).day` to get the index of the last day of the month. Chose this over the alternative of `.with({ day: 1 }).add({ days: yearMonth.daysInMonth() - 1]}).day` beacuse the `GetMethod(calendar, "dateAdd")` can be reduced to one GetMethod.
Updates polyfill, no changes needed to non-ISO calendars because there are no skipped days in any of the calendars it implements.
Updates to docs pending, will update PR when ready.
Will prepare separate editorial PR to make language of CalendarDateDaysIn{Week,Month,Year} and CalendarDateMonthsInYear more consistent, but current phrasing is correct - nothing needed to address this.
> Normative: Treat `daysInMonth` as the count of days in a month

- polyfill/lib/ecmascript.mjs
Replaces one use of `ObjectCreate` followed by `CopyDataProperties` with `CopyOptions`.
This pattern is used everywhere else in Temporal but was missed in #2484.
> Polyfilll: ObjectCreate + CopyDataProperties => CopyOptions

- spec/timezone.html
This PR adds a CanonicalizeTimeZoneOffsetString AO which converts an offset string into its canonical form.
This pattern occurs twice in existing spec text, and will likely be needed in more places after ECMA-402 supports passing offset strings as the `timeZone` option to InitializeDateTimeFormat.
> Editorial: DRY for canonicalizing offset strings

- spec/timezone.html
This editorial PR clarifies that the [[OffsetNanoseconds]] and [[Identifier]] internal slots in the TimeZone type are mutually exclusive. This will help clarify that implementers should only store offset time zone information once, not once in each slot.
It also replaces `*undefined*` with `~empty~` to better match current practice elsewhere in the spec.
Finally, it adds a note clarifying that although [[Identifier]] is a String in the spec, it's OK to implement the slot as an enumeration or index because the list of strings is static and short.
_A first, bad attempt at this PR was at #2578 but I got that PR into an un-reopenable state so created a new one here._
> Editorial: Clarify that Temporal.TimeZone slots are mutually exclusive

- polyfill/lib/ecmascript.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
As per ietf-wg-sedate/draft-ietf-sedate-datetime-extended#38, there's been a change to the IXDTF draft precipitated by IETF review and adopted in the IETF 116 meeting, which affects how we handle an ISO string with multiple calendar annotations. For example,
2023-04-13[u-ca=iso8601][u-ca=gregory]
This is unchanged: we continue to use the first annotation and disregard any subsequent ones.
What changes is that if there are multiple annotations, we must throw if any of them have the critical flag. These are both rejected:
2022-07-08T00:14:07Z[!u-ca=chinese][u-ca=japanese]
2022-07-08T00:14:07Z[u-ca=chinese][!u-ca=japanese]
Previously, both of these would parse successfully, and disregard the Japanese calendar annotation.
While we are touching multiple calendar annotations anyway, implement …
> Normative: Implement IETF change regarding multiple calendar annotations

- polyfill/lib/ecmascript.mjs
- polyfill/lib/timezone.mjs
- polyfill/test/validStrings.mjs
Refactors a few places in the polyfill to more closely match the spec. These changes will be helpful for testing of later normative PRs and proposals.
* Case-insensitive caching of DTF instances
* Add CanonicalizeTimeZoneOffsetString AO
* Refactor ParseTemporalTimeZone
* Move offset canonicalization out of GetCanonicalTimeZoneIdentifier
* Move string coercion earlier before IsTimeZoneOffsetString and ParseTimeZoneOffsetString
* Rename `ianaName` parse field to `tzName` because offset strings can also live in this field.
* Refactor TimeZone constructor
> Polyfill: align time zone identifier handling with spec

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/instant.html
- spec/intl.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Introduces SnapshotOwnProperties to precede CopyDataProperties with creating the target object and follow it with returning that object, collapsing many common algorithm subsequences (including all of those using the CopyOptions operation, which is fully subsumed).
Once introduced to ECMA-262, it can also simplify [RestDestructuringAssignmentEvaluation](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-runtime-semantics-restdestructuringassignmentevaluation) and [RestBindingInitialization](https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-destructuring-binding-patterns-runtime-semantics-restbindinginitialization):
```patch
-          1. Let _restObj_ be OrdinaryObjectCreate(%Object.prototype%).
-          1. Perform ? …
```
> Editorial: Simplify object snapshotting 

- docs/zoneddatetime.md
The ZonedDateTime docs still included text about accepting `timeZone` in `with`. This is no longer supported. While I was in the neighborhood I clarified a few other things.
> Fix and clarify ZDT docs

- spec/timezone.html
Corrects minor issues found when creating https://github.com/tc39/ecma402/pull/788 .
> Editorial: Fix up minor issues in FormatTimeZoneOffsetString

- polyfill/ci_codecov_test262.sh
- polyfill/package.json
- polyfill/runtest262.mjs
A previous commit extended the timeout for running Test262 tests because a few of our tests now take as long as 10-20 seconds to run. However, this change clobbered any TIMEOUT values that developers add when running `npm run test262`. 
Instead, the right place to extend the timeout is in `runTest262.mjs`, so that developers can revise the TIMEOUT environment variable on the command line, for example:
```sh
TIMEOUT=3600000 npm run test262
```
This is important when running Test262 under a debugger where timeouts need to be much longer than 30 seconds.
> Fix Test262 timeout for debugging

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/intl.html
- spec/mainadditions.html
Other call sites always provide an Object, so this isolates the inconsistency.
> Editorial: Move ToObject from SnapshotOwnProperties to Calendar.p.mergeFields

- spec/mainadditions.html
- spec/temporal.html
As suggested at https://github.com/tc39/proposal-temporal/pull/2573#discussion_r1225751385 .
> Editorial: Introduce SystemUTCEpochMilliseconds to confine GetGlobalObject()

- polyfill/runtest262.mjs
I've seen occasional Test262 failures at 30 seconds (perhaps related to GitHub capacity limitations?) so let's bump to 60s.
Note that it doesn't happen every time, so I don't think the problem is our code.
> Extend long-test timeout to 60s

- spec/abstractops.html
|TZLeadingChar| is an ASCII letter, full stop, or underscore, and |TZChar| should extend that to include hyphen-minus but #2600 accidentally preserved `_` rather than `-` in productions of the latter.
> Fix accidental grammar change

- spec/abstractops.html
I think I finally found a way to clean up the complexity of [|TimeZoneIANAName|](https://tc39.es/proposal-temporal/#prod-TimeZoneIANAName) needing to support ASCII-case-insensitive matches of legacy time zone names. This PR introduces an IsLegacyIANATimeZoneName syntax-directed operation that checks against both the static list and the Etc/GMT±\<UnpaddedHour> pattern, and also provides an explanatory note.
> Editorial: Introduce an SDO for checking legacy time zone names

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- polyfill/lib/calendar.mjs
This PR adds support for running tests in Node 20 and adds a workaround for an [ICU 73.1 regression](https://unicode-org.atlassian.net/browse/ICU-22412) in the iso8601 calendar that breaks some tests in Node 20.
The fix was to stop using Intl.DateTimeFormat for Gregorian-based calendars like `roc` and `japanese`. As a side effect, a few tests that previously failed now work correctly, and tests run a little faster. 
This PR depends on https://github.com/tc39/test262/pull/3848, so don't please don't merge this PR until I have a chance to rebase this PR's submodule to the latest test262 after the test262 PR is merged.
> Polyfill: Support Node 20 and work around ICU 73.1 bug

- package-lock.json
- package.json
- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/regex.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/instant.html
- spec/intl.html
- spec/mainadditions.html
- spec/timezone.html
- spec/zoneddatetime.html
This PR refactors spec text and polyfill code for time zone offsets, splitting the handling of offsets used as time zone identifiers from offsets used  for ZDT's `offset` property (both parsing and output), and for parsing of Instant and the RFC3339 portion of ZDT strings.
This split will prepare for the normative changes in #2607 and will make the normative PR easier to review. 
Here's more details about what's in this PR: 
* Moves offset string grammar into abstractops.html, remove it from mainadditions.html
* Splits the `|UTCOffset|` production into `|UTCOffsetMinutePrecision|` and `|UTCOffsetSubMinutePrecision|`. 
* Replaces the pattern of calling `IsTimeZoneOffsetString`, throwing if it's `false`, and then calling `ParseTimeZoneOffsetString`. Instead, offset-parsing AOs (like other …
> Editorial: refactor time zone offset handling (prepare for #2607)

- .editorconfig
- .eslintrc.yml
- package.json
This PR updates ESLint config to use double-quotes in Test262 tests, unlike polyfill code that uses single quotes. This configuration is helpful if you're using VS Code's auto-format feature so it won't make unexpected quoting updates to Test262 tests.
> chore: Override ESLint quote config for Test262

- docs/README.md
It was referencing `timeZone` and not `timeZoneId`. When using the Documentation Playground, this readme is the page that loads first. It may be confusing to have an incorrect function name as one of the first things people might try in the Developer Console.
> Typo in README's reference to `Temporal.Instant.timeZoneId()` function

- spec/abstractops.html
- spec/intl.html
Better aligns with ECMA-262: https://github.com/tc39/ecma262/pull/3122
> Editorial: Prefer returning static values after alias comparison

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- spec/abstractops.html
- spec/mainadditions.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
Addresses #2532.
In some cases, duplicate property names are possible in PrepareTemporalFields(). Remove duplicates there, which removes the need for MergeLists(), which is replaced by a list-concatenation in the two places where it was used.
Updates PrepareTemporalFields() to remove duplicates, and {PlainYearMonth,PlainMonthDay}.prototype.toPlainDate() to use list-concatenation instead of MergeLists().
Removes MergeLists() as it's not used any more.
Updates polyfill to match the changes.
> Normative: Remove duplicates in PrepareTemporalFields

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaintime.mjs
- spec/abstractops.html
- spec/duration.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
This editorial PR removes redundant spec text dealing with time formatting:
* Adds a new AO FormatTimeString, and calls it in TemporalTimeToString, TemporalDateTimeToString, and TimeString (the legacy date AO in 262).
* Removes FormatSecondsStringPart and replaces it with a new AO FormatFractionalSeconds, and call it in FormatTimeString and TemporalDurationToString. The text of this new AO is aligned with similar text in GetOffsetStringFor in #2607.
* Replaces sub-second formatting text in TemporalDurationToString with a call to FormatFractionalSeconds.
* Aligns polyfill code to these spec changes.
Note that this PR doesn't touch spec text for formatting time zone offsets because there are several in-flight PRs dealing with offsets and I wanted to keep this PR merge-conflict-free. But …
> Editorial: DRY refactor of time formatting 

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/timezone.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
This normative PR removes string coercion that is currently used in Temporal methods where inputs are expected to be strings. This change is an implementer-recommended fix to the problem that numbers can sometimes be coerced into syntactically valid Temporal string inputs, especially dates and time zone offsets.
Although coercing numbers to strings sometimes works, this behavior is brittle and unpredictable. For example, `-1000` is a valid time zone offset when coerced to a string, but neither `1000` nor `-900` can be coerced into valid offsets. 
Calendars are also affected because while a number cannot be a calendar identifier, an ISO string can be passed in place of a calendar ID. This means that a number like 20200101 (if coerced to a string) is a valid ISO string representing the date …
> Normative: don't coerce non-string primitives to strings, esp. time zones, offsets, and calendars

- polyfill/lib/ecmascript.mjs
- polyfill/lib/timezone.mjs
- spec/abstractops.html
- spec/intl.html
- spec/mainadditions.html
- spec/timezone.html
_This PR is stacked on #2607. Please review only the last commit. At @ptomato's request, I'm splitting it into a separate editorial PR to simplify review of the other normative PR.  It's marked as a draft until #2607 is approved at the upcoming TC39 meeting._ 
Now that #2607 limits TimeZone's [[OffsetNanoseconds]] internal slot to minute precision, this PR refactors TimeZone to clarify that only minutes are allowed in that slot and related abstract operations. 
Changes:
* Renames TimeZone's [[OffsetNanoseconds]] internal slot to [[OffsetMinutes]]
* Changes ParseTimeZoneIdentifier to return an [[OffsetMinutes]] field instead of an [[OffsetNanoseconds]] field.
* Changes FormatOffsetTimeZoneIdentifier to expect its argument to be an integer number of minutes, not an integer number of …
> Editorial: refactor TimeZone [[OffsetNanoseconds]] internal slot to [[OffsetMinutes]]

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/timezone.html
Simplify offset formatting by using FormatTimeString instead of bespoke formatting logic for offsets. This commit completes the time-formatting refactor that #2629 started, and that I promised @gibson042 that I'd complete after #2574 and #2607 were merged.
This PR is stacked on #2622, so please review only the top commit.
> Editorial: Refactor offset string formatting

- docs/ambiguity.md
- docs/strings.md
- docs/timezone.md
- docs/zoneddatetime.md
- polyfill/index.d.ts
- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/intl.html
- spec/timezone.html
https://github.com/tc39/proposal-canonical-tz reached Stage 3 at the July 2023 TC39 meeting. At that meeting, the committee decided that proposal-canonical-tz, instead of continuing as a standalone proposal, should be merged into Temporal Stage 3.
This PR does this merging!  🚀🚀🚀
Tests are at https://github.com/tc39/test262/pull/3837.
cc @gibson042
> Normative: Merge proposal-canonical-tz Stage 3 into Temporal

- docs/cookbook/meetingPlanner.js
- docs/cookbook/storageTank.js
These examples are tiny web apps and don't have any assertions in them, so they are not run by test-cookbook. That's the reason nobody caught this earlier.
> Fix cookbook examples

- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- polyfill/test/validStrings.mjs
To make it easier to find Test262 gaps, this PR removes unreachable code in ISO parsing in the polyfill that codecov complained about. 
It also removes offset normalization code from ParseISODateTime, to better mach the spec that only normalizes downstream from ISO string parsing. Doing this exposed a test bug that's fixed in the second commit of https://github.com/tc39/test262/pull/3877. For good measure, this PR pulls in the entirety of https://github.com/tc39/test262/pull/3877.
Note that this PR shouldn't be merged until the corresponding Test262 PR is merged.
> Polyfill: fix codecov/Test262 issues in ISO parser & align it closer to spec

- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/plaindatetime.html
- spec/plaintime.html
- spec/timezone.html
- spec/zoneddatetime.html
I know we just inlined FormatTimeZoneOffsetString into GetOffsetStringFor, but due to rebasing #2519 I'm having to un-inline it — it'll be used in more than one place when we pre-calculate the UTC offset nanoseconds in cases where it was calculated twice.
Also includes some commits adding more structured headers that I had queued up but never submitted.
> Editorial: Structured headers, AO for formatting UTC offset with nanoseconds

- spec/duration.html
4edfed17fbfd1af52ffcb729a7267428a382bda8 can be seen as either normative or editorial. For actual implementations it's definitely just an editorial change.
> Mark BalancePossiblyInfiniteTimeDuration and CreateTimeDurationRecord as infallible

- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/instant.html
- spec/mainadditions.html
- spec/timezone.html
- spec/zoneddatetime.html
When directly calling `ParseTimeZoneIdentifier` in `ParseTemporalTimeZoneString`, the time zone parsing in `ToTemporalTimeZoneSlotValue` can be simplified.
Also fixes #2639.
And fixes an incorrect `? ParseTimeZoneIdentifier` call in `ToTemporalTimeZoneSlotValue`, which is actually infallible and therefore should have been `! ParseTimeZoneIdentifier`.
And fixes an incorrect `offsetParseResult.[[OffsetMinutes]]` access in `ToTemporalTimeZoneSlotValue`, which should have been `offsetParseResult.[[OffsetNanoseconds]] / (60 * 10^9)`.
> Editorial: Simpler time zone parsing in ToTemporalTimeZoneSlotValue

- docs/timezone.md
* Adds a new section about time zone identifiers
* Adds new section to explain TZ identifier canonicalization
* Clarifies how identifiers and canonicalization work for custom TZs
* Various minor improvements related to IDs and canonicalization
> Improve time zone identifier docs

- polyfill/lib/ecmascript.mjs
Found by codecov: ParseTemporalInstantString already throws if neither `z` nor `offset` are present, so there's no need to check again after ParseTemporalInstantString returns.
> Polyfill: Remove throw in ParseTemporalInstant

- polyfill/lib/ecmascript.mjs
Align RoundDuration checking of `relativeTo` to an assertion, like in the spec. 
There's no need to throw a TypeError in the (should never happen) case when validating `relativeTo`, because upstream callers guarantee that it is one of `undefined`, a ZDT instance, or a PlainDate instance.
> Polyfill: Change RoundDuration TypeError to an assertion

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/instant.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
#2519 is a large pull request that touches everything, and it's difficult to keep rebasing it while I work on the test coverage. I'd like to split it into parts, instead, and land each part as soon as the test coverage is ready. This first part consists of commits that already have complete test coverage, in tc39/test262#3894.
These commits have already been reviewed in #2519. The only change aside from rebasing them was to address Richard's comment about the order in which ToTemporalOverflow is called in the "Normative: Copy options object..." commits.
> Audit of user code calls, part 1

- polyfill/lib/calendar.mjs
Excludes fixes that are already included in #2500.
> Polyfill: Be more robust against late-run primordial manipulation

- polyfill/lib/regex.mjs
- spec/abstractops.html
- spec/timezone.html
Fixes #2608
https://www.ietf.org/archive/id/draft-ietf-sedate-datetime-extended-09.html#name-abnf
Note that _semantic_ constraints remain unchanged; a syntactically valid but unknown time zone like "Etc/GMT-23" or "Foo/Bar+1" is still rejected.
> Editorial: Align time zone name syntax with IXDTF

- spec/abstractops.html
They differ only by optionality of |TimeZoneAnnotation|, so ParseISODateTime was specifying unnecessary work.
> Editorial: Merge Temporal{Zoned,}DateTimeString nonterminals

- spec/duration.html
> Don't look for slots on maybe-undefined relativeTo

- spec/calendar.html
- spec/instant.html
- spec/plainmonthday.html
- spec/timezone.html
- spec/zoneddatetime.html
The term already links to a precise definition in ECMA-262: https://tc39.es/ecma262/multipage/numbers-and-dates.html#epoch
> Editorial: Remove qualifiers before "epoch"

- polyfill/lib/ecmascript.mjs
GetNamedTimeZonePreviousTransition currently has an optimization to avoid fruitlessly searching for a transition in far-future years in time zones that don't have any transitions. This optimization ignores cases where a time zone's offset changes are scheduled more than one year in advance.  This PR extends the lookahead period to three years.
Similarly, GetNamedTimeZoneNextTransition has an optimization where it assumes that no time zone has any transitions more than one year in the future, which IMO is a pretty bad bug because all dates in 2025+ report no transitions in any time zone. This PR extends this lookahead to three years later than either the current date or the input instant, whichever is later. This ensures that, for time zones that currently use recurring DST rules, a next …
> Polyfill: Extend transition-finding lookahead

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/test/validStrings.mjs
Fixes small compliance issues in the reference code, that I came across while doing other things. Also removes unnecessary code from the parser tests.
> Various fixes in the reference code

- docs/plaindatetime.md
- polyfill/lib/ecmascript.mjs
- polyfill/lib/timezone.mjs
- spec/abstractops.html
- spec/instant.html
- spec/mainadditions.html
- spec/timezone.html
- spec/zoneddatetime.html
This PR refactors several operations related to range validation of Temporal.PlainDateTime and Temporal.Instant.
commit 1: remove the `!` from existing calls to IsValidEpochNanoseconds which is infallible. 
commit 2:
* Makes polyfill GetUTCEpochNanoseconds infallible, like in the spec, using @ptomato's `year % 400` trick to avoid overflows.
* Simplifies the polyfill's GetNamedTimeZoneOffsetNanoseconds by using the now-infallible GetUTCEpochNanoseconds.
* Adds optional `_offsetNanoseconds_` parameter to GetUTCEpochNanoseconds, and uses it in call sites of GetUTCEpochNanoseconds where an offset was previously applied to its result.
* Simplifies the polyfill's GetNamedTimeZoneOffsetNanoseconds by using the now-infallible GetUTCEpochNanoseconds.
* Simplifies the polyfill's PlainDateTime range …
> Editorial: Simplify date/time range validation

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
We've received enough user confusion about `valueOf` throwing (see #1681 for why we throw) that I think it's worth clarifying the error message.
> Polyfill: clarify error message about why `valueOf` throws

- polyfill/lib/calendar.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/intrinsicclass.mjs
- polyfill/lib/timezone.mjs
- spec/calendar.html
- spec/plainyearmonth.html
Fixes for various minor issues encountered while rebasing and writing tests for #2519. More info in each commit message. Best reviewed commit by commit.
> Editorial: Various fixes

- polyfill/lib/calendar.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/ecmascript.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
Following on from #2645: #2519 is a large pull request that touches everything, and it's difficult to keep rebasing it while I work on the test coverage. I'd like to split it into parts, instead, and land each part as soon as the test coverage is ready. This is the second part, which consists of various removals of redundant observable operations. This now has test coverage in tc39/test262#3897.
These commits have already been reviewed in #2519. The changes consist only of rebasing.
Closes: #2247 
Closes: #2529
> Audit of user code calls, part 2

- docs/timezone.md
Fixes #2673 to clarify that sub-minute time zone offsets will be output by `Temporal.TimeZone.prototype.getOffsetStringFor` when the offset isn't aligned on a minute boundary.
Note that sub-minute offsets are only allowed for IANA and custom zones, and are disallowed for offset time zones per #2607.
> Fix getOffsetStringFor docs for sub-minute offsets

- polyfill/lib/zoneddatetime.mjs
This has been a bug in the polyfill since ZonedDateTime was originally introduced! The spec says to convert the ZonedDateTime to PlainDateTime once here, whereas the polyfill would Get each property in turn.
Tests will follow as part of #2519.
> Polyfill: Align ZonedDateTime.p.toPlain{YearMonth,MonthDay} with spec

- spec/duration.html
These are pulled out of #2612 to make the normative diff smaller.
> Editorial: Tweaks to UnbalanceDateDurationRelative

- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
Many thanks to @anba for catching these.
Closes: #2683
Closes: #2684
Closes: #2686
Closes: #2687
> Editorial improvements

- polyfill/lib/ecmascript.mjs
Continue where #2667 left off by further clarifying this error message and fixing a mistake where `+foo` was treated as a string coercion, not the number coercion that it is.
> Polyfill: Refine valueOf exception message (again)

- polyfill/lib/ecmascript.mjs
The [current spec](https://github.com/tc39/proposal-temporal/blob/3f82e8d48d3c062d07a4ae77dc175d65cc3be8ae/spec/duration.html#L1365-L1367) for `BalancePossiblyInfinteTimeDurationRelative` includes early-returning the overflow values, but this is not present in the polyfill code.
This seems to have been introduced in 0547d29dbdf4c5aa9c2dca3c6072513dc52abe36.
> Fix handling of overflow returns to BalancePossiblyInfiniteDurationRelative

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/intl.html
- spec/plainmonthday.html
This PR removes some dead steps from PlainMonthDay-related spec algorithms to hopefully clarify that year is optional only for the ISO 8601 calendar—and that in that calendar it is **always** optional (regardless of entry point or presence vs. absence of `month` and/or `monthCode`)—and then updates the polyfill accordingly, fixing a gap from #2500 that supported `Temporal.PlainMonthDay.from({ monthCode, day })` and `Temporal.PlainMonthDay.from({ month, day })` but not `Temporal.PlainMonthDay.from({ month, day, calendar: "iso8601" })` or `Temporal.Calendar.from("iso8601").monthDayFromFields({ month, day })`).
Note that polyfilled _non_–ISO-8601 calendars, including "gregory", continue to reject input that fails to include at least one of `year` and `monthCode`.
Related test262 PR: …
> Polyfill: Update per #2500

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/methodrecord.mjs
- polyfill/lib/now.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
This is an audit of the whole proposal for opportunities where we can reduce the number of calls we make into user code.
Very large, recommend reviewing commit by commit.
> Normative: Audit of user-visible operations in Temporal

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/methodrecord.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/timezone.mjs
- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
This addresses Richard's comments on #2519.
Tests are in https://github.com/tc39/test262/pull/3959
Closes: #2724
> Remove conditional lookups

- spec/temporal.html
`Temporal.Calendar` and `Temporal.ZonedDateTime` are missing from the `Temporal` object's property
> Editorial: Add missing constructor properties of the Temporal object

- spec/abstractops.html
- spec/instant.html
- spec/intl.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
ECMAScript spec uses "Abstract Operations" and "Abstract Operations for Something" as the capitalization in the heading.
> Editorial: Use consistent capitalization for Abstract Operations

- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
ECMAScript sepc uses "... is the String value ..."
> Editorial: Use upper case for "String" value

- README.md
I've renamed my `fullcalendar/temporal` repo to `fullcalendar/temporal-polyfill`. It used to contain a grab-bag of Temporal-adjacent utilities but now its just the polyfill, so it's a better name.
I've also upgraded the release type to 'beta'.
Thank you so much for your work on this proposal!
> Update README.md for new temporal-polyfill repo link, beta

- polyfill/lib/calendar.mjs
Fixes #2740. There were two separate problems with the islamic calendar implementation in the Temporal polyfill, both fixed in this PR:
* Previous implementation assumed that when the 12th month had 30 days, then it was a leap year. But the `islamic-umalqura` calendar appears to break this rule. New implementation calculates the number of days in the year; if 355 then it's a leap year.
* Previous implementation had a bug where it was using ISO date instead of calendar date when calculating `daysInYear`.
> Polyfill: Fix daysInYear and inLeapYear in Islamic calendars

- docs/cookbook/roundToNearestMonth.mjs
Fixes #2751 
In addition to removing the use of hardcoded 12, I found that using Duration to find the closest option was more readable than the day of month arithmetic.
> Improve roundToNearestMonth example

- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainmonthday.md
- docs/plaintime.md
- docs/timezone.md
- docs/zoneddatetime.md
I update document about no-separator input samples of each from-function for this issue: https://github.com/js-temporal/temporal-polyfill/issues/273
The document explains it follows ISO 8601 but the specification explained the format more strictly.
(I'm not good at English so I may overlook in the document, sorry.)
Therefore I added sample codes to show no separator is in specification.
If there's no explains really, I may be able to add short grammar explaining page into `Other documentation` list.
> Editorial: Add no separator text input samples

- docs/buildDocs.js
- package-lock.json
- package.json
- spec/abstractops.html
- spec/biblio.json
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
- Update all developer dependencies to their latest versions (including major updates).
- Update files to conform to the new versions and fix some issues:
- Enum values should be lowercase and kebab-case.
- Avoid declaring variables that are already declared, either set their value or rename them accordingly.
- Avoid using abrupt shorthands on abstract or syntax-directed operations that do not return a Completion Record.
- Avoid calling abstract functions in algorithms that don't have a definition.
- Update section names to their new ones.
- Fix a small formatting issue.
> Editorial: update deps and fix issues

- polyfill/lib/ecmascript.mjs
- spec/plaindate.html
The DifferenceISODate AO was a port from optimized JS to spec language, but was difficult to understand. Replace it with an algorithm that is written in an easier to understand way, but produces identical results (verified by testing a 1:1 implementation of the old and new algorithms on every possible pair of dates in a 4-year period.)
The reference code is also changed to match the AO more closely and be easier to understand, although some optimizations are made.
(This is the editorial part of #2759.)
> Editorial: Rewrite DifferenceISODate as a clearer algorithm

- polyfill/lib/calendar.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/math.mjs
- polyfill/lib/timeduration.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/all.mjs
- polyfill/test/math.mjs
- polyfill/test/timeduration.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
~~(Note: stacked on top of #2722, will rebase as appropriate)~~
This includes everything from #2612 except the last commit, which I'm still checking for a potential bug. These are the changes that place the limits on each component of a Temporal.Duration, and implement the internal calculations in a "normalized form" - 32-bit years, months, weeks, and time units expressed as one <96-bit integer.
> Duration normalization, part 2 of 3

- package-lock.json
- package.json
- spec/abstractops.html
- spec/calendar.html
- spec/intl.html
- spec/timezone.html
https://github.com/tc39/ecma262/pull/3268 added a new AO which lets us simplify use of the iteration protocol.
I didn't update the polyfill, sorry.
> Editorial: use new IteratorStepValue AO

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/duration.html
Refactor for legibility - https://github.com/tc39/proposal-temporal/issues/2692
Two errors that were triggering on test were present in branch previously
co-authored by El Linzer elinzer5@gmail.com
> Duration iscalendarunit

- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/mainadditions.html
Now that biblio.json contents are propagated to grammarkdown, these duplicated parts of the ISO 8601 grammar can be removed.
> Editorial: Remove duplicated grammar definitions

- polyfill/lib/ecmascript.mjs
- spec/timezone.html
- spec/zoneddatetime.html
~~This is the integer math refactor that I have mentioned in the last couple of Temporal presentations.~~
~~It is stacked on top of #2519 and #2609; only the last 7 commits belong to this change. The GitHub UI doesn't let me show a comparison with `HEAD~7` but here is a view that includes the editorial commits from #2609 but without the large PR #2519: https://github.com/tc39/proposal-temporal/compare/user-code-calls...duration-normalize-96?expand=1~~
~~Best reviewed commit by commit. There is more information in each individual commit message.~~
~~Test262 tests are in https://github.com/ptomato/test262/commits/duration-normalize but I still need to review them for complete coverage.~~
~~See: #2195, #1700.~~
This is now part 3 of 3 of this change.
Part 1: #2722
Part 2: #2727
> Normative: Limit Duration units to prevent arbitrary-precision integer arithmetic, and prevent loops

- polyfill/lib/ecmascript.mjs
- spec/plaindate.html
This adjusts the difference algorithm for Gregorian-year dates so that when an intermediate date occurs past the end of a month, it is not shifted to the end of that month.
Previously, in some edge cases where taking the difference in months or years would return a number of months and zero days, we now return one month less and 28, 29, or 30 days instead.
Example: 1970-01-29 until 1971-02-28, largestUnit years
Old result: 1 year, 1 month
New result: 1 year, 30 days
Note that largestUnit weeks and largestUnit days, the latter of which is the default, are not affected.
~~(**Note:** Stacked on top of an editorial change which I will eventually make a separate PR for.)~~
Closes: #2535
> Normative: Fix date difference for end-of-month edge cases

- spec/calendar.html
%Temporal.TimeZone.prototype.dateFromFields%, etc., don't exist. These are copy-paste errors and should say %Temporal.Calendar.prototype.dateFromFields%, etc.
Thanks to Shannon Booth for catching this.
Closes: #2772
> Editorial: Fix copy-paste errors in Calendar Methods Record ops

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/intl.html
- spec/mainadditions.html
Make `CalendarDateWeekOfYear` return undefined for all calendars without well-defined week calendar system
Fixes: #2744
> Normative: Make CalendarDateWeekOfYear return undefined 

- polyfill/lib/ecmascript.mjs
Found by @12wrigja here: https://github.com/js-temporal/temporal-polyfill/pull/275#discussion_r1507142623
> Polyfill: Convert unnecessary let => const

- polyfill/index.d.ts
Found by @12wrigja in https://github.com/js-temporal/temporal-polyfill/pull/280. Porting it upstream.
> Polyfill: Fix typo in JSDoc comments of TS typings

- spec/intl.html
- spec/mainadditions.html
- spec/timezone.html
Adds notes in the appropriate places to prohibit cases such as time zones becoming unsupported after they had previously been observed to be supported, or becoming primary after they had previously been observed to be primary.
Co-Authored-By: Richard Gibson
Closes: #1921
> Editorial: Clarify consistency requirements for supported time zones

- polyfill/lib/ecmascript.mjs
- spec/zoneddatetime.html
This PR supersedes #2760
@ptomato
Test262 branch with updated tests:
https://github.com/fullcalendar/test262/tree/temporal-2760
Diff from main: https://github.com/tc39/test262/compare/main...fullcalendar:test262:temporal-2760
Diff from previous: https://github.com/ptomato/test262/compare/temporal-2760...fullcalendar:test262:temporal-2760
I have not updated the spec text. I'd really appreciate some help with that.
Plz lmk if questions. Thanks!
> Normative: [Alt PR] Fix intermediate value in ZonedDateTime difference

- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- spec/plainmonthday.html
- spec/plainyearmonth.html
This is to address belated feedback from Anba on #2718. The options object previously created here is unnecessary, because 'constrain' is always the default for this option. Not creating the options object here is consistent with the rest of the spec text.
Closes: #2803
> Post-adjustment: Remove unnecessary object creation

- docs/calendar.md
- polyfill/ci_codecov_test262.sh
- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/test/expected-failures.txt
- spec/calendar.html
> Editorial: Close more old non-normative issues

- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
This is my proposed fix to #2790
Adjusted tests:
https://github.com/tc39/test262/compare/main...fullcalendar:test262:temporal-2790-round-zdt-day
Could someone please review?
> Normative: Fix ZonedDateTime::round incorrect results with smallestUnit:day

- polyfill/index.d.ts
This PR reflects a recent normative change on `weekOfYear` / `yearOfWeek` (#2756) in type definition.
> Polyfill: Update d.ts

- polyfill/lib/ecmascript.mjs
- polyfill/test/expected-failures.txt
- spec/abstractops.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
Put duration units in a table, and use that table to make operations easier to follow.
Address a couple of other minor editorial issues.
> Editorial: More minor improvements

- polyfill/lib/ecmascript.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/calendar.html
Closes: #2655
Closes: #2831
cc @anba
> Editorial: Another batch of minor editorial improvements

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/timeduration.mjs
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
When the time portion of a duration, rounded relative to a ZonedDateTime, would land on a non-24-hour day, we'd get incorrect results. This is a regression from #2508 where although switching the order of BalanceDateDurationRelative and BalanceTimeDurationRelative was correct, we should not have removed the MoveRelativeZonedDateTime call.
Closes: #2742
> Normative: Fix Duration rounding relative to ZonedDateTime

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
- After #2758, there is only one remaining caller of AddDuration. Inlining it into its caller makes it easier to implement / understand.
- Closes #2785 by making BalanceTimeDuration return a completion record, as @anba pointed out there are circumstances in which it can fail.
- Fix broken ESIDs
- Comparing numbers uses =, not "is"
> Editorial: Next batch of minor editorial improvements

- polyfill/lib/calendar.mjs
Chrome for Android as of v 142.0.6367.179 mishandled the era option in Intl.DateTimeFormat and was returning 'bc' instead of 'ah'.
Fix: js-temporal/temporal-polyfill#284
> polyfill: fix: patching era for Hijri dates

- spec/abstractops.html
- spec/duration.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
This makes it easier to validate the math in NudgeToCalendarUnit when calling ApplyUnsignedRoundingMode. It also matches other operations which already require that `increment` is a positive integer.
(Cherry-picked from #2884.)
> Editorial: Consistently mark increment as "positive integer"

- docs/plaindate.md
day is not a subfield of monthCode
> Fix the doc markup for PlainDate properties

- polyfill/lib/ecmascript.mjs
- spec/plaindatetime.html
Fix for https://github.com/tc39/proposal-temporal/issues/2820
Fix bug where PlainDateTime since/until would maintain date/time-diff sign compatibility by backing-off from wrong end and erroneously falling across month boundaries
Tests: https://github.com/tc39/test262/pull/4078/files
> Normative: Fix bug with PlainDateTime since/until near month boundaries

- docs/duration.md
- polyfill/index.d.ts
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/duration.html
This is part of the ongoing effort, at implementations' request, to reduce the code size and complexity of the proposal.
Removes the options parameter from Temporal.Duration.prototype.add and Temporal.Duration.prototype.subtract. Everything else remains the same: Additions and subtractions that previously succeeded without relativeTo, still succeed, with the same results. Additions and subtractions that previously threw if there was no relativeTo, now just throw unconditionally.
Closes: #2825
> Normative: Remove relativeTo option from Duration.p.add/subtract

- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/intl.html
- spec/mainadditions.html
In the ISO 8601 grammar, we can use early errors and parameterization to avoid such bizarre productions like TimeHourNotThirtyOneDayMonth and TimeSpecWithOptionalOffsetNotAmbiguous, etc.
Best reviewed commit by commit.
Closes: #1984
> Editorial: Use early errors and parameterization to simplify ISO 8601 grammar

- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/mainadditions.html
- spec/timezone.html
Prefer language like "the first |TemporalDecimalFraction|, if present" rather than defining several nonterminals such as |TimeFraction|, |DurationHoursFraction|, etc.
Closes: #2006
> Editorial: Collapse nonterminals only used for disambiguation

- docs/README.md
- docs/ambiguity.md
- docs/cookbook/getTimeStamp.mjs
- docs/cookbook/makeExpandedTemporal.mjs
- docs/instant.md
- docs/ja/ambiguity.md
- docs/now.md
- docs/plaindatetime.md
- docs/plaintime.md
- docs/timezone.md
- docs/zoneddatetime.md
- polyfill/index.d.ts
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/now.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/calendar.html
- spec/instant.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/temporal.html
- spec/zoneddatetime.html
Here is an implementation of part of the slate of API removals that reached consensus in the TC39 meeting of 2024-06-12. This consists of all removals except for calendars and time zones and things related to them such as getISOFields, which will follow in a later PR.
This PR contains documentation updates, removals from the spec text, removals from the reference code, removals from the suggested TypeScript definitions, and adjustments of the cookbook examples.
Here is what's removed exactly:
- Temporal.PlainDateTime.p.withPlainDate
- Temporal.ZonedDateTime.p.withPlainDate
- Temporal.PlainTime.p.toPlainDateTime
- Temporal.PlainTime.p.toZonedDateTime
- Temporal.Instant.fromEpochSeconds
- Temporal.Instant.fromEpochMicroseconds
- Temporal.Instant.p.epochSeconds
- …
> Normative: Partial stack of removals

- docs/ambiguity.md
- docs/instant.md
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Here's a batch of editorial fixes, including some docs improvements from Richard that I extracted out of another PR, and some of the newer editorial issues opened by Anba.
Best reviewed commit by commit.
Closes: #2871, #2872, #2874, #2875, #2879, #2887
> Editorial: Batch of editorial improvements

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/duration.html
Changes:
- I've inserted `abs` for all arguments passed to `ApplyUnsignedRoundingMode` to ensure the `r1 ≤ x < r2` requirement in `ApplyUnsignedRoundingMode` is fulfilled. 
- Furthermore `startEpochNs` and `endEpochNs` are now required to be correctly ordered. This ensures that `progress` is a proper fraction. (If it's not a proper fraction, then `abs(total)` can be larger than `abs(r2)`, which is invalid for `ApplyUnsignedRoundingMode`.)
- Also fixes #2893 by comparing `roundedUnit` against `abs(r2)`.
> Editorial: Add missing checks before calling ApplyUnsignedRoundingMode

- polyfill/lib/ecmascript.mjs
- spec/duration.html
Replacing AddDateTime with AddDate makes it easier (for implementers) to see why it's okay to skip all time duration normalization steps.
e283b594f199f06e210bd80b9216c9668d4d6030:
- Avoid creating a normalized duration record whose time component is always zero.
9e220c77f52beda604d3402607a2ccd12466ade8:
- Read time components directly from input date-time.
0739c719946f22d95e411d2285448ac697ac01e1:
- And finally replace AddDateTime with AddDate in NudgeToCalendarUnit.
aee35382c4d64dbeb31c31d7224100e2c944ee47:
- Same changes as the first three commits, but this time for NudgeToZonedTime.
5776d1a33ae7f56a5f40ec5f9d94c905521c4df4:
- Same changes as the first three commits, but this time for BubbleRelativeDuration.
> Editorial: Replace AddDateTime with AddDate 

- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/mainadditions.html
This PR is the Temporal counterpart to https://github.com/tc39/ecma262/pull/3334.
See that PR for details.
> Normative: Revert U+2212 from time zone offset grammar

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- spec/calendar.html
- spec/intl.html
Anba re-synced the spec text with the latest draft of ECMA-402 in #2904. That brought in AvailableCalendars which now needs to move into ECMA-262 as part of Temporal, and also brought in calendar canonicalization which I've implemented support for in the reference code. Also brings in a test262 update with improved coverage for calendar canonicalization.
> Editorial: Followups from re-sync of ECMA-402

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
Best reviewed commit by commit. Explanations in each commit message. Closes several issues opened by @anba.
> Next batch of editorial issues

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/duration.html
- spec/plaintime.html
This is preparation for #2925.
> Editorial: Small batch of editorial issues

- polyfill/lib/duration.mjs
- spec/duration.html
The corner case of rounding to a >1 increment of a calendar smallest unit while simultaneously balancing to a larger calendar unit is ambiguous. This use case was probably never considered.
```js
const d1 = Temporal.Duration.from({months: 9});
d1.round({
relativeTo: '2024-01-01',
largestUnit: 'years',
smallestUnit: 'months',
roundingIncrement: 8,
roundingMode: 'ceil',
});  // => 1 year? 1 year 4 months?
```
This never came up in real-world usage. Disallow it explicitly, to leave space for a future proposal if it ever comes up.
Closes: #2902
> Normative: Disallow rounding to increment while balancing to calendar unit

- docs/plaindate.md
- docs/zoneddatetime.md
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/timezone.html
- spec/zoneddatetime.html
Fixes calculations of start of day in `ZonedDateTime.prototype.hoursInDay`, `ZonedDateTime.prototype.startOfDay()`, and `ZonedDateTime.prototype.round()` with smallestUnit: "day".
Updates the following operations to explicitly mean "start of day" and not
"midnight":
- `PlainDate.prototype.toZonedDateTime(timeZoneString)`
- `PlainDate.prototype.toZonedDateTime(options)` with omitted or undefined `plainTime` option
- `ZonedDateTime.prototype.withPlainTime()` with no argument or undefined
- Parsing `YYYY-MM-DD[Zone]` anywhere a ZonedDateTime string is expected
This is in order to handle one corner case from the TZDB where clocks were set one hour ahead in America/Toronto at 23:30 on March 30, 1919, meaning that the DST skipped hour encompassed midnight but did not start or end at midnight. …
> Normative: Handle "start of day" separately from "midnight"

- docs/cookbook.md
- docs/cookbook/hijriDaysAdjustments.mjs
- docs/hijri-days-adjustments.md
This PR implements the `AdjustableHijriTemporal`  class for customizing Hijri date display.
This class allows for adjustment of Hijri dates by shifting days forward or backward. It's designed to:
- Help users synchronize displayed Hijri dates with their local Hijri calendar.
- Facilitate the use of alternative Hijri calendar epochs.
Key points:
- It adjusts the display of Hijri dates without modifying the underlying calendar system.
- The adjustment is a simple day shift and does not alter month lengths or other calendar rules.
- This approach is useful for visual alignment but does not implement comprehensive calendar customization or detailed Hijri calendar variants.
Notes to maintainers: The implementation uses composition instead of inheritance and I have made it so that one class can …
> Cookbook example showing how to do Hijri days adjustments (without custom calendar)

- polyfill/index.d.ts
* `DateTimeFormatRangePart`: included in standard TypeScript definition as `Intl.DateTimeRangeFormatPart` (https://github.com/microsoft/TypeScript/blob/31afb988d1c6857ce4d1ab3b2558385e68a565a8/src/lib/es2021.intl.d.ts#L14)
* `DateTimeFormatOptions`: all defined options are already included in standard TypeScript definition (https://github.com/microsoft/TypeScript/blob/31afb988d1c6857ce4d1ab3b2558385e68a565a8/src/lib/es2021.intl.d.ts#L6-L12)
These types are supported in official type definition of ES2021, so it's possible to omit from this repository's `d.ts` file.
> Polyfill: Update type definitions of `Intl`

- polyfill/lib/ecmascript.mjs
- spec/zoneddatetime.html
It's possible to avoid the `GetOffsetNanosecondsFor` call. For each candidate instant, you can derive its offset by comparing it to the UTC-zoned year/month/day/etc. Applicable to offset:prefer/reject only.
Modified (and passing) test262:
https://github.com/tc39/test262/compare/main...fullcalendar:test262:temporal-fewer-calls-offset-prefer-reject
> Editorial: Fewer GetOffsetNanosecondsFor calls during InterpretISODateTimeOffset (prefer/reject)

- polyfill/lib/ecmascript.mjs
- spec/plainyearmonth.html
While investigating for #2794 (ultimately unsuccessful), I uncovered a way to have less user-code calls from PlainYearMonth add/subtract.
I don't see it in the [calendar invariants list](https://tc39.es/proposal-temporal/docs/calendar.html#invariants-across-calendars), but this axiom probably goes without saying: *the day before the first day of one month is the last day of the previous month.*
If add/subtract moves backward in time, the algorithm requires us to determine the last day of the current month before proceeding with PlainDate-style add/subtract.
Right now, the last day is being determined, but seems unnecessary to thread it back through `CalendarDateFromFields`, no?
Adjusted tests:
https://github.com/tc39/test262/compare/main...fullcalendar:test262:temporal-fewer-calls-pym-math …
> Fewer CalendarDay/CalendarDateFromFields calls during PlainYearMonth add/subtract

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/duration.html
- spec/instant.html
- spec/zoneddatetime.html
Many operations seem to be simplified by dealing with Duration Records rather than individual fields.
And I suspect that even further reform in this direction remains possible.
> Editorial: Pass Duration Records rather than individual components

- polyfill/lib/calendar.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/intrinsicclass.mjs
- polyfill/lib/legacydate.mjs
- polyfill/lib/math.mjs
- polyfill/lib/now.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/primordials.mjs
- polyfill/lib/regex.mjs
- polyfill/lib/shim.mjs
- polyfill/lib/slots.mjs
- polyfill/lib/timeduration.mjs
- polyfill/lib/zoneddatetime.mjs
While working on #2940, I noticed that the polyfill was vulnerable to post-load manipulation of primordials. This PR addresses every such pattern I could find... the first PR is semi-mechanical replacement of dynamic-lookup method invocations (includes those hidden by iterable spread/destructuring or for..of), the second fully so.
The result is slightly less readable, but hews more closely to the spec and doubles down on the `ES.Call` protections that are already commonplace.
> Polyfill: Be more robust against post-load environment changes

- polyfill/lib/calendar.mjs
The majority do not quote them, so this replaces the exceptions.
> Polyfill: Make field references in error messages more consistent

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Without user-defined calendars and time zones, it's no longer observable when new objects are returned. This helps to simplify the various `from` methods.
Implementations can easily avoid these allocations. (They should probably already doing this when the `ToXXX` operations are called without actually returning the new object to user code.)
> Editorial: Return new objects from ToXXX operations

- polyfill/lib/ecmascript.mjs
- spec/instant.html
- spec/mainadditions.html
- spec/timezone.html
- spec/zoneddatetime.html
`GetUTCEpochNanoseconds` was changed to include a subtraction. There are currently exactly three callers which require this change. All other callers, which are in the majority, don't use this optional offset parameter.
Instead of modifying `GetUTCEpochNanoseconds`, perform this subtraction in the caller. Also change `InterpretISODateTimeOffset` to perform a single call to `GetUTCEpochNanoseconds`.
Also don't bother to µ-optimise `InterpretISODateTimeOffset` to avoid calling `GetUTCEpochNanoseconds` when `possibleEpochNs` is empty. This case happens too rarely to bother optimising it.
> Editorial: Avoid GetUTCEpochNanoseconds modification

- docs/README.md
- docs/cookbook.md
- docs/cookbook/futureDateForm.js
- docs/cookbook/meetingPlanner.js
- docs/cookbook/storageTank.js
- docs/duration.md
- docs/instant.md
- docs/object-model.svg
- docs/persistence-model.svg
- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainmonthday.md
- docs/plaintime.md
- docs/plainyearmonth.md
- docs/zoneddatetime.md
- spec.html
Various improvements to the docs, mostly taken from a sweep of the issue backlog. Also corrected other mistakes I ran into.
> Docs improvements

- spec/abstractops.html
Fixes various issues in GetTemporalUnitValuedOption:
- `allowedStrings` is a list of strings, so it shouldn't be initialised as a copy of `allowedValues`.
- `GetOption` was incorrectly called with `default = UNSET`.
- `default = REQUIRED` can be passed directly to `GetOption`.
- `allowedValues` doesn't contain `UNSET`, so the loop doesn't need to handle that case.
> Editorial: Correct various value types in GetTemporalUnitValuedOption

- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/primordials.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/ecmascript.mjs
There is one test262 test that has annoyed me for over a year because it takes 30 seconds to execute with the reference polyfill: `intl402/Temporal/ZonedDateTime/prototype/getTimeZoneTransition/transition-at-instant-boundaries.js`. I assumed it was slow because we use DateTimeFormat to figure out the UTC offset of a time zone many times in a loop. Finally I decided to profile it. It's true that DateTimeFormat is a significant part of the profile, but there was a lot more unnecessary work being done there.
The key optimization in this PR is that we assume there are no time zone transitions that occur in the middle of a millisecond. This means, we assume the UTC offsets at these two times are always the same:
2024-09-25T16:47.123456789
2024-09-25T16:47.123
This is the case in all modern …
> Optimize the slow test

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/duration.html
- spec/instant.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
In #2758 we kept the code paths for Duration.p.round() and Duration.p.total() the same. However, it is actually simpler to separate them in most places, except for NudgeToCalendarUnit.
- Splits TotalRelativeDuration out of RoundRelativeDuration
- Splits TotalTimeDuration out of RoundTimeDuration
- Splits DifferenceZonedDateTimeWithTotal out of DifferenceZonedDateTimeWithRounding
- Splits DifferencePlainDateTimeWithTotal out of DifferencePlainDateTimeWithRounding
- Removes [[Total]] field from Nudge Result Record
- Changes NudgeToCalendarUnit to return a record of { [[NudgeResult]], [[Total]] }
Closes: #2947
> Editorial: Split total() code path out of RoundRelativeDuration

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
cc @anba 
Closes: #2997, #2999, #3001
> Editorial: More suggestions from Anba

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/instant.html
- spec/timezone.html
- spec/zoneddatetime.html
Follow-ups from PR #3003.
Closes: #3005
> Editorial: Follow up suggestions from Justin

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/math.mjs
- polyfill/lib/timeduration.mjs
- polyfill/test/timeduration.mjs
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
Rename for reasons described in #2953, and change Normalized Time Duration Record to be an integer within a particular range, which allows simplifying several abstract operations as discussed there.
Closes: #2953
> Editorial: Rename "normalize" and "unnormalize" for durations

- polyfill/index.d.ts
related: https://github.com/js-temporal/temporal-polyfill/pull/224 .
According to the spec of Temporal and ECMA-402, first argument of `toLocaleString` methods can be `Intl.Locale` object (or its array). But the type definition in this repository doesn't match to the spec.
The polyfill already accepts `Intl.Locale` object as locale so I think there is no need to modify it. (Perhaps tests should be added, but I'm not sure where and how to add them.)
> Use `Intl.LocalesArgument` in  type definition of `toLocaleString` methods

- docs/cookbook/fromLegacyDate.mjs
- docs/instant.md
- docs/now.md
Found this minor documentation bug, `Temporal.Now.timeZone()` does not exist so it should be `timeZoneId()`.
> Use `Temporal.Now.timeZoneId()` instead of `timeZone()`

- docs/cookbook.md
- docs/duration.md
- docs/instant.md
- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainmonthday.md
- docs/plaintime.md
- docs/plainyearmonth.md
- docs/timezone.md
- docs/zoneddatetime.md
Consistently format string values for options as (for example) `'constrain'`, with single quotation marks inside backticks.
Closes #2988
> Docs: Make code-formatted string values consistent (#2988)

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/duration.html
- spec/instant.html
- spec/plaintime.html
Changes:
- Move handling for `day` units from `RoundTimeDuration` to `Temporal.Duration.prototype.round`.
- Correct argument type for `DifferenceInstant` to only allow time units.
- `RoundTimeDuration` is now only called with time units and its input and output is a time duration.
- Remove the no rounding fast path from `DifferenceTemporalPlainTime` to match `DifferenceInstant`.
Fixes:
`TemporalDurationFromInternal` is fallible in `Temporal.Duration.prototype.toString`:
```js
Temporal.Duration.from({
days: 1,
seconds: 2**53 - 1 - (24*60*60),
nanoseconds: 999_999_999
}).toString({
roundingMode: "ceil",
fractionalSecondDigits: 7
});
```
> Editorial: Change TimeDuration to use time durations instead of internal durations

- docs/zoneddatetime.md
See https://github.com/tc39/proposal-temporal/issues/2938
> Docs: Document hoursInDay and startOfDay when same day starts twice (#2938)

- spec/abstractops.html
This AO doesn't work with strings.
> Editorial: correct description of LargerOfTwoTemporalUnits

- polyfill/lib/legacydate.mjs
- polyfill/test/expected-failures.txt
This PR updates test262 and adds a fix for a newly-added test that the reference code fails.
> Polyfill: Date.prototype.toTemporalInstant should not be a constructor

- docs/cookbook/fromLegacyDate.mjs
- docs/strings.md
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/duration.html
- spec/plaindatetime.html
- spec/zoneddatetime.html
Closes #3016, #3018, #3019, #3020, #3021
> Editorial: Implement next batch of editorial suggestions from Anba

- spec/abstractops.html
It is referred to as `value` in the subsequent description and steps.
> Editorial: Fix IsPartialTemporalObject parameter name

- polyfill/lib/ecmascript.mjs
- polyfill/test/expected-failures.txt
- spec/abstractops.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
This closes several issues spotted by @anba and @trflynn89, and also brings in the latest commits from test262.
> Editorial: Fix next batch of editorial issues

- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/intrinsicclass.mjs
- polyfill/lib/slots.mjs
- spec/intl.html
- spec/plaindatetime.html
- Updates test262 to bring in test coverage for #3015 and ensures assertion is not hit
- Drive-by fix for custom devtools representation of polyfilled Intl.DateTimeFormat
- Reverts unintended observable change affecting `new Date().toLocale{Date,Time,}String()` (see #3049)
- Proofreading/clarity fixes
> Editorial: Next batch of editorial issues

- polyfill/lib/zoneddatetime.mjs
- spec/intl.html
- spec/timezone.html
> Editorial: Next batch of minor editorial issues

- spec/abstractops.html
> Editorial: Simplify ParseTemporalCalendarString

- polyfill/lib/ecmascript.mjs
- spec/plainyearmonth.html
The call to CalendarYearMonthFromFields will already reject too large dates, but adding an explicit step makes it more obvious that ISODateToFields doesn't require support for mapping large ISO dates to calendar dates. And it also aligns ToTemporalYearMonth with ToTemporalMonthDay after #3054.
Taken from @anba's PR #3054, this is the editorial/unobservable part.
> Editorial: Make explicit that ToTemporalYearMonth rejects too-large ISO year strings

- docs/README.md
- docs/head.html.part
A note in the banner and also on the front page.
> docs: Add note about MDN being the main API reference going forward

- polyfill/lib/duration.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/primordials.mjs
- spec.html
- spec/abstractops.html
- spec/biblio.json
- spec/duration.html
- spec/intl.html
- spec/mainadditions.html
Intl.DurationFormat is stage 4, so we can now incorporate the necessary changes to use it in Temporal.Duration.prototype.toLocaleString and to accept Temporal.Duration as an argument to Intl.DurationFormat.prototype.format and formatToParts. Some operations need to move from ECMA-402 into ECMA-262.
Closes: #452
> Integrate Intl.DurationFormat into Temporal

- docs/strings.md
The actual output is: `28 février 22`
This example demonstrates date wrap around the era notation, but doesn't note the era. An alternative example might demonstrate subtraction without passing past 0 CE, but for now let's just fix the typo.
> docs: Update typo of string formatting output

- polyfill/lib/ecmascript.mjs
- polyfill/test/expected-failures.txt
- spec/plainmonthday.html
Follow-up to #3008 / #3002 to reject too large dates.
> Normative: Reject too large dates in ToTemporalMonthDay

- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- spec/mainadditions.html
- Add %Temporal% to list of well-known intrinsics
- ~~Update test262 tests~~
- Fix a few nonconformances in the reference code pointed out by @anba
> Editorial: Small batch of changes

- spec/timezone.html
While strict inequality of `t` and `epochNanoseconds` can be surmised from behavior (without it, `someDateTime.getTimeZoneTransition("previous") == someDateTime.getTimeZoneTransition("previous").getTimeZoneTransition("previous")`), I think this is a little clearer at a quick glance.
> Clarify strict inequality in `getTimeZoneTransition()`

- polyfill/index.d.ts
The `exactOptionalPropertyTypes` option in TypeScript bans passing `undefined` to optional properties unless `undefined` is allowed explicitly, because optional properties and `undefined` properties behave differently in JavaScript, to be precise.
https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes
```typescript
function foo(
dateTime: Temporal.ZonedDateTime,
disambiguation?: "compatible" | "earlier" | "later" | "reject",
) {
dateTime.with({ day: 1 }, { disambiguation });
}
```
For example, above code result in the error below with `exactOptionalPropertyTypes`.
```
Argument of type '{ disambiguation: "reject" | "compatible" | "earlier" | "later" | undefined; }' is not assignable to parameter of type 'Partial<AssignmentOptions & ToInstantOptions & …
```
> polyfill: Update type definition to support `exactOptionalPropertyTypes`

- polyfill/index.d.ts
The options argument of `Duration.toLocaleString` is incorrectly typed as `Intl.DateTimeFormatOptions` which is incorrect. For example this code fails typechecking:
```ts
duration.toLocaleString('en', { style: 'digital' })`
```
TypeScript's lib.d.ts does not yet include type definitions for Intl.DurationFormat, so I've added the relevant options manually. This can be removed once TypeScript has shipped support.
> Polyfill: Fix type definition of Duration.toLocaleString

- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/timeduration.mjs
- Update to latest test262
- A few minor improvements
- Fix bug in calendar code (not corresponding to any spec steps)
> Update to latest test262, minor reference code improvements

- polyfill/lib/ecmascript.mjs
For a few time zones, the two-week search window for an interval to bisect is too large, because transitions occur less than two weeks apart. Special-case these time zones.
This allows increasing the default window to 19 days (a bunch of Argentinian time zones have transitions less than 20 days apart, so this seems like a good boundary where we don't have to add too many special cases.) This gives a small performance improvement in the common case.
Closes: #3110
> Polyfill: Adjust time zone transition search window

- docs/buildDocs.js
Somewhere along the line, the Markdown renderer stopped putting this comment at the beginning of the line.
Closes: #3119
> Fix table of contents in cookbook page

- spec/duration.html
- spec/instant.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
The PlainDate constructor was the only one that already had it written this way, which seems to be the preferred style in upstream ECMA-262.
> Editorial: Use consistent wording for throwing on undefined NewTarget

- docs/cookbook-nepali-calendar.md
- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/assert.js
- docs/cookbook/nepaliCalendar.mjs
- polyfill/package.json
This is an example of how to approach implementing a custom calendar, after Temporal.Calendar objects are removed.
It's an implementation of a Nepali calendar (described by @kabaros in https://github.com/tc39/proposal-temporal/issues/2854#issuecomment-2160132543) based on the implementation linked in that comment, as well as the implementation that was based on.
~~I used inheritance in this example because in this case that's slightly less code to write, but inheritance also makes some operations legal that maybe shouldn't be. (Like, `Temporal.PlainDateTime.from(nepaliPlainDate)`) So it might be better to switch to composition.~~
~~I'd also like to write a similar example about Hijri dates with manual adjustment (described in https://github.com/tc39/proposal-temporal/issues/2854#issuecomme …
> Cookbook example showing custom calendar proof of concept (without custom calendar object)

- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/plaintime.html
The first commit adds links to the early error section from the grammar so that it's not so easy for implementors to miss.
Note the second commit is optional. I haven't decided whether it's an improvement or not. I don't know how much more clarity it offers, against the downside of not having as much of the string validation as possible in the grammar.
Closes: #3128
> Clarify grammar early errors

- spec/abstractops.html
Currently the spec correctly disallows `Temporal.PlainMonthDay.from("07-17[u-ca=chinese]")`, however it incorrectly additionally disallows `2025-07-17[u-ca=chinese]`. It's evident that that is desired parser behavior since `ToTemporalMonthDay` has steps after the returning step 10.
The current behavior is because `ToTemporalMonthDay` (and YearMonth) parse `TemporalMonthDay` (etc) which contains both AnnotatedMonthDay and AnnotatedDateTime; but the parser exception doesn't discriminate between those two NTs since it matches on the requested goal, not the final NT that got parsed.
Both the polyfill and Firefox handle this "correctly", by performing the ISO check only after narrowly parsing an `AnnotatedMonthDay`, and then separately parsing an AnnotatedDateTime. …
> Correctly disallow calendared monthday/yearmonth strings whilst still allowing calendared datetime strings

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/calendar.html
- Update reference code to match spec text changes from #3134, #3135, #3139
- Reflect editorial changes that stage 2.7 reviewers of Intl Era/Month code asked for
> Editorial: Various updates regarding Era/Month code

- spec/duration.html
This operation can be called with a time unit as largestUnit. It should continue to work as advertised, the type assertion in the header was just wrong.
Closes: #3121
> Editorial: Fix type assertion in BubbleRelativeDuration

- polyfill/lib/calendar.mjs
Fixes #3153
Note that checking against test262 will require locally adopting https://github.com/js-temporal/temporal-test262-runner/pull/20, manually creating the missing directory, or a similar action.
> Polyfill: Speed up largestUnit: month date difference for calendars without leap months
