tc39/proposal-temporal

- README.md
This PR changes quite a few things, based on feedback received both here on GitHub, and in person from many others, as well as conversations that @maggiepint, @bterlson and I have had.
Will follow up with separate GH issues to track the TBDs and other thoughts.
> Update with baseline of revised proposal

- instant.html
@maggiepint @RedSquirrelious for review.
> initial stab at Instant

- spec-zonedinstant.html
Largely adapted from @pipobscure 's Instant.  Still must add algorithms for toCivil*
> initial stab at zonedinstant  @maggiepint

- README.md
Here is an example in response to https://github.com/tc39/proposal-temporal/issues/86#issuecomment-423367554.
The problem these two code snippets try to solve is: Given a date and time in Chicago, what is the date and time at that same instant in Sydney.
> Add an example of converting between time zones

- explainer.md
I've collated all the documentation on the different objects, updated them to what my latest understanding is and put them into one long document.
As of right now this is a Work-In-Progress, but I wanted to start it as a PR to progress further.
> Explainer of Objects

- README.md
Just some small changes in wording to make things a bit clearer.
> Small fixes in language

- civil.md
Adding some more points I brought up in the bike-shed thread.
Note: this will probably create a merge conflict with #144, which the author of that PR can resolve if necessary.
> Add additional Civil justification to civil.md

- spec/duration.html
This is a bare-bones spec for Duration just to get discussion/improvements down.
> Bare-Bones Duration specification

- techrecord.md
This comes out of [#139](https://github.com/tc39/proposal-temporal/issues/139). It's actually true that the epochNanoseconds and their ilk aren't really the value of the Instant and that the value of the Instant shouldn't be exposed. There is however a clear relation between an Instant and the epoch, so that `fromEpochNanoseconds()` and `getEpochNanoseconds()` should be the way forward.
There have been multiple requests that there is an interface to the time-zone data directly. For that reason we have introduced TimeZone objects. They stringify to the IANA-name of the timezone or the Offset-String in case of a pure offset.
Since `TimeZone` objects are now a thing and have all the information necessary to distinguish between pure offsets and actual IANA time-zones the distinction between …
> Update to Current-State of discussion

- spec.html
- spec/intl.html
***This is the reopening of #140***
This is a work in progress. Please let me know if this is roughly the direction to go in.
CC #129.
> Specify the integration with the Intl.DateTimeFormat API.

- spec/biblio.json
I forgot to check this in in #140/#155.
> Add biblio.json.

- .travis.yml
Also drop the encrypted variable for now.
> Use two Travis jobs.

- spec.html
- spec/duration.html
Started tinkering on this, please feel free to review and give suggestions.
/cc @pipobscure @littledan @Ms2ger
> Update spec text for Temporal.Duration

- spec/duration.html
> [spec] misc fixes to duration

- spec/biblio.json
- spec/date.html
- spec/datetime.html
- spec/duration.html
- spec/monthday.html
- spec/time.html
- spec/yearmonth.html
> Use RequireInternalSlot.

- docs/absolute.md
- docs/date.md
- docs/duration.md
Making a start here.
Documentation for Temporal.Absolute
* `from` is missing, i think i need to understand this one a bit more
* * I can't see to get from(obj) working properly, so would be interested in some help on this
* `toString` has an example, im not sure if we want these but toying with the idea
* same with Absolute the polyfill for Date.from() doesn't seem to work properly
> Adding documentation to Absolute & Date

- polyfill/lib/absolute.mjs
- polyfill/lib/casts.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/timezone.mjs
- polyfill/package.json
- polyfill/test/absolute.mjs
- polyfill/test/all.mjs
- polyfill/test/timezone.mjs
This supercedes #246
* Use big-integer polyfill instead of doing bigint maths by hand
* Add tests for plus/minus in Absolute
* Fix issues in Absolute plus/minus
> Using big-integer polyfill / fix absolute maths

- .editorConfig
- README.md
- cookbook/README.md
- cookbook/absoluteFromLegacyDate.mjs
- cookbook/getParseableZonedStringAtInstant.mjs
- polyfill/README.md
- polyfill/lib/index.mjs
> Addition of cookbook fixes #240

- README.md
Purpose: I'm happy to be champion for the Intl side of Temporal, including toLocaleString and Calendar.  I've been putting together a lot of meetings and doing write-ups and presentations on this topic.  It would be nice to be officially a champion for the purposes of today's TC39 presentation.
> Add sffc as a champion

- polyfill/lib/absolute.mjs
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/monthday.mjs
- polyfill/lib/time.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/time.mjs
> More explicit type checks

- docs/cookbook/sortAbsoluteInstants.mjs
Addition of Sort Absolute Instants to the cookbook
> sort Absolute Instants

- spec/date.html
> Fix definition for PadYear abstract operation

- docs/calendar-draft.md
- docs/date.md
- docs/datetime.md
- docs/yearmonth.md
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/yearmonth.mjs
- spec/date.html
- spec/datetime.html
- spec/yearmonth.html
The 'is' emphasizes that it's a yes or no answer.
Closes: #369
> Rename 'leapYear' property to 'isLeapYear'

- docs/head.html.part
This makes it clearer that the docs are not an authoritative reference
for the proposal, they just reflect the state of the polyfill.
> Add "incomplete" banner to the top of polyfill docs

- docs/monthday.md
Bringing the docs pages in line with the current state of the polyfill.
> Documentation for Temporal.MonthDay

- docs/date.md
- docs/datetime.md
Brings the documentation in line with the current state of the polyfill.
> Documentation for Temporal.Date

- polyfill/lib/absolute.mjs
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/time.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/absolute.mjs
- polyfill/test/date.mjs
- polyfill/test/monthday.mjs
- polyfill/test/time.mjs
- polyfill/test/yearmonth.mjs
- spec/absolute.html
- spec/duration.html
ToLimitedDuration was recently added to the spec. This brings the polyfill implementation more in line with the spec and adds some test coverage.
> Use ToLimitedDuration in polyfill

- polyfill/lib/time.mjs
- polyfill/test/time.mjs
- spec/duration.html
- spec/time.html
> Fix Time.difference to always return the smaller possible duration

- docs/date.md
- docs/datetime.md
- docs/time.md
- docs/yearmonth.md
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/time.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/date.mjs
- polyfill/test/datetime.mjs
- polyfill/test/time.mjs
- polyfill/test/yearmonth.mjs
- spec/abstractops.html
- spec/date.html
- spec/datetime.html
- spec/time.html
- spec/yearmonth.html
> Remove arithmetic balance

- docs/absolute.md
- docs/calendar-draft.md
- docs/date.md
- docs/datetime.md
- docs/time.md
- docs/yearmonth.md
- polyfill/lib/absolute.mjs
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/time.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/absolute.mjs
- polyfill/test/date.mjs
- polyfill/test/datemath.mjs
- polyfill/test/datetime.mjs
- polyfill/test/time.mjs
- polyfill/test/yearmonth.mjs
- spec/absolute.html
- spec/abstractops.html
- spec/date.html
- spec/datetime.html
- spec/time.html
- spec/yearmonth.html
> Add cutoff parameter to Date.difference() and DateTime.difference()

- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- polyfill/test/regex.mjs
- spec/date.html
This is something that I'll use for #312, and I've been rebasing it for some time while gradually working on the actual spec and having the discussion in #198. I think it would be useful to get this in, even though it doesn't change any functionality.
> Refactor regex

- docs/cookbook/getTimeStamp.mjs
This is created in response to https://github.com/tc39/proposal-temporal/issues/240#issuecomment-591689152
Its a simple one, but asked a lot
> get timestamp in JS fixes #240

- docs/cookbook/getCurrentDate.mjs
Addresses https://github.com/tc39/proposal-temporal/issues/240#issuecomment-591689152
> get date fixes #240

- polyfill/lib/duration.mjs
- polyfill/test/duration.mjs
- spec/duration.html
- spec/time.html
> Duration balance

- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/monthday.mjs
- polyfill/lib/time.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/date.mjs
- polyfill/test/duration.mjs
- polyfill/test/time.mjs
- spec/abstractops.html
- spec/datetime.html
- spec/duration.html
- spec/timezone.html
Best reviewed commit-by-commit, here's a bunch of miscellaneous small changes I've made while working on other things. Should be fairly uncontroversial.
> Misc fixes

- polyfill/lib/intl.mjs
- polyfill/test/intl.mjs
> intl: increase Intl coverage and incorporate fixes along the way

- polyfill/lib/intl.mjs
- polyfill/test/intl.mjs
Here goes more! Currently includes:
1. bugfix for legacy date as discussed yesterday.
2. remove Intl.DurationFormat (once a polyfill is available, it will be used).
3. more improvements to intl.mjs
TODO:
1. comprehensive tests.
2. more improvements?
> intl: bugfixes and other improvements

- polyfill/lib/duration.mjs
- polyfill/lib/intl.mjs
- polyfill/test/intl.mjs
could this be even better? :P
But seriously, this seems to be one of the last few improvements we need. Everything should be thoroughly tested at this point, please check.
TODOs:
1. Change spec to reflect these changes.
2. Keep watching `Intl.DurationFormat` to see when we need to pull the polyfill in.
> intl: more improvements

- polyfill/lib/absolute.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/test/absolute.mjs
- spec/absolute.html
> Remove time zone argument from Absolute.toJSON()

- polyfill/lib/absolute.mjs
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/monthday.mjs
- polyfill/lib/now.mjs
- polyfill/lib/time.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/ecmascript.mjs
- spec/absolute.html
- spec/abstractops.html
- spec/date.html
- spec/datetime.html
- spec/duration.html
- spec/monthday.html
- spec/temporal.html
- spec/time.html
- spec/timezone.html
- spec/yearmonth.html
> Use TemporalDate, temporalDateLike, etc. internally

- polyfill/lib/ecmascript.mjs
- polyfill/test/absolute.mjs
- spec/absolute.html
> Fix Absolute.from() disambiguation

- polyfill/test/absolute.mjs
- polyfill/test/date.mjs
- polyfill/test/datemath.mjs
- polyfill/test/datetime.mjs
- polyfill/test/ecmascript.mjs
- polyfill/test/exports.mjs
- polyfill/test/intl.mjs
- polyfill/test/now.mjs
- polyfill/test/regex.mjs
- polyfill/test/time.mjs
- polyfill/test/timezone.mjs
> Improve assert imports across tests.

- docs/cookbook.md
- docs/cookbook/absoluteFromLegacyDate.mjs
- docs/cookbook/getCurrentDate.mjs
- docs/cookbook/getParseableZonedStringAtInstant.mjs
> Cookbook use-case fix and a few minor improvements

- docs/cookbook/all.mjs
- docs/cookbook/getFirstTuesdayOfMonth.mjs
An implementation of getting the first Tuesday of the month.
Have at it.
> First Tuesday Of Month Fixes #240

- docs/package.json
here's diff of artifacts before-and-after the patch @ https://github.com/kaizhu256/proposal-temporal/compare/artifact-main..artifact-sed
> fix markdown rendering bug

- docs/calendar-draft.md
Marking the following issues fixed, since their consensuses are now documented in the Markdown file:
- Fixes #391
- Fixes #310
- Fixes #291
- Fixes #290
In addition, the following issues are now superseded:
- Fixes #389
- Fixes #390
> Updating calendar-draft.md with recent data model conclusions

- docs/cookbook/getParseableZonedStringAtInstant.mjs
Follow up from #482 suggested by Richard Gibson.
> Fix parameter documentation

- polyfill/ci_test.sh
- polyfill/test/parseResults.py
This allows for incremental output.
> Pipe test262-harness output to parseResults.py.

- package-lock.json
> meta: add package.lock for proposal

- docs/cookbook/all.mjs
- docs/cookbook/dateTimeFromLegacyDate.mjs
- docs/cookbook/legacyDateFromDateTime.mjs
Should help with both https://github.com/tc39/proposal-temporal/issues/299 and https://github.com/tc39/proposal-temporal/issues/370
> Date interop fixes #299

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/getParseableZonedStringWithLocalTimeInOtherZone.mjs
> Add getParseableZonedStringWithLocalTimeInOtherZone example to cookbook

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/getUtcOffsetDifferenceSecondsAtInstant.mjs
- docs/cookbook/getUtcOffsetSecondsAtInstant.mjs
- docs/cookbook/getUtcOffsetStringAtInstant.mjs
> Cookbook examples for UTC offsets

- polyfill/test/intl.mjs
some more intl fixes, better test organization and increase coverage
> intl: reorganize tests, add coverage

- docs/cookbook.md
- docs/cookbook/.eslintrc.yml
- docs/cookbook/absoluteFromLegacyDate.mjs
- docs/cookbook/dateTimeFromLegacyDate.mjs
- docs/cookbook/getFirstTuesdayOfMonth.mjs
- docs/cookbook/getParseableZonedStringAtInstant.mjs
- docs/cookbook/getParseableZonedStringWithLocalTimeInOtherZone.mjs
- docs/cookbook/getSortedLocalDateTimes.mjs
- docs/cookbook/getTimeZoneObjectFromIanaName.mjs
- docs/cookbook/getUtcOffsetDifferenceSecondsAtInstant.mjs
- docs/cookbook/getUtcOffsetSecondsAtInstant.mjs
- docs/cookbook/legacyDateFromDateTime.mjs
- docs/cookbook/sortAbsoluteInstants.mjs
- docs/timezone.md
- polyfill/test/resolve.cookbook.mjs
Implementing @littledan's suggestion to not use functions for one-liner cookbook examples.
See #240.
> Some cookbook changes

- docs/cookbook.md
The document is getting quite long now, and would benefit from a table
of contents. (This is autogenerated by a plugin in my editor,
unfortunately. Since markedjs doesn't support generating tables of
contents, it's either this, or maintain it manually, or generate it in
JavaScript when loading the page.)
> Add table of contents to cookbook

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/getElapsedDurationSinceInstant.mjs
> Add getElapsedDurationSinceInstant example to cookbook

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/getBusinessOpenStateText.mjs
> Add getBusinessOpenStateText example to cookbook

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/getInstantBeforeOldRecord.mjs
> Add getInstantBeforeOldRecord example to cookbook

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/getInstantOfNearestOffsetTransitionToInstant.mjs
This one works now thanks to #513 :smile: 
See: #240
> Add nearest UTC offset transition example to cookbook

- docs/cookbook/getInstantOfNearestOffsetTransitionToInstant.mjs
- polyfill/test/timezone.mjs
> timezone: stick to testing past DST transitions

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/getBusinessOpenStateText.mjs
- docs/cookbook/getInstantBeforeOldRecord.mjs
- docs/cookbook/getLocalizedArrival.mjs
- docs/cookbook/getSortedLocalDateTimes.mjs
- docs/cookbook/getTripDurationInHrMinSec.mjs
- docs/cookbook/nextWeeklyOccurrence.mjs
- docs/cookbook/plusAndRoundToMonthStart.mjs
- docs/cookbook/sortAbsoluteInstants.mjs
- docs/datetime.md
- polyfill/README.md
> Launch date example and some misc improvements

- docs/calendar-draft.md
These methods aren't necessary with our current data model.
> Remove Calendar.toISO/fromISO

- README.md
Reading this before a morning coffee, I derailed a few times due to punctuation. I hope these tweak tone and make this more readable.
> Copy edit introduction

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/bridgePublicHolidays.mjs
> Add "bridge public holiday" example to cookbook

- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/countPrecedingWeeklyDaysInMonth.mjs
- docs/cookbook/getFirstTuesdayOfMonth.mjs
- docs/cookbook/getWeeklyDaysInMonth.mjs
Augmenting the existing getFirstTuesday example, there were a few more
that Richard and Shane mentioned in the issue
See: #240
> Add more Nth-day-of-the-week examples

- docs/cookbook.md
- docs/cookbook/calendarInput.js
- docs/cookbook/futureDateForm.js
These examples show how it's possible to integrate Temporal with `<input type="date">` and HTML forms.
> Date picker cookbook examples

- meetings/agenda-minutes-2020-04-16.md
- meetings/agenda-minutes-2020-04-23.md
Tagging everyone with review access who was in these meetings
> Add meeting minutes from April 16 and 23

- docs/cookbook.md
- docs/cookbook/.eslintrc.yml
- docs/cookbook/storageTank.js
> Add storage tank example to cookbook

- docs/calendar-draft.md
> Add constructor parameter to calendar methods

- README.md
- spec.html
/cc @ptomato @littledan and everyone else. I guess we can merge this unless someone objects to it.
> meta: add @ryzokuken and @ptomato to champions

- docs/date.md
- docs/datetime.md
- docs/monthday.md
- docs/yearmonth.md
> Note explicitly in docs that months are 1-based, not 0-based

- README.md
- docs/README.md
- docs/absolute.md
- docs/date.md
- docs/datetime.md
- docs/duration.md
- docs/monthday.md
- docs/now.md
- docs/processMarkdown.js
- docs/time.md
- docs/timezone.md
- docs/yearmonth.md
This makes some adjustments to the API documentation landing page, rearranging the information from least to most detailed. Also changes some outdated things in the README and adds tables-of-contents to API documentation pages.
> Docs and readme landing

- docs/cookbook.md
- docs/cookbook/meetingPlanner.js
- docs/cookbook/storageTank.js
A simple time zone meeting planner using Temporal.
> Meeting planner example

- docs/monthday.md
cc @ptomato @justingrant
Fixes: #578
> docs: fix issue in monthday withYear documentation

- docs/datetime.md
> docs: fix error in DateTime toLocaleString docs

- docs/cookbook.md
- docs/cookbook/adjustDayOfMonth.mjs
- docs/cookbook/adjustMonth.mjs
- docs/cookbook/all.mjs
- docs/cookbook/birthdayIn2030.mjs
- docs/cookbook/noonOnDate.mjs
- docs/cookbook/roundDownToWholeHours.mjs
Use cases from #561 suggested by @justingrant
Closes: #561
See also: #240
> Add more examples of with() to the cookbook

- docs/cookbook.md
- docs/cookbook/getUtcOffsetDifferenceSecondsAtInstant.mjs
- docs/cookbook/getUtcOffsetSecondsAtInstant.mjs
- docs/cookbook/getUtcOffsetStringAtInstant.mjs
- docs/cookbook/meetingPlanner.js
- docs/now.md
- docs/timezone-draft.md
- docs/timezone.md
- polyfill/lib/ecmascript.mjs
- polyfill/lib/timezone.mjs
- polyfill/test/TimeZone/prototype/getOffsetNanosecondsFor/argument-not-absolute.js
- polyfill/test/TimeZone/prototype/getOffsetNanosecondsFor/branding.js
- polyfill/test/TimeZone/prototype/getOffsetNanosecondsFor/prop-desc.js
- polyfill/test/timezone.mjs
- spec/timezone.html
Method discussed in the custom time zone API draft.
Closes: #349
> Time zone offset in nanoseconds

- docs/README.md
/cc @ptomato you missed this one :smile:
> docs: remove timezone iterability clause

- docs/calendar-draft.md
> Add Reingold/Dershowitz citation in solar day discussion

- docs/ambiguity.md
- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/getInstantWithLocalTimeInZone.mjs
- docs/timezone-draft.md
- docs/timezone.md
- polyfill/lib/timezone.mjs
- polyfill/test/TimeZone/prototype/getPossibleAbsolutesFor/argument-not-datetime.js
- polyfill/test/TimeZone/prototype/getPossibleAbsolutesFor/branding.js
- polyfill/test/TimeZone/prototype/getPossibleAbsolutesFor/prop-desc.js
- polyfill/test/timezone.mjs
- spec/timezone.html
See time zone draft document.
Can be used to implement #317, #318.
> TimeZone.getPossibleAbsolutesFor()

- spec/date.html
- spec/datetime.html
- spec/duration.html
- spec/monthday.html
- spec/time.html
- spec/yearmonth.html
Records have fields, not internal slots.
> Fix misnomer in spec

- docs/calendar-draft.md
> Calendar draft fixups

- docs/timezone-draft.md
- polyfill/lib/ecmascript.mjs
- polyfill/lib/timezone.mjs
- spec/date.html
- spec/datetime.html
Prep work for implementing custom time zones. The next pull request will be stacked on top of this one.
> Custom time zones, phase 1

- docs/calendar.md
- docs/monthday.md
- docs/yearmonth.md
- polyfill/index.d.ts
- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/monthday.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/monthday.mjs
- polyfill/test/yearmonth.mjs
- spec/monthday.html
- spec/yearmonth.html
While waiting to finish up #638, here is a pull request with a few smaller fixes that can be merged independently of the iso8601 calendar.
> Calendar fixes

- README.md
- docs/head.html.part
- polyfill/README.md
- polyfill/package.json
Updates metadata, readme, and version
> Changes for publishing

- polyfill/README.md
- polyfill/package.json
- polyfill/test/absolute.mjs
- polyfill/test/date.mjs
- polyfill/test/datemath.mjs
- polyfill/test/datetime.mjs
- polyfill/test/duration.mjs
- polyfill/test/exhaust.mjs
- polyfill/test/exports.mjs
- polyfill/test/intl.mjs
- polyfill/test/monthday.mjs
- polyfill/test/now.mjs
- polyfill/test/regex.mjs
- polyfill/test/resolve.cookbook.mjs
- polyfill/test/time.mjs
- polyfill/test/timezone.mjs
- polyfill/test/usercalendar.mjs
- polyfill/test/usertimezone.mjs
- polyfill/test/yearmonth.mjs
'tc39-temporal' sounds like something official from TC39.
'proposal-temporal' sounds like something incomplete to try out, which
is what we are aiming for.
> Rename polyfill package to 'proposal-temporal'

- polyfill/lib/timezone.mjs
- spec/timezone.html
> timezone: call toString in toJSON

- polyfill/package.json
It's a bit annoying that this has to go via pull request, but :shrug:
> Version bump

- docs/cookbook/getBusinessOpenStateText.mjs
The result will be wrong if the closing time is near a DST transition
because of adding soonWindow to a Temporal.DateTime instead of a
Temporal.Absolute.
Closes: #698
> Fix DST bug in cookbook

- spec.html
- spec/absolute.html
- spec/date.html
- spec/datetime.html
- spec/duration.html
- spec/monthday.html
- spec/temporal.html
- spec/time.html
- spec/timezone.html
- spec/yearmonth.html
Start the process of updating the spec. Draft and rebased on top of #705.
/cc @ptomato
> Clean up and update spec

- polyfill/test/datetime.mjs
cSpell FTW! https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
> Fix typo in test case description

- docs/monthday.md
- polyfill/index.d.ts
- polyfill/lib/monthday.mjs
- polyfill/test/monthday.mjs
- spec/monthday.html
> Add disambiguation to MonthDay.toDateInYear

- meetings/agenda-minutes-2020-06-11.md
- meetings/agenda-minutes-2020-06-18.md
- meetings/agenda-minutes-2020-06-26.md
Tagging everyone for review who was present at one of the meetings, also @younies @leobalter
> Add minutes from the last three weeks

- polyfill/lib/datetime.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/time.mjs
This matches the specification, and leads to more readable code overall.
> [polyfill] Refactor using FormatSecondsStringPart.

- docs/absolute.md
- polyfill/lib/ecmascript.mjs
> Clarify Temporal.Absolute largest unit

- polyfill/lib/regex.mjs
- polyfill/test/DateTime/constructor/from/parser.js
- polyfill/test/regex.mjs
> polyfill: fix timezone parsing starting from c

- docs/README.md
- docs/balancing.md
> Clarify duration balancing and make explainers more prominent

- polyfill/lib/ecmascript.mjs
- polyfill/test/Absolute/constructor/argument.js
Fixes: https://github.com/tc39/proposal-temporal/issues/763
> polyfill: fix ES.ToBigInt

- polyfill/test/resolve.cookbook.mjs
Fixes: https://github.com/tc39/proposal-temporal/issues/792
/cc @gilmoreorless
> cookbook: fix resolver bug that broke CI

- spec.html
- spec/calendar.html
Added initial spec text for calendar. Wdyt? Should I add the stubs to the spec too?
> spec: add initial spec text for calendar

- docs/calendar-draft.md
> Record decision about caching calendar per-object information

- polyfill/lib/intrinsicclass.mjs
Add an additional check to ensure that intrinsics are registered once.
Refs: https://github.com/tc39/proposal-temporal/pull/832#discussion_r478316185
/cc @Ms2ger
> polyfill: add intrinsic check

- polyfill/lib/timezone.mjs
- polyfill/test/TimeZone/prototype/toJSON/custom-tostring-undefined.js
- polyfill/test/TimeZone/prototype/toJSON/tostring-call.js
- polyfill/test/TimeZone/prototype/toJSON/tostring-undefined.js
- spec/timezone.html
Refs: https://github.com/tc39/proposal-temporal/pull/832#discussion_r478282533
/cc @Ms2ger @ptomato
> timezonetojson: improve spec and add tests

- docs/absolute.md
- polyfill/lib/absolute.mjs
- polyfill/test/Absolute/prototype/minus/infinity-throws-rangeerror.js
- polyfill/test/Absolute/prototype/minus/negative-infinity-throws-rangeerror.js
- polyfill/test/Absolute/prototype/minus/order-of-operations.js
- polyfill/test/Absolute/prototype/plus/infinity-throws-rangeerror.js
- polyfill/test/Absolute/prototype/plus/negative-infinity-throws-rangeerror.js
- polyfill/test/Absolute/prototype/plus/order-of-operations.js
- polyfill/test/absolute.mjs
- spec/absolute.html
Weeks was already technically disallowed but not checked everywhere.
Days was allowed, but now is not.
Closes: #802
> Disallow Absolute arithmetic with days and weeks

- polyfill/lib/ecmascript.mjs
> polyfill: fix inconsistent method on ES object

- docs/time.md
- polyfill/index.d.ts
- polyfill/lib/ecmascript.mjs
- polyfill/lib/time.mjs
- polyfill/test/duration.mjs
- polyfill/test/time.mjs
- spec/duration.html
- spec/time.html
Preparation for implementing rounding in #827. I've split these out into a separate pull request to make the main one (coming soon) easier to review.
> Rounding preparation fixes

- docs/calendar.md
- docs/date.md
- docs/datetime.md
- docs/yearmonth.md
- polyfill/index.d.ts
- polyfill/lib/calendar.mjs
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/Date/prototype/daysInWeek/branding.js
- polyfill/test/Date/prototype/daysInWeek/prop-desc.js
- polyfill/test/Date/prototype/monthsInYear/branding.js
- polyfill/test/Date/prototype/monthsInYear/prop-desc.js
- polyfill/test/date.mjs
- polyfill/test/datetime.mjs
- polyfill/test/yearmonth.mjs
- spec/calendar.html
- spec/date.html
- spec/datetime.html
- spec/yearmonth.html
> monthsInYear and daysInWeek

- .eslintrc.yml
- polyfill/lib/calendar.mjs
- polyfill/test/ISO8601Calendar/prototype/toStringTag/prop-desc.js
- spec.html
- spec/calendar.html
- spec/isocalendar.html
This leaves the actual algorithms undefined, but it serves as a skeleton for
the work that needs to be done.
> Specify ISO8601Calendar.

- polyfill/lib/ecmascript.mjs
- polyfill/test/absolute.mjs
- polyfill/test/date.mjs
- polyfill/test/datetime.mjs
- polyfill/test/duration.mjs
- polyfill/test/ecmascript.mjs
- polyfill/test/monthday.mjs
- polyfill/test/time.mjs
- polyfill/test/timezone.mjs
- polyfill/test/yearmonth.mjs
- spec/abstractops.html
See tc39/ecma402#480 and tc39/ecma402#493. This seems to have critical mass over on the ECMA-402 side now, so I'm opening this PR again.
> Options must be an object

- README.md
I don't really feel like a champion, but I couldn't find a "participation trophy" list so this will have to do. ;-)
So grateful for the opportunity to help with this project. Y'all are a great team.
> Add myself to champions list

- docs/package.json
- package-lock.json
- package.json
- polyfill/package.json
There's a prettier bugfix I wanted to pick up, so while I was in the
neighborhood I updated all build dependencies to latest versions,
except demitasse that (per earlier discussion) we're not planning
to update soon.
> Update build dependencies

- docs/README.md
- docs/absolute.md
- docs/date.md
- docs/datetime.md
- docs/head.html.part
- docs/now.md
- docs/time.md
- docs/timezone.md
I'm committing these cleanups from #922 in advance, in order to make the review easier.
> Various edits in advance of LocalDateTime docs

- CHANGELOG.md
- README.md
I'm planning to release a 0.4 as soon as possible. A lot of changes have been made since the last release. This is an update to the changelog and the proposal status, in preparation for that.
> Release 0.4

- README.md
- polyfill/package.json
Argh, these should have been included in #944. Sorry for the noise.
> Release 0.4 try again

- polyfill/index.d.ts
> types: update duration overflow options

- docs/date.md
- docs/datetime.md
- docs/monthday.md
- docs/yearmonth.md
> Fix documentation of era property in from() methods

- polyfill/index.d.ts
- polyfill/lib/date.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/monthday.mjs
- polyfill/lib/yearmonth.mjs
> Fix fields object in calendar.{date,yearMonth,monthDay}FromFields()

- polyfill/lib/ecmascript.mjs
- polyfill/test/duration.mjs
- spec/duration.html
> Fix overflow in Duration.toString()

- meetings/agenda-minutes-2020-07-09.md
- meetings/agenda-minutes-2020-07-16.md
- meetings/agenda-minutes-2020-07-23.md
- meetings/agenda-minutes-2020-07-31.md
- meetings/agenda-minutes-2020-08-06.md
- meetings/agenda-minutes-2020-08-13.md
- meetings/agenda-minutes-2020-08-20.md
- meetings/agenda-minutes-2020-08-27.md
- meetings/agenda-minutes-2020-08-28.md
- meetings/agenda-minutes-2020-09-03.md
- meetings/agenda-minutes-2020-09-04.md
- meetings/agenda-minutes-2020-09-10.md
- meetings/agenda-minutes-2020-09-11.md
- meetings/agenda-minutes-2020-09-17.md
- meetings/agenda-minutes-2020-09-18.md
- meetings/agenda-minutes-2020-10-01.md
@ptomato @littledan @pipobscure @jasonwilliams @sffc @justingrant @mj1856 @gibson042 and anyone else attending the meetings who I might've missed: please check if you have any objection to these notes being published.
> chore: add meeting notes

- docs/balancing.md
This PR updates the duration balancing docs page with a bunch of recent changes to how balancing works: 
* Adds info about `relativeTo` and removes content saying that months/years won't be balanced
* Accounts for rename of plus->add and minus->subtract
* Removes content relating to the `overflow` option which is no longer used with Duration
* Clarifies how balancing works now using `round`, including discussion of how `largestUnit` is used for balancing
> Update balancing docs page

- spec/abstractops.html
- spec/date.html
- spec/datetime.html
- spec/instant.html
- spec/isocalendar.html
- spec/time.html
- spec/yearmonth.html
See https://github.com/tc39/ecma262/pull/2007. More work will be needed, but this already fixes the warnings.
> Fix number-related warnings.

- polyfill/lib/calendar.mjs
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/monthday.mjs
- polyfill/lib/now.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/yearmonth.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/date.html
- spec/datetime.html
- spec/instant.html
- spec/temporal.html
- spec/timezone.html
> Rename GetDefaultCalendar to GetISO8601Calendar

- polyfill/test/instant.mjs
> Fix remaining 'abs' references.

- spec/intl.html
> Add note to ECMA-402 diffs about host environment tzdata updates

- docs/calendar.md
- docs/timezone.md
- polyfill/lib/calendar.mjs
- polyfill/lib/regex.mjs
- polyfill/lib/timezone.mjs
- polyfill/test/instant.mjs
- polyfill/test/regex.mjs
- polyfill/test/usercalendar.mjs
- polyfill/test/usertimezone.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/timezone.html
> Define valid calendar and time zone IDs

- polyfill/lib/ecmascript.mjs
- spec/date.html
- spec/datetime.html
- spec/monthday.html
- spec/yearmonth.html
These are in preparation for #666.
> Various spec improvements

- polyfill/lib/calendar.mjs
- polyfill/test/all.mjs
- polyfill/test/calendar.mjs
- spec/abstractops.html
- spec/calendar.html
> Calendar.from should take ISO string

- docs/calendar.md
- docs/timezone.md
- polyfill/index.d.ts
- polyfill/lib/calendar.mjs
- polyfill/lib/timezone.mjs
- polyfill/test/calendar.mjs
- polyfill/test/timezone.mjs
- spec/calendar.html
- spec/timezone.html
> Allow property bags in TimeZone.from and Calendar.from

- polyfill/lib/regex.mjs
> Fix regex pattern for timezone offset parsing

- spec/intl.html
Fixes: https://github.com/tc39/proposal-temporal/issues/1022
/cc @Ms2ger
> spec: update Intl to use ISO prefixed slot names

- docs/date.md
- docs/datetime.md
- docs/instant.md
- polyfill/lib/instant.mjs
- polyfill/lib/intl.mjs
- polyfill/test/intl.mjs
With a couple of incidental bug fixes.
Closes: #1021
> Document where the time zone comes from in Instant.toLocaleString

- docs/calendar.md
- docs/date.md
- docs/datetime.md
- docs/monthday.md
- docs/yearmonth.md
- polyfill/index.d.ts
- polyfill/lib/calendar.mjs
- polyfill/lib/date.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/monthday.mjs
- polyfill/lib/yearmonth.mjs
- polyfill/test/Date/constructor/from/order-of-operations.js
- polyfill/test/Date/prototype/with/order-of-operations.js
- polyfill/test/DateTime/constructor/from/order-of-operations.js
- polyfill/test/DateTime/prototype/with/order-of-operations.js
- polyfill/test/YearMonth/constructor/from/order-of-operations.js
- polyfill/test/YearMonth/prototype/with/order-of-operations.js
- polyfill/test/calendar.mjs
- polyfill/test/date.mjs
- polyfill/test/datetime.mjs
- polyfill/test/yearmonth.mjs
- spec/date.html
- spec/datetime.html
- spec/monthday.html
- spec/yearmonth.html
> Don't use 'era' in iso8601 calendar

- polyfill/lib/ecmascript.mjs
- polyfill/test/date.mjs
- polyfill/test/datetime.mjs
- polyfill/test/duration.mjs
- spec/duration.html
Currently requires #1060, so review that first.
Closes: #1059
> Fix bugs in rounding algorithm

- docs/duration.md
- polyfill/index.d.ts
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/test/duration.mjs
- spec/duration.html
> Remove Duration arithmetic overflow option

- polyfill/index.d.ts
- polyfill/lib/calendar.mjs
- polyfill/lib/datetime.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/regex.mjs
- polyfill/test/validStrings.mjs
- polyfill/test/zoneddatetime.mjs
- spec/abstractops.html
- spec/datetime.html
- spec/instant.html
- spec/timezone.html
- spec/zoneddatetime.html
Next part of ZonedDateTime implementation, including:
- addressing code review comments that arrived after the last PR was merged
- completed missing parts of implementation of from()
- implementation of getFields()
> ZonedDateTime, part 2

- .github/workflows/lint.yml
- .github/workflows/test.yml
Only one action remains to be ported, which is WIP. It'll need me to check out how GitHub Secrets work.
> add github actions workflows

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
> Add deploy CI action

- docs/calendar.md
- docs/date.md
- docs/datetime.md
- docs/time.md
Draft PR containing doc changes.
> add time calendar docs

- docs/zoneddatetime.md
- polyfill/lib/ecmascript.mjs
- polyfill/lib/time.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/time.mjs
- polyfill/test/zoneddatetime.mjs
- spec/time.html
- spec/zoneddatetime.html
Including the tentative decision from #906 
See: #569
> ZonedDateTime.with()

- docs/now.md
The huge plainXxx PR that just landed (#1135) conflicted with #1132 and it looks like merge conflicts were checked into main. 
This PR resolves the conflicts.
> Remove merge conflicts from main in now.md

- polyfill/index.d.ts
- polyfill/lib/ecmascript.mjs
- polyfill/lib/now.mjs
- polyfill/test/now.mjs
Add polyfill code and relevant tests for `Temporal.now.plainTime`.
> polyfill: add Temporal.now.plainTime

- docs/monthday.md
- polyfill/index.d.ts
- polyfill/lib/plainmonthday.mjs
- polyfill/test/plainmonthday.mjs
- spec/plainmonthday.html
> Remove options argument from MonthDay.toPlainDate.

- docs/date.md
- docs/instant.md
- docs/time.md
- polyfill/index.d.ts
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaintime.mjs
- spec/plaindate.html
- spec/plaintime.html
> Update toZonedDateTime documentation.

- docs/date.md
- docs/datetime.md
- docs/monthday.md
- docs/time.md
- docs/yearmonth.md
- polyfill/index.d.ts
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/PlainDate/prototype/with/order-of-operations.js
- polyfill/test/PlainDateTime/prototype/with/order-of-operations.js
- polyfill/test/PlainMonthDay/prototype/with/order-of-operations.js
- polyfill/test/PlainTime/prototype/with/order-of-operations.js
- polyfill/test/PlainYearMonth/prototype/with/order-of-operations.js
- polyfill/test/plaindate.mjs
- polyfill/test/plaindatetime.mjs
- polyfill/test/plainmonthday.mjs
- polyfill/test/plaintime.mjs
- polyfill/test/plainyearmonth.mjs
- polyfill/test/usercalendar.mjs
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
> Update with() methods.

- polyfill/lib/regex.mjs
- polyfill/test/timezone.mjs
> Correct timezone offset allowed range 

- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/zoneddatetime.mjs
- spec/zoneddatetime.html
> Fix rounding in ZonedDateTime.toString()

- polyfill/lib/ecmascript.mjs
- spec/plaindate.html
/cc @justingrant @ptomato 
Fixes: #1124 
Refs: #1123
> Add spec text for DifferenceDate

- docs/cookbook/calculateDailyOccurrence.mjs
- docs/cookbook/getBusinessOpenStateText.mjs
- docs/cookbook/nextWeeklyOccurrence.mjs
- docs/date.md
- docs/time.md
- polyfill/index.d.ts
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaintime.mjs
- polyfill/test/plaindate.mjs
- polyfill/test/plaintime.mjs
- spec/plaindate.html
- spec/plaintime.html
> 'plain' in toZonedDateTime argument properties

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/duration.mjs
- spec/duration.html
- spec/zoneddatetime.html
> Misc ZonedDateTime and Duration changes to support relativeTo

- polyfill/index.d.ts
- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/duration.mjs
- polyfill/test/zoneddatetime.mjs
- spec/duration.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
This fixes support for Duration arithmetic with ZonedDateTime relativeTo, and rounding ZonedDateTime when the day is not 24 hours.
See: #1171
> Some ZonedDateTime relativeTo support

- docs/datetime.md
- docs/zoneddatetime.md
Fixes a few typos in withPlainTime docs code samples
> Fix a few docs typos

- docs/object-model.svg
- docs/persistence-model.svg
- spec.html
> Add object diagram and persistence diagram to spec

- spec.html
- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/legacydate.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
> Separate ECMA-262 and ECMA-402 parts of calendar- and locale-dependent spec text

- README.md
- docs/README.md
- docs/head.html.part
This is a bit out of date. We should close the survey and note that the
proposal is still unstable, since it may change during review, but that we
are done making design decisions.
> Update proposal status

- polyfill/lib/calendar.mjs
- polyfill/test/calendar.mjs
- polyfill/test/plainmonthday.mjs
- polyfill/test/plainyearmonth.mjs
- spec/calendar.html
- spec/intl.html
> Review ES.ToRecord called on non-objects

- polyfill/lib/ecmascript.mjs
- spec/duration.html
> Omit fractional Numbers support in Duration.from for now.

- docs/plaintime.md
- polyfill/lib/plaintime.mjs
- polyfill/test/plaintime.mjs
- spec/plaintime.html
> Remove options arguments from PlainTime.add/subtract.

- docs/calendar.md
> Clarify the documentation for constructor arguments in Calendar.

- spec/plaindate.html
> Update the spec for PlainDate.add/subtract.

- docs/README.md
> Add some examples to the documentation readme.

- docs/README.md
> Fix README example

- polyfill/test/plaindatetime.mjs
- polyfill/test/zoneddatetime.mjs
- spec/zoneddatetime.html
Fix discrepancy in spec text, and make the tests on this topic consistent.
Closes: #341
> from() always returns new object

- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
> Fix some missing 'Plain' prefixes in intrinsic references.

- docs/instant.md
- docs/now.md
- docs/plaindate.md
- docs/plaindatetime.md
- docs/plaintime.md
> Fix broken links to removed heading in documentation

- spec/calendar.html
> Specify ConsolidateCalendars abstract operation.

- polyfill/lib/calendar.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/Calendar/constructor/constructor/missing-arguments.js
- polyfill/test/Instant/constructor/constructor/argument.js
- polyfill/test/PlainDate/constructor/constructor/missing-arguments.js
- polyfill/test/PlainDateTime/constructor/constructor/missing-arguments.js
- polyfill/test/PlainMonthDay/constructor/constructor/missing-arguments.js
- polyfill/test/PlainYearMonth/constructor/constructor/missing-arguments.js
- polyfill/test/TimeZone/constructor/constructor/missing-arguments.js
- polyfill/test/ZonedDateTime/constructor/constructor/missing-arguments.js
- polyfill/test/ZonedDateTime/constructor/constructor/timezone-undefined.js
> [polyfill] Clarify constructor error messages for missing required arguments.

- spec/abstractops.html
- spec/duration.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
Ref: https://github.com/tc39/ecma262/pull/2007.
Fixes #1295.
> Update name of ToInteger abstract operation.

- docs/README.md
> Close code block in docs intro page.

- meetings/agenda-minutes-2020-10-08.md
- meetings/agenda-minutes-2020-10-09.md
- meetings/agenda-minutes-2020-10-15.md
- meetings/agenda-minutes-2020-10-22.md
- meetings/agenda-minutes-2020-10-23.md
- meetings/agenda-minutes-2020-10-29.md
I intend to publish the backlog of meeting minutes that I had been neglecting in October / November due to being busy finishing up the proposal. Here is the first installment.
> Add minutes from October meetings

- docs/calendar.md
- polyfill/index.d.ts
- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/usercalendar.mjs
- spec/calendar.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
> Calendar.mergeFields()

- polyfill/lib/duration.mjs
I have no idea how I failed to cherry-pick this properly on Thursday, I thought I did.
> Polyfill: Remove getFields from Duration

- docs/calendar.md
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
> Options handling

- polyfill/lib/ecmascript.mjs
> Clarify invalid duration field error message

- spec/calendar.html
- spec/duration.html
- spec/timezone.html
> Use GetMethod for looking up calendar and time zone methods

- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
> Replace Get+Call by Invoke

- meetings/agenda-minutes-2020-11-05.md
- meetings/agenda-minutes-2020-11-12.md
- meetings/agenda-minutes-2020-12-03.md
- meetings/agenda-minutes-2020-12-10.md
- meetings/agenda-minutes-2020-12-17.md
- meetings/agenda-minutes-2021-01-07.md
- meetings/agenda-minutes-2021-01-14.md
- meetings/agenda-minutes-2021-01-19.md
- meetings/agenda-minutes-2021-01-21.md
Review requested from everyone who was there (and also @younies, @Manishearth, @leobalter who attended but aren't on the reviewers list) — please check within the next few days that what you said is accurately reflected.
> Minutes from recent meetings

- docs/calendar.md
- docs/cookbook-expandedyears.md
- docs/cookbook.md
- docs/cookbook/all.mjs
- docs/cookbook/makeExpandedTemporal.mjs
Originally suggested by @gibson042 in #240.
A full implementation of this would be a lot larger, so this example is intentionally a partial one.
Closes: #604
> "Expanded Temporal" cookbook example

- polyfill/lib/calendar.mjs
- polyfill/test/PlainDate/constructor/from/order-of-operations.js
- polyfill/test/PlainDate/prototype/with/order-of-operations.js
- polyfill/test/PlainDateTime/constructor/from/order-of-operations.js
- polyfill/test/PlainDateTime/prototype/with/order-of-operations.js
- polyfill/test/PlainMonthDay/constructor/from/infinity-handled.js
- polyfill/test/PlainMonthDay/constructor/from/options-undefined.js
- polyfill/test/PlainMonthDay/constructor/from/order-of-operations.js
- polyfill/test/PlainMonthDay/constructor/from/subclass.js
- polyfill/test/PlainMonthDay/prototype/with/infinity-handled.js
- polyfill/test/PlainMonthDay/prototype/with/order-of-operations.js
- polyfill/test/PlainMonthDay/prototype/with/subclass-constructor-undefined.js
- polyfill/test/PlainMonthDay/prototype/with/subclass-species-null.js
- polyfill/test/PlainMonthDay/prototype/with/subclass-species-undefined.js
- polyfill/test/PlainMonthDay/prototype/with/subclass.js
- polyfill/test/PlainYearMonth/constructor/from/order-of-operations.js
- polyfill/test/PlainYearMonth/prototype/with/order-of-operations.js
- polyfill/test/intl.mjs
- polyfill/test/plaindate.mjs
- polyfill/test/plaindatetime.mjs
- polyfill/test/plainmonthday.mjs
- polyfill/test/plainyearmonth.mjs
- polyfill/test/regex.mjs
- polyfill/test/usercalendar.mjs
- polyfill/test/zoneddatetime.mjs
> Update polyfill to use zero-padded month codes

- spec/intl.html
> Clarify host time zone information updates to refer to time zone database

- polyfill/lib/ecmascript.mjs
- polyfill/test/Duration/prototype/toString/precision.js
- spec/abstractops.html
- spec/duration.html
Same bug as #1351 in another place, oops.
Fixes #1404.
> polyfill: fix Duration precision bug

- README.md
> Update contributors in readme

- docs/cookbook.md
Just a single character typo fix.
> Fix a small typo

- polyfill/index.d.ts
Based on https://github.com/tc39/proposal-temporal/blob/732751277ed13c65f82fb55496354c428ebc58b3/polyfill/lib/instant.mjs#L63
> polyfill: fix the Instant methods types

- spec/calendar.html
Remove CompareCalendar which no spec text referring to
close #1476
> Remove dangling CompareCalendar

- spec/abstractops.html
> Remove dangling ToTemporalDurationOverflow

- spec/abstractops.html
Remove IsValidCalendarID which no spec text referring to
close #1477
> Remove dangling IsValidCalendarID

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plainyearmonth.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/temporal.html
- spec/timezone.html
- spec/zoneddatetime.html
Fixes the normative issues identified in #1424 (and a few various editorial things)
See: #1424
> Various normative issues that are part of Stage 3 conditions

- spec/plaindatetime.html
Remove RegulateISODateTime which no spec text referring to
and ConstrainISODateTime which only referred by RegulateISODateTime
close #1473 #1474
> Remove dangling RegulateISODateTime ConstrainISODateTime

- docs/README.md
- docs/plaindatetime.md
Closes: #1460
Closes: #1461
cc: @meyerweb
> Docs fixes

- spec/duration.html
> Editorial: Mark AddDuration argument relativeTo as required.

- docs/zoneddatetime.md
Fix typo: ZonedDateTimeFormat -> DateTimeFormat
Fixes #1559
> Update zoneddatetime.md to fix typo: ZonedDateTimeFormat -> DateTimeFormat

- docs/zoneddatetime.md
> fix type of offset to string from number

- polyfill/test/parseResults.js
This was present in the original Python script but not ported as we didn't
have any expected failures at the time.
> Add a mechanism for expected failures in test262 tests

- polyfill/lib/intl.mjs
- polyfill/test/Instant/prototype/toLocaleString/options-conflict.js
- polyfill/test/PlainDate/prototype/toLocaleString/options-conflict.js
- polyfill/test/PlainDateTime/prototype/toLocaleString/options-conflict.js
- polyfill/test/PlainTime/prototype/toLocaleString/options-conflict.js
- polyfill/test/ZonedDateTime/prototype/toLocaleString/options-conflict.js
- polyfill/test/expected-failures.txt
Added `dateStyle`/`timeStyle` support into polyfill.
Fixes #1590
> Add dateStyle/timeStyle to Intl helpers

- polyfill/lib/ecmascript.mjs
Port of https://github.com/js-temporal/temporal-polyfill/pull/14
> Fix division issues caught by tsc in RoundDuration

- meetings/agenda-minutes-2021-03-03.md
- meetings/agenda-minutes-2021-03-04.md
- meetings/agenda-minutes-2021-03-18.md
Sorry I have gotten so far behind on these. I'll be doing them in batches of one month at a time.
> Add champions meeting minutes from March

- spec/duration.html
somehow CalculateOffsetShift miss the w arg and didn't pass it to CalculateOffsetShift
@ptomato @justingrant @jugglinmike @Ms2ger @ryzokuken @ljharb
> Add w CalculateOffsetShift  pass to AddZonedDateTime

- spec/duration.html
UnbalanceDurationRelative is very long. Just shorten it a little bit.
> Editorial: Simplify UnbalanceDurationRelative

- polyfill/index.d.ts
* Rename XxxLike types to include the Plain prefix
* Add PlainDateTime and ZonedDateTime to PlainTimeLike type (fixes #1707)
> Fix XxxLike TS types

- spec/calendar.html
Somehow  [[InitializedTemporalDateTime]] is missing from these places.
> Editorial: Add ", [[InitializedTemporalDateTime]]" to list

- spec/plainmonthday.html
One place use plainMonthDay, change it to name monthDay to be consisent.
> Editoral: Consistenly use monthDay for this

- spec/timezone.html
Add " or *null* if no such transition exists" to GetIANATimeZoneNextTransition and GetIANATimeZonePreviousTransition
https://tc39.es/proposal-temporal/#sec-temporal-getianatimezonenexttransition
Fixes #1764
> Editoral: add "or *null* if no such transition exists"

- README.md
- docs/zh_CN/README.md
I have translated a document into Chinese. I will continue this work in my free time :(
> docs: add chinese translations

- spec/duration.html
Attempt to fix https://github.com/tc39/proposal-temporal/issues/1658
@justingrant @ptomato @littledan @ljharb @Ms2ger @ryzokuken @linusg
> Normative: Fix undefined, NaN, Infinity in ToTemporalDurationRecord

- polyfill/lib/duration.mjs
- polyfill/test/Duration/constructor/constructor/infinity-throws-rangeerror.js
- polyfill/test/Duration/constructor/constructor/negative-infinity-throws-rangeerror.js
- spec/duration.html
Change it to align with other Temporal.Plain* constructor 
Close https://github.com/tc39/proposal-temporal/issues/1598
@ptomato @ryzokuken @sffc @justingrant @Ms2ger
> Normative: Check +/-∞ in Temporal.Duration after ToIntegerOrInfinity

- spec/abstractops.html
No tests needed, as the algorithm as a whole is sufficiently covered that
enough would fail if it were implemented as previously written.
Closes: #1666
> Normative: Fix typo in variable name

- spec/abstractops.html
Clarify "--" is optional together in DateSpecMonthDay
address https://github.com/tc39/proposal-temporal/issues/1800
@ptomato
> Editorial: Clarify "--" is optional together

- polyfill/index.d.ts
Port of https://github.com/js-temporal/temporal-polyfill/pull/53
> Add @@toStringTag to TS types

- spec/duration.html
> Normative: Fix TemporalDurationToString for negative duration

- polyfill/lib/plainmonthday.mjs
> [polyfill] PlainMonthDay#toPlainDate() rejects out-of-range dates.

- spec/abstractops.html
These changes are by @gibson042, from #1907. This is the non-normative changes from that pull request, split out into a separate pull request in order to land them earlier.
> Editorial: Simplify Duration parsing

- spec/abstractops.html
- spec/biblio.json
- spec/mainadditions.html
It might even be possible to take this further for leveraging e.g. [StringNumericValue](https://tc39.es/ecma262/#sec-runtime-semantics-stringnumericvalue) and/or [MV](https://tc39.es/ecma262/#sec-static-semantics-mv).
> Editorial: Reuse preexisting productions

- meetings/agenda-minutes-2021-09-30.md
- meetings/agenda-minutes-2021-10-14.md
- meetings/agenda-minutes-2021-10-28.md
> Next three meeting minutes

- docs/zoneddatetime.md
Hi,
if have correctly understood the API, I think the example should be more like my proposed change.
Thank you for this awesome API !
> Fix `ZonedDateTime` example

- polyfill/index.d.ts
Port of https://github.com/js-temporal/temporal-polyfill/pull/126 and https://github.com/js-temporal/temporal-polyfill/pull/121
> Update TS types from temporal-polyfill

- docs/plaindate.md
> Update docs to explain mid-month rounding

- README.md
> add row about fullcalendar's temporal-polyfill

- docs/ambiguity.md
- docs/instant.md
- docs/ja/ambiguity.md
> Fix micro/milli typos in docs

- polyfill/test/instant.mjs
See https://github.com/tc39/test262/pull/3431
> Remove tests ported to test262

- polyfill/lib/ecmascript.mjs
- spec/plaindate.html
> Editorial: Remove unused code in DifferenceISODate.

- spec/duration.html
- spec/instant.html
- spec/zoneddatetime.html
> More editorial Duration stuff

- spec/intl.html
This adjusts the diff so that the end result is closer to what is currently in ecma402 ([4689559437e3bda8b9264364b8ac6df6ec240b2c](https://github.com/tc39/ecma402/commit/4689559437e3bda8b9264364b8ac6df6ec240b2c)).
> Editorial: Adjust InitializeDateTimeFormat diffs to current ecma402.

- polyfill/test/validStrings.mjs
Adds syntax constraints that the parsing function now checks for. Additionally fixes the test's exit code so that it should actually fail the CI job if it fails.
Closes: #2103
> Fix validStrings test

- docs/README.md
- docs/ja/README.md
- docs/zh_CN/README.md
See #2126.
I don't see any option to squash the commits in GitHub's web interface. Are *you* able to do it? Alledgedly, there is a "Squash and merge" button.
> Correct wrong docs sentence in the form "A or A" to "A or B"

- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
From https://github.com/tc39/ecma262/pull/2699.
> Editorial: Use ToZeroPaddedDecimalString.

- polyfill/test/duration.mjs
- polyfill/test/instant.mjs
- polyfill/test/plaindatetime.mjs
- polyfill/test/timezone.mjs
- polyfill/test/zoneddatetime.mjs
Also ported a bunch of tests that were nearly identical to the Instant
tests, while I was at it.
See https://github.com/tc39/test262/pull/3468
> Port Instant.toString() tests to test262

- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/duration.mjs
I ran into these while converting some more tests to test262.
> Various fixes

- polyfill/test/plaindatetime.mjs
Goes with [this](https://github.com/tc39/test262/pull/3497) PR on the Test262 side.
> Drop tests ported to Test262

- polyfill/test/duration.mjs
- polyfill/test/instant.mjs
> Remove tests from Demitasse that landed in test262

- spec/timezone.html
Some editorial fixes around the time zones language.
> Editorial changes

- spec/intl.html
Refactor out all the current "implementation-defined" behavior into abstract operations that do a slightly better job of explaining what's supposed to happen.
Fixes: https://github.com/tc39/proposal-temporal/issues/1899
/cc @FrankYFTang
> Editorial: refactor intl spec

- spec/intl.html
see my comments in https://github.com/tc39/proposal-temporal/pull/1928#issuecomment-1112599130
@ryzokuken @ptomato
> Editorial: Fix errors introduced by pull/1928

- polyfill/test/expected-failures.txt
- polyfill/test/instant.mjs
- polyfill/test/zoneddatetime.mjs
The bug fix has been merged in test262 upstream, so we can remove the temporary expected failures.
> Remove some more ported tests and update test262

- spec/abstractops.html
cf. https://github.com/tc39/proposal-temporal/pull/1952#issuecomment-1120689942
> Editorial: Remove unnecessary productions

- spec/intl.html
Overflow should be a String in https://github.com/tc39/proposal-temporal/pull/1928
@ryzokuken
> Editorial: Correct mistake made in pull/1928

- polyfill/lib/ecmascript.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/zoneddatetime.html
- Change TemporalTimeZoneIdentifier as discussed in #2200
- Make one of the changes described in #2099 which doesn't lead to observable changes
- Determined two Gets are infallible
- Make some progress on #1465
> Various editorial changes

- polyfill/lib/calendar.mjs
- polyfill/test/intl.mjs
Port of https://github.com/js-temporal/temporal-polyfill/pull/153
> Polyfill: Lunisolar math fixes

- spec/abstractops.html
- spec/intl.html
> Editorial: Align GetOption with ECMA-402

- spec/timezone.html
> Only call CanonicalizeTimeZoneName on valid time zone ids 

- spec/duration.html
> Editorial: Fix typo in Time Duration Records

- spec/duration.html
> Editorial: Mark CreateDurationRecord in RoundDuration as fallible

- spec/abstractops.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Create a new AO GetDifferenceSettings() to read values from options
for Difference* operations and use it from various DifferenceTemporal* AOs
> Editorial: Refactor common option reading operation into a AO

- spec/abstractops.html
This is an extraction of the initial editorial commits from #2284.
> Editorial: Improve the "NotAmbiguous" grammar

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/plaindatetime.html
- spec/timezone.html
- Update reference code to match recent changes to spec
- Add some clarifying assertions
> Various non-normative changes

- package-lock.json
- package.json
- spec/intl.html
This would also have caught the two typos in https://github.com/tc39/proposal-temporal/pull/2348 but @gibson042 was too quick.
> bump ecmarkup and fix typo caught thereby

- spec/intl.html
> Editorial: Correct HandleDateTimeValue from ! to ?

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- spec/duration.html
> Normative: Fix Duration.prototype.total() return value

- polyfill/ci_codecov_test262.sh
- polyfill/runtest262.mjs
Ref c945cb24b6b6b6df6a29b12c184741e6118a489b
> Meta: Don't conflate missing files and test failures

- docs/duration.md
Result matches 130 hours and 20 minutes.
> Editorial: Fix typo

- spec/intl.html
fix https://github.com/tc39/proposal-temporal/issues/2401
> Fix CalendarDateMergeFields param and return to Object

- polyfill/lib/ecmascript.mjs
- polyfill/lib/zoneddatetime.mjs
These were caught by Anba's test262 tests.
> Polyfill: More precision fixes

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
Fixes: #2112 
Thanks @ptomato for help!
> Normative: Fix generating durations from non-numeric inputs 

- spec/mainadditions.html
- spec/temporal.html
> Introduce a host hook for the current time.

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
These are all regressions or bugs introduced by #2482, spotted by @anba, eagle-eyed as always.
> Fixes to builtins-as-strings change

- polyfill/lib/ecmascript.mjs
Suggested by @12wrigja in 
https://github.com/js-temporal/temporal-polyfill/pull/244/files#r1169245765
> Polyfill: Add comment explaining ASCIILowercase AO

- polyfill/lib/ecmascript.mjs
- polyfill/test/validStrings.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
- Preparation for #2519 to make rebasing easier
- Address some review comments from #2519 that applied to existing spec text
- Implement a suggestion from Anba (#2282)
Best reviewed commit by commit.
> Editorial improvements

- polyfill/index.d.ts
This PR adds a few .d.ts updates that were missed recently.
* Add `yearOfWeek`
* Add `toString` options for `critical` flag
* Update `CalendarLike` and `TimeZoneLike` types to account for string slot changes.
* Simplify PlainTimeLike type
* Update a few comments
* Move `getCalendar` and `getTimeZone` methods under their corresponding properties to make it easier for readers to realize that they're connected.
> Polyfill: Sync index.d.ts with temporal-polyfill

- spec/instant.html
> Editorial: Remove unnecessary type coercion

- spec/abstractops.html
> Editorial: Improve the explanation of ISO 8601 grammar deviations

- polyfill/lib/ecmascript.mjs
- spec/plaindate.html
Fixes #2649. See https://github.com/tc39/proposal-temporal/issues/2649#issuecomment-1684907910 for an explanation of why it's unreachable.
> Editorial: Remove unreachable steps in DifferenceISODate

- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/zoneddatetime.mjs
This fixes a few more compliance issues with the reference code, that I came across while writing test262 tests.
> More alignment of reference code to spec

- spec.html
> Change the duplicate month/year to month/day in the introduction

- spec/abstractops.html
- spec/plaindatetime.html
- spec/plainmonthday.html
Encountered as part of #2519 and #2664; should make the diffs a bit smaller to review.
> Minor editorial changes

- docs/duration.md
- docs/instant.md
- docs/plaindatetime.md
- docs/plaintime.md
- docs/zoneddatetime.md
- polyfill/lib/ecmascript.mjs
- spec/plaindate.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
- Editorial fix from @anba #2699
- Docs fixes #2709, #2711
> Editorial and docs fixes

- docs/now.md
- spec/abstractops.html
- spec/duration.html
- spec/instant.html
Fixes some outstanding editorial issues and makes some progress on adding structured headers everywhere.
> Editorial progress

- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
Closes: #2533, #2534, #2548, #2549, #2552
> Editorial: Address various issues raised by Anba

- docs/zoneddatetime.md
- polyfill/lib/ecmascript.mjs
- polyfill/lib/regex.mjs
- spec/abstractops.html
- spec/intl.html
- spec/plaindatetime.html
- spec/timezone.html
- spec/zoneddatetime.html
Closing out more minor editorial issues from the backlog.
Closes: #2358, #2382, #2452, #2523, #2524, #2525, #2530
> Editorial: More minor improvements

- docs/buildDocs.js
Hi there, I'm Japanses user but now ja-localized document page can not use playground in a console.
Because localized page uses sub dir but those resource is written with relative path from doc root and all pages use same static header/footer.
Therefore I fixed doc build script to replace relative path in header/footer content for each sub directory output.
Thank you.
> Editorial: Fix doc build.js for localized page

- polyfill/lib/ecmascript.mjs
- spec/duration.html
- spec/zoneddatetime.html
This PR fixes a batch of editorial issues recently opened by @anba.
> Editorial: Fix newly opened comments

- polyfill/lib/ecmascript.mjs
- spec/duration.html
- spec/plaindatetime.html
- spec/timezone.html
This PR consists of fixes for issues opened recently by Anba, or other things I spotted while making those fixes.
Closes: #2775, #2782, #2783, #2784
> Editorial: More fixes for things that Anba pointed out

- polyfill/lib/ecmascript.mjs
- spec/duration.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
Addressing another batch of editorial issues, most of them opened by @anba.
> Editorial issues

- meetings/agenda-minutes-2023-01-19.md
- meetings/agenda-minutes-2023-01-26.md
- meetings/agenda-minutes-2023-02-09.md
- meetings/agenda-minutes-2023-02-15.md
- meetings/agenda-minutes-2023-02-23.md
- meetings/agenda-minutes-2023-03-02.md
- meetings/agenda-minutes-2023-03-09.md
- meetings/agenda-minutes-2023-03-16.md
- meetings/agenda-minutes-2023-03-30.md
- meetings/agenda-minutes-2023-04-13.md
- meetings/agenda-minutes-2023-04-27.md
- meetings/agenda-minutes-2023-05-11.md
- meetings/agenda-minutes-2023-05-25.md
- meetings/agenda-minutes-2023-06-08.md
- meetings/agenda-minutes-2023-08-17.md
- meetings/agenda-minutes-2023-08-31.md
- meetings/agenda-minutes-2023-09-14.md
- meetings/agenda-minutes-2023-10-12.md
- meetings/agenda-minutes-2023-10-26.md
- meetings/agenda-minutes-2023-11-09.md
- meetings/agenda-minutes-2023-11-16.md
- meetings/agenda-minutes-2023-12-07.md
- meetings/agenda-minutes-2024-01-11.md
- meetings/agenda-minutes-2024-01-18.md
- meetings/agenda-minutes-2024-01-25.md
- meetings/agenda-minutes-2024-01-26.md
- meetings/agenda-minutes-2024-02-01.md
- meetings/agenda-minutes-2024-02-15.md
- meetings/agenda-minutes-2024-02-29.md
I've been neglecting to update the meeting minutes in the repo. This is all of them since the last time I updated.
> Meeting minutes

- docs/calendar.md
- docs/plaindate.md
- docs/plaindatetime.md
- docs/plaintime.md
- docs/plainyearmonth.md
- docs/zoneddatetime.md
- polyfill/lib/calendar.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
I went through the backlog and fixed a bunch of minor editorial issues that are unlikely to collide with any of the PRs currently in review.
Best reviewed commit by commit.
Hopefully none of these need much discussion. If discussion is needed about a particular commit, I'll instead remove it from here and put it in a separate PR so it doesn't hold up the rest.
> Editorial: Close a bunch of old minor issues

- polyfill/lib/calendar.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/timezone.mjs
- polyfill/lib/zoneddatetime.mjs
- polyfill/test/ecmascript.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
Most of these renames were suggested by @gibson042 in #2441. I'd like to get this in before we land other simplifications.
Closes: #2441
> Editorial: Rename operations dealing with options bags

- polyfill/lib/ecmascript.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
Modernize editorial conventions & address a defect spotted by @anba.
> Editorial: Smaller batch of editorial improvements

- .github/workflows/test.yml
- package-lock.json
- package.json
- polyfill/ci_codecov_test262.sh
- polyfill/package.json
- spec/intl.html
> Update ecmarkup and codecov

- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainyearmonth.md
- docs/zoneddatetime.md
> Docs: Align `year` descriptions

- .github/workflows/test.yml
- docs/plaindate.md
- docs/plaindatetime.md
- docs/plainmonthday.md
- docs/plainyearmonth.md
- polyfill/ci_codecov_test262.sh
- polyfill/lib/assert.mjs
- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/intl.mjs
- polyfill/lib/timeduration.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/mainadditions.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plaintime.html
- spec/zoneddatetime.html
A few more minor things, and a fix for correctly uploading to codecov.io so that viewing source works in the codecov reports.
Closes: #2951 (cc @anba)
> Editorial batch

- polyfill/lib/duration.mjs
- polyfill/lib/ecmascript.mjs
- polyfill/lib/instant.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/plaindatetime.mjs
- polyfill/lib/plainmonthday.mjs
- polyfill/lib/plaintime.mjs
- polyfill/lib/plainyearmonth.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/calendar.html
- spec/duration.html
- spec/instant.html
- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/zoneddatetime.html
Addresses the recent batch of corrections submitted by @anba.
> Editorial: Address Anba's requests

- polyfill/lib/ecmascript.mjs
- polyfill/lib/plaindate.mjs
- polyfill/lib/zoneddatetime.mjs
- spec/abstractops.html
- spec/duration.html
- spec/instant.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
- spec/timezone.html
- spec/zoneddatetime.html
This contains fixes for all the outstanding editorial issues from Anba. It fixes all the instances of #2985 that I've found, but I'll follow up with test262 tests and possibly more if I find any.
> Editorial: Fix more of Anba's requests

- spec/calendar.html
This is a speculative PR for what I think is probably the best way to address #3002.
Closes: #3002
> Editorial: Clarify requirement for implementation-defined month-day validation

- spec/duration.html
- spec/timezone.html
> Editorial: Address feedback from Anba

- spec/timezone.html
> Editorial: Clarify definition of "time zone transition"

- polyfill/lib/ecmascript.mjs
- polyfill/test/expected-failures.txt
- spec/abstractops.html
- spec/zoneddatetime.html
> Normative: Require strict matching with a precise ZonedDateTime offset

- spec/intl.html
- spec/plaindate.html
- spec/plaindatetime.html
- spec/plainmonthday.html
- spec/plaintime.html
- spec/plainyearmonth.html
> Editorial: Use consistent naming for this value
