README.md, spec/civildatetime.html, spec/civiltime.html
The previous forms of the constructor optional arguments gave the
nanosecond field the highest priority, with the second field the lowest.
This patch reverses the optional brace nesting to match intended usage.
Fixes #75.
=> Correct optional constructor arguments for CivilTime and CivilDateTime.

meetings/agenda-minutes-2018-06-18.md, spec/instant.html, spec/zoneddatetime.html
Fixes half of #127
(The other half of #127 is discussed in #131 and I didn't want to touch that)
=> Fix milisecond->millisecond typos

spec-rendered.html
Intl.DateTimeFormat was mistyped as Intl.DateFormatter and
Intl.DateDormatter, which has been fixed.
Fixes: https://github.com/tc39/proposal-temporal/issues/131
/cc @frankyftank
=> Editorial: Fix mistypes of Intl.DateTimeFormat

objects.md, spec/instant.html, spec/offsetdatetime.html, spec/zoneddatetime.html
Basic cleanup of the spec to closer match `objects.md` .
Reason is that it's just as easy to `offsetdatetime.instant.withZone()` which is much more explicit.
=> Cleanup ZonedDateTime & OffsetDateTime Spec

polyfill/lib/casts.mjs
Unify the behavior of Temporal.Duration.from() on all numerical types
(number and bigint) and providing previously available behavior through
the static Temporal.Duration.fromNanoSeconds() method.
/cc @pipobscure @Ms2ger @littledan
=> [polyfill] unify behavior on numerical types

docs/absolute.md, docs/datetime.md, docs/playground.md, polyfill/lib/absolute.mjs, polyfill/lib/casts.mjs, polyfill/lib/datetime.mjs, polyfill/test/absolute.mjs, polyfill/test/datetime.mjs
Rename `Absolute.prototype.inZone` and `DateTime.prototype.inZone` to
`Absolute.prototype.inTimeZone` and `DateTime.prototype.inTimeZone`
respectively, since Temporal.TimeZone now exists.
Fixes: https://github.com/tc39/proposal-temporal/issues/235
=> [api] rename inZone to inTimeZone

docs/monthday.md, polyfill/lib/monthday.mjs
Add a disambiguation parameteter to `MonthDay.prototype.withYear`,
finally enabling disambiguation across all `with*` methods in the API.
Fixes: https://github.com/tc39/proposal-temporal/issues/179
(Since we decided it was best to keep `disambiguation` consistently across the API wherever necessary, this puts all our disambiguation worries to an end. All constructors, `plus` methods, `minus` methods, and `with*` methods now have a disambiguation parameter).
=> [polyfill] add disambiguation param to withYear

spec/duration.html, spec/time.html
In the spec, BalanceTime was returning an object with a [[Day]] internal
slot, which was neither inline with the polyfill nor the intended
behavior, this PR renames that slot to [[Days]], which better represents
is actual significance (to denote the delta days).
Fixes: https://github.com/tc39/proposal-temporal/issues/234
=> [spec] fix all occurances of [[Day]] in BalanceTime

polyfill/test/monthday.mjs
@pipobscure 
Add tests for `tec39-temporal.MonthDay`, covering the following APIs:
1. `get day()` and `get month()`
2. `plus()`
Increase statement coverage from 45.45% to 62.99%.
=> [polyfill] Add tests for MonthDay

docs/datetime.md, docs/monthday.md, docs/playground.md, docs/time.md, docs/timezone.md, docs/yearmonth.md, polyfill/lib/absolute.mjs, polyfill/lib/casts.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/monthday.mjs, polyfill/lib/time.mjs, polyfill/lib/timezone.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/absolute.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/intl.mjs, polyfill/test/monthday.mjs, polyfill/test/time.mjs, polyfill/test/yearmonth.mjs, spec/absolute.html, spec/date.html, spec/datetime.html, spec/duration.html, spec/monthday.html, spec/time.html, spec/yearmonth.html
Merge the `from` and `fromString` methods on the various builtins.
=> Merge from and fromString methods

docs/absolute.md, docs/date.md, docs/datetime.md, docs/duration.md, docs/monthday.md, docs/time.md, docs/yearmonth.md
It usually helps to show the constructors (plus other ways of creating this object) near the top.
As most developers will use `from` rather than the `new` constructor the from method should be shown just underneath.
=> move from to the top under constructor

docs/yearmonth.md
A space ended up in the wrong position.
=> Typo in yearmonth.md

README.md
s/An/A/ in Temporal.Absolute's description because it was bugging me. Every other class described starts with "A".
Entirely possible "An" is matching against the class name "Absolute" starting with a vowel, which would hold true because all of the ones starting with "A" have classes that start with consonants. Feel free to close this if that's the case. :)
=> Grammar nit in readme.md

docs/package.json
The links in the generated HTML now point to .html siblings instead of .md siblings.
=> Correct generated doc links

docs/calendar-draft.md
I made a doc detailing my understanding of the state of the Temporal calendar design, following the 10+ hours of discussions this week at TC39.
@pipobscure @robpalme @apaprocki @spectranaut @caiolima
=> Explainer for API changes for calendar support

polyfill/lib/ecmascript.mjs, polyfill/test/absolute.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/duration.mjs, polyfill/test/monthday.mjs, polyfill/test/time.mjs, polyfill/test/yearmonth.mjs
This fixes some of the functions to properly throw `RangeError`s instead of (accidentally) `ReferenceError`s.
There are still some outstanding issues with these errors, particularly around the message of those errors. I didn't want to conflate this PR from the singular goal of fixing which type of error is thrown.
=> Fix references of `iso` to `isoString`

README.md
The polyfill isn't necessarily more authoritative than the spec text; everything's undergoing changes.
=> Edit warning note

polyfill/test/duration.mjs
Two blocks of duration tests were identical except one had better error messaging. I removed the duplicated set and kept the more descriptive messaging.
=> Remove test duplication from polyfill/tests/duration.mjs.

docs/calendar-draft.md
I started the table to compare the pros and cons of four default calendar options.  I'm sure I'm missing something.  @spectranaut, do you have the notes from the meeting on Thursday December 5?
@pipobscure @robpalme @apaprocki @caiolima @littledan
=> Adding default calendar pros and cons

docs/README.md, docs/absolute.md, docs/calendar-draft.md, docs/timezone.md, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/regex.mjs, polyfill/lib/timezone.mjs, polyfill/test/duration.mjs, polyfill/test/timezone.mjs
MDN-style documentation of Temporal.TimeZone, plus minor bug fixes so that the examples work.
=> Temporal.TimeZone docs

docs/setup.ejs, polyfill/lib/index.mjs, polyfill/lib/initialise.js
The rationale for this is that client code might come to depend on the
shipped API working like the polyfill.
We do use the setup function twice internally, to initialize the docs
playground and the node interpreter playground. In these cases, instead
import the Temporal and Intl objects from the polyfill and copy them to
the global object manually.
Closes: #306
=> Remove setup() function from polyfill

docs/duration.md, spec/duration.html
Corrects the signature of `new Temporal.Duration()` in the reference docs and spec to match the polyfill.
Closes: #276
=> Fix Duration constructor docs

docs/date.md, docs/datetime.md, docs/monthday.md, docs/time.md, docs/yearmonth.md, polyfill/lib/absolute.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/monthday.mjs, polyfill/lib/timezone.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/absolute.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/monthday.mjs, polyfill/test/time.mjs, polyfill/test/timezone.mjs, polyfill/test/yearmonth.mjs, spec/absolute.html, spec/date.html, spec/datetime.html, spec/monthday.html, spec/time.html, spec/timezone.html, spec/yearmonth.html
Removes casting from all `compare()` and `difference()` methods, as well as:
- `Date.withTime()`
- `Time.withDate()`
- `TimeZone.getOffsetFor()`
- `TimeZone.getAbsoluteFor()`
Closes: #237
=> Remove casting in methods

docs/absolute.md, docs/date.md, docs/datetime.md, docs/duration.md, docs/monthday.md, docs/time.md, docs/timezone.md, docs/yearmonth.md
This is intended to make the difference between methods and static
methods clearer in the reference docs.
=> Add section headings in reference docs

polyfill/lib/timezone.mjs, polyfill/test/timezone.mjs, spec/abstractops.html, spec/date.html, spec/datetime.html, spec/duration.html, spec/monthday.html, spec/time.html, spec/timezone.html, spec/yearmonth.html
This also removes the unused argument to Temporal.Date.prototype.difference.
Fixes #254.
=> Spec handling of invalid disambiguation values.

polyfill/package.json, polyfill/rollup.config.js
So i wanted to step into the .mjs code, but rollup currently has both sourcemaps off and uglify mangling the variable names, so in development mode ive turned these off, (sourcemaps i've just turned on for all environments as it causes no harm).
If anyone uses vscode i can also share the launch profile i have, but that could be a separate PR.
I also updated the dependencies as rollup was a few version behind.
p.s we should probably unignore the package-lock.json file
=> adjust rollup config for debugging purposes

.travis.yml
Travis has been broken since the automatic update to 12.16.0 with
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /home/travis/build/tc39/proposal-temporal/polyfill/package.json
This pins the version for now, until we figure out what's wrong.
=> [ci] Pin node version.

.travis.yml, polyfill/test/resolve.compiled.mjs, polyfill/test/resolve.source.mjs
Importing JSON doesn't work natively.
Un-pin the version of node.
=> Use fs to import JSON

docs/calendar-draft.md
=> Changing symbols to strings for Calendar

polyfill/lib/ecmascript.mjs, polyfill/test/absolute.mjs
Temporal.Absolute.from() with a time zone was broken.
Closes: #352.
=> Fix time zone offset bug

polyfill/test/all.mjs, polyfill/test/regex.mjs
- Re-enable regex tests which were commented out
- Fix bug in generating test expressions which was giving durations with multiple seconds components
=> Re-enable regex tests

polyfill/lib/ecmascript.mjs, polyfill/test/absolute.mjs, polyfill/test/datetime.mjs, polyfill/test/time.mjs
When parsing an ISO string with a :60 seconds value, silently convert it
to :59, which is the behaviour specified by POSIX. In all other cases,
treat it as any other out-of-range value, which means following the same
behaviour that would happen, for example, with :61 seconds.
(Note that the disambiguation argument will be moved out of the constructor in #260, so this is not identical to the final desired behaviour we agreed upon in the meeting — which assumes #260 is already implemented.)
Closes: #339
=> Deal with input containing leap seconds

docs/monthday.md, polyfill/lib/monthday.mjs, polyfill/test/monthday.mjs, spec/monthday.html
As discussed in the ticket, we'll consider MonthDay arithmetic undefined
without a year attached, because of not knowing whether the year is a
leap year or not.
Also remove MonthDay.daysInMonth which is meaningless without a year and
was not in the spec or polyfill anyway.
Closes: #261
=> Remove arithmetic from MonthDay

docs/cookbook/getSortedLocalDateTimes.mjs
This currently does not work.
```
proposal-temporal/cookbook/getSortedLocalDateTimes.mjs:12
return a.compare(b);
^
TypeError: a.compare is not a function
```
Does anyone know why? 
According to the code/docs .compare() should exist
=> adding getSortedLocalDateTimes

spec/date.html, spec/datetime.html, spec/monthday.html, spec/time.html, spec/yearmonth.html
This is not a particularly useful thing to do, as the string parsing will
fill in all the fields, making the call little more than a more expensive
way to call from().
The polyfill does not support passing strings.
=> Drop support for passing strings to with().

docs/duration.md, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/duration.mjs, spec/duration.html, spec/time.html
Previously, the code assumed that the millisecond, microsecond, and
nanosecond fields of Duration all had 3 digits or less. This allows for
the possibility of values ≥ 1000. In order to allow this, roundtripping
via toString() is no longer preserved, we have to balance the sub-second
units with a new abstract operation BalanceSubSecond.
Closes: #396
=> Fix Duration.toString for sub-second units > 999

spec/absolute.html
=> Editorial: Remove obsolete todo notes from the specification.

.gitignore, .travis.yml, codecov.yml, docs/package.json, docs/rollup.config.ejs, package.json, polyfill/ci_test.sh, polyfill/package.json, polyfill/rollup-script.config.js, polyfill/rollup.config.js, polyfill/test/transform.test262.js
This is pretty hacky due to a bunch of shortcomings in the available tooling, as detailed in the commit message, but it merges the code coverage from the test262 tests into the lcov file submitted to codecov.io.
=> Test262 coverage

spec/absolute.html
This is tested in polyfill/test/absolute.mjs.
Fixes #420.
=> Define the return type for Absolute#getEpoch{Milli,}Seconds.

spec/date.html, spec/monthday.html, spec/time.html, spec/yearmonth.html
I verified these abstract operations are only called from the `from` static
methods, behind a Type check.
=> Editorial: Replace some always-true checks with assertions in the spec.

docs/calendar-subclass.md
This is a document that briefly introduces the subclassing approach, and then goes into several key areas where the semantics of the two approaches (Temporal.Calendar and Temporal.Date Subclassing) would differ.
See #392
=> Adding initial calendar-subclass.md explainer

docs/duration.md
This has been blocked on #408 for a while, but I'd like to get it in before the March plenary, in order to have complete documentation even if it means that the documentation is temporarily ahead of the polyfill.
=> Documentation for Temporal.Duration

polyfill/lib/timezone.mjs, polyfill/test/TimeZone/prototype/getAbsoluteFor/argument-not-datetime.js, spec/timezone.html
=> Don't coerce the dateTime argument to TimeZone#getAbsoluteFor.

spec/datetime.html
I verified this abstract operation is only called from the `from` static
method, behind a Type check.
=> Editorial: Assert that ToTemporalDateTime is only called with objects.

polyfill/lib/absolute.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/Absolute/prototype/minus/subclass-out-of-range.js, polyfill/test/Absolute/prototype/plus/subclass-out-of-range.js, polyfill/test/absolute.mjs, polyfill/test/timezone.mjs, spec/biblio.json
- implement ECMA-262 ToBigInt in terms of big-integer library so that our conversions are more compliant
- only get the `bigInt.value` property if it is actually a native BigInt, otherwise return the big-integer wrapper
=> BigInt fixes

package.json
This brings in the fix for https://github.com/bterlson/ecmarkup/issues/184 in particular.
=> Update ecmarkup to ensure markup errors are caught.

spec/duration.html
I verified this abstract operation is only called from two places, both behind a Type check.
=> Editorial: Assert that ToTemporalDuration is only called with objects.

polyfill/lib/ecmascript.mjs
Follow-up to #479 suggested by Ms2ger. The unique() function is overkill
for just one call on an array with two elements.
=> Remove unique() function from polyfill

polyfill/ci_test.sh, polyfill/test/parseResults.py
Parsing the output all at once can cause out-of-memory errors in automated testing.
=> Use ijson to parse the test262 results.

polyfill/package.json
The CI was broken at some point, likely because of some breaking change
in the full-icu npm module. While I couldn't reproduce the issue locally
on Linux, this is a best guess PR which should ideally fix it.
I have confirmed that it builds locally with the changes, so best case,
it doesn't further break anything.
=> meta: unbreak CI

polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/duration.mjs
Define the abstract operation that is expected here, and add a test that
exercises toLocaleString without caring about the contents of the
returned string.
=> Fix Duration.toLocaleString

docs/parse-draft.md
=> WIP: Add proposals for resolving questions with from()/Temporal.parse()

docs/cookbook.md, docs/cookbook/all.mjs, docs/cookbook/nextWeeklyOccurrence.mjs
This is a generalization of the code snippet that I use to calculate the next occurrence of the weekly Temporal call!
See: #240
=> Add nextWeeklyOccurrence example to cookbook

docs/timezone-draft.md, docs/timezone.md
=> Draft of custom time zone API

docs/cookbook.md, docs/cookbook/all.mjs, docs/cookbook/calculateDailyOccurrence.mjs
It was mentioned in #26 that the documentation used to have two use case
examples. This was one of them. (The other was already covered by
"Preserving absolute instant".)
See: #26, #240
=> Add back one of the examples from the old documentation

docs/cookbook.md, docs/cookbook/all.mjs, docs/cookbook/localTimeForFutureEvents.mjs
This is adapted from Andrew's comment on #26.
See: #240
=> Add second example to "preserving absolute instant" in cookbook

polyfill/lib/absolute.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/intl.mjs, polyfill/lib/intrinsicclass.mjs, polyfill/lib/monthday.mjs, polyfill/lib/now.mjs, polyfill/lib/temporal.mjs, polyfill/lib/time.mjs, polyfill/lib/timezone.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/all.mjs
This removes the warning about circular dependencies that is printed when bundling the JS sources.
=> Untangle dependencies

polyfill/test/monthday.mjs, spec/monthday.html
MonthDays cannot be out of range, since they are cyclical. The spec text
would throw on an out-of-range MonthDay, however, if a large enough
number was the value of a property of the month-day-like object passed
to MonthDay.with. Fix the spec text and create RejectMonthDay and
ConstrainMonthDay abstract operations.
The polyfill didn't have this bug, but add a regression test anyway.
Closes: #444
=> Fix RegulateMonthDay so it cannot be out of range

docs/calendar-draft.md, docs/monthday.md, polyfill/lib/monthday.mjs, polyfill/test/MonthDay/prototype/withYear/infinity-throws-rangeerror.js, polyfill/test/MonthDay/prototype/withYear/negative-infinity-throws-rangeerror.js, polyfill/test/monthday.mjs, spec/monthday.html
=> withYear() object argument

.travis.yml, package.json, polyfill/README.md, polyfill/package.json
It could be confused with building the cookbook (npm run build:docs).
Closes: #565
=> Rename 'cookbook' npm script to 'test-cookbook'

docs/calendar-draft.md, docs/timezone-draft.md
From a conversation with @littledan. It doesn't seem necessary to provide two ways to do this, as long as you can replace the individual methods listed there in the draft. Additionally, it's good to keep the points where a monkeypatch is needed to a minimum.
=> Remove draft about replacing Temporal.TimeZone and Temporal.now objects

polyfill/lib/intl.mjs, polyfill/test/intl.mjs
If the formatting options request a time zone name for any type except
Absolute, or a day for YearMonth, or a year for MonthDay, we want to
ignore that, since the data model for that type doesn't contain those
units.
Closes: #572
=> Ignore units not in the data type when formatting with Intl

docs/time.md
Clear up this language a bit and explain that the default is effectively
hours.
Closes: #580
=> Fix confusion about Temporal.Time.difference largest unit

polyfill/lib/ecmascript.mjs, polyfill/test/ecmascript.mjs
Fixes #575, which is an infinite loop in Chrome caused by https://bugs.chromium.org/p/chromium/issues/detail?id=1045791, where Chrome reports "24:00" instead of "00:00" for midnight times. This breaks `ES.GetFormatterParts` which in turn causes the infinite loop.
This 1-line PR treats `hour==='24'` as if it were zero.
For some reason the Temporal test suites won't run on my Mac, so it may take a few pushes to get all tests passing. I'll commit the test changes first to validate that the tests work, then push the code changes. _EDIT: Actually this didn't help because CI tests don't run in a real browser.  This means that the test added in this PR won't actually catch the original problem. Probably should consider using a browser-hosted test runner like …
=> WIP: Fix infinite loop (only in Chrome) in ES.GetFormatterParts

docs/iso-string-ext.md
I am writing up this doc in order to have a place to point people on what extensions we are making to the ISO-8601 syntax.  Let me know if this looks good or if I missed any other exceptions.
See #293
=> Adding initial explainer for extended ISO string syntax

polyfill/.npmignore
The polyfill package currently installs over 80MB of test files. Real users of the polyfill won't need those, right?
This PR reduces polyfill download size from 11.4MB to to 400KB (and on-disk size from 89MB to 2.3MB, and `npm pack` time by >90%) by adding the following to .npmignore: 
* test folders
* build scripts
* (selfishly for me) typescript-related tooling files I keep in my fork that don't need to be in the package
Before: 
```
npm notice === Tarball Details === 
npm notice name:          tc39-temporal                           
npm notice version:       1.0.0                                   
npm notice filename:      tc39-temporal-1.0.0.tgz                 
npm notice package size:  11.4 MB                                 
npm notice unpacked size: 89.6 MB …
```
=> Add test files and build scripts to polyfill's .npmignore

polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/monthday.mjs, polyfill/lib/slots.mjs, polyfill/lib/time.mjs, polyfill/lib/yearmonth.mjs, spec/date.html, spec/datetime.html, spec/monthday.html, spec/yearmonth.html
Once we build calendar support, things are going to get confusing if we
aren't more specific in the names. This renames all year, month, and day
in constructor arguments to isoYear, isoMonth, and isoDay respectively;
and renames [[Year]], [[Month]], and [[Day]] internal slots to
[[IsoYear]], [[IsoMonth]], and [[IsoDay]].
Other methods might benefit from having their arguments renamed, but
we'll do that as they are ported to the calendar world, in order to
avoid too much churn.
=> Rename slots and constructor arguments to isoYear, isoMonth, isoDay

docs/head.html.part
This is a particularly unimportant change, but it was starting to really annoy me when scrolling.
The banner at the top of docs pages had `width: 100vw`. Unfortunately `vw` ignores the scrollbar, so in browsers with non-floating scrollbars, the page caused an extra bit of horizontal space (and therefore an unnecessary horizontal scrollbar).
=> Remove horizontal scrollbar on docs pages

polyfill/lib/ecmascript.mjs, polyfill/lib/slots.mjs, polyfill/lib/timezone.mjs, polyfill/test/ecmascript.mjs
Temporal.Calendar is also going to have an identifier, but we will need
to have separate internal slots in order to tell the two types apart.
No change in the spec is needed because the spec has additional
[[InitializedTemporalX]] slots which we don't have in the polyfill.
=> Replace IDENTIFIER slot with TIMEZONE_ID

docs/date.md, docs/datetime.md, docs/monthday.md, docs/yearmonth.md, polyfill/index.d.ts, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/monthday.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/Date/prototype/getISOCalendarFields/branding.js, polyfill/test/Date/prototype/getISOCalendarFields/prop-desc.js, polyfill/test/Date/prototype/getISOCalendarFields/subclass.js, polyfill/test/DateTime/prototype/getISOCalendarFields/branding.js, polyfill/test/DateTime/prototype/getISOCalendarFields/prop-desc.js, polyfill/test/DateTime/prototype/getISOCalendarFields/subclass.js, polyfill/test/MonthDay/prototype/getISOCalendarFields/branding.js, polyfill/test/MonthDay/prototype/getISOCalendarFields/prop-desc.js, polyfill/test/MonthDay/prototype/getISOCalendarFields/subclass.js, polyfill/test/YearMonth/prototype/getISOCalendarFields/branding.js, polyfill/test/YearMonth/prototype/getISOCalendarFields/prop-desc.js, polyfill/test/YearMonth/prototype/getISOCalendarFields/subclass.js, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/monthday.mjs, polyfill/test/yearmonth.mjs, spec/date.html, spec/datetime.html, spec/monthday.html, spec/yearmonth.html
This is in order to be able to get the underlying fields from the data
model, which are stored in the ISO 8601 calendar.
It's not expected to be used in normal Temporal usage, it really exists
only for calendar implementors.
Closes: #354
=> Add getISOCalendarFields() method to calendar-dependent types

docs/absolute.md, docs/date.md, docs/datetime.md, docs/duration.md, docs/monthday.md, docs/time.md, docs/yearmonth.md, polyfill/lib/absolute.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/duration.mjs, polyfill/lib/monthday.mjs, polyfill/lib/time.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/absolute.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/duration.mjs, polyfill/test/monthday.mjs, polyfill/test/time.mjs, polyfill/test/yearmonth.mjs, spec/absolute.html, spec/date.html, spec/datetime.html, spec/duration.html, spec/monthday.html, spec/time.html, spec/yearmonth.html
This adds a valueOf() method to Absolute, Date, DateTime, Duration,
MonthDay, Time, and YearMonth, which throws a TypeError. This is in
order to prevent spurious comparisons using <, <=, >, and >= from
working.
Closes: #517
=> Add throwing valueOf() to Temporal types

docs/absolute.md, docs/date.md, docs/datetime.md, docs/timezone.md, docs/yearmonth.md
This is to remove any potential confusion between overflowing the range
of a Temporal type and hitting an invalid time during a daylight saving
transition.
Closes: #598
=> Clarify what "outside the allowed range" means

docs/monthday.md, docs/yearmonth.md, polyfill/index.d.ts, polyfill/lib/ecmascript.mjs, polyfill/lib/monthday.mjs, polyfill/lib/slots.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/MonthDay/constructor/infinity-throws-rangeerror.js, polyfill/test/MonthDay/constructor/negative-infinity-throws-rangeerror.js, polyfill/test/YearMonth/constructor/infinity-throws-rangeerror.js, polyfill/test/YearMonth/constructor/negative-infinity-throws-rangeerror.js, polyfill/test/monthday.mjs, polyfill/test/yearmonth.mjs, spec/monthday.html, spec/yearmonth.html
Temporal.YearMonth gets a RefISODay internal slot and Temporal.MonthDay
gets a RefISOYear internal slot, as discussed in #391. This will be
required for calendar support.
=> RefISOYear and RefISODay internal slots

docs/README.md, docs/calendar.md, polyfill/index.d.ts, polyfill/lib/calendar.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/slots.mjs, polyfill/lib/temporal.mjs, polyfill/test/exports.mjs
All of the methods throw "not implemented". Calendar objects are not yet
used anywhere within Temporal in this commit, but we go ahead and write
the documentation.
=> Add stub Temporal.Calendar and documentation

polyfill/index.d.ts
Some of the `options` parameters on `Duration`, `YearMonth`, and `Calendar` were accidentally marked as required. This PR changes them to optional parameters to match the docs.
=> Ensure all TS types have optional `options` params

polyfill/lib/ecmascript.mjs, polyfill/lib/timezone.mjs, polyfill/test/ecmascript.mjs, spec/abstractops.html, spec/timezone.html
Spec changes are present where they are straightforward, but I haven't concentrated on writing a complete spec for these changes. since the time zone spec was already not complete yet anyway.
According to the time zone draft, custom time zones have to implement three methods: `getOffsetNanosecondsFor`, `getPossibleAbsolutesFor`, and `getTransitions`. All other methods of Temporal.TimeZone should be implemented in terms of these three, resulting in observable calls.
With this code, all the pieces are in place now for custom time zones. This will be followed shortly by a "phase 3" pull request which adds tests proving that custom time zones work (and will need to remove some brand checks and fix a few other things.)
=> Custom time zones, phase 2

polyfill/lib/absolute.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/absolute.mjs, polyfill/test/datetime.mjs, spec/absolute.html, spec/datetime.html
Fixes #648.  This PR updates the polyfill and the spec to match the docs, which say that the time zone parameter for `DateTime.prototype.inTimeZone` and `Absolute.prototype.inTimeZone` should be required.
Given that the meaning of an omitted time zone parameter (UTC?  local time zone?) is not clear without reading the docs, it seems wise to require the user to explicitly provide a time zone when converting between time zones.
Also, given that a design goal of Temporal is to remove ambiguity (especially including around time zones), enforcing an explicit time zone choice seems to support that goal.
=> Make time zone parameter required `inTimeZone` methods

docs/absolute.md, docs/datetime.md, docs/now.md, docs/timezone-draft.md, docs/timezone.md, polyfill/index.d.ts, polyfill/lib/absolute.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/now.mjs, polyfill/lib/timezone.mjs, polyfill/test/all.mjs, polyfill/test/ecmascript.mjs, polyfill/test/timezone.mjs, polyfill/test/usertimezone.mjs
Stacked on top of #620, for the time being, and marked as a draft until that is merged. This is the rest of the support needed for custom time zones. Adds tests to make sure that passing in a subclass of Temporal.TimeZone and a plain object with the required methods both work.
=> Custom time zones, phase 3

polyfill/index.d.ts
This PR fixes two problems in the latest .d.ts's calendar types: 
* Make `options` required in `Calendar`/`CalendarProtocol` methods
because you can't put a non-optional `constructor` param after an
optional param.
* Added required `'years' | 'months' | 'weeks' | 'days'` generic type
parameter to `Calendar`/`CalendarProtocol` use of `DifferenceOptions`
Q: are `'years' | 'months' | 'weeks' | 'days'` the correct valid options?  The `Calendar` docs say only `'years' | 'months' | 'days'` but I assumed that the docs are out of date.
=> Fix calendar-related errors in index.d.ts

package-lock.json, package.json
To prevent index.d.ts type errors like #670 from getting into CI builds, this PR adds TSC in "no emit" mode as part of the lint step that's run in CI for every PR. "No emit" means that it will report errors but won't actually compile anything, so it's super-fast-- only a few hundred msecs.
We already had all the needed TS and lint dependencies, but while I was in the neighborhood I bumped all lint-related dev dependencies except prettier 2.0 because it adds rules that break on a few cookbook examples and I didn't want to scope-creep this PR too much.
Fixes #672.
=> Enhance index.d.ts type-checking with TSC no-emit in lint step 

package.json, polyfill/index.d.ts
This PR updates TS types to fix a few minor issues with the initial calendar types:
- change type of `era` from `unknown` to `string | undefined`
- consistent ordering of `CalendarProtocol | string`
- change `Calendar.from` to accept `CalendarProtocol | string`
- add missing calendar param to `TimeZoneProtocol.getDateTimeFor`
UPDATE:  
- adds TS strict mode to the lint step
- fixes calendar-related types that were broken in strict mode
- adds `DurationFields` and `TimeFields` types for consistency with `*Fields` types that include a calendar.
- Convert protocols from TS types to TS interfaces
- Export protocols (for re-use) but don't export `*Fields` types
=> Fix minor calendar issues with TS types

docs/absolute.md, docs/calendar.md, docs/cookbook/futureDateForm.js, docs/cookbook/getElapsedDurationSinceInstant.mjs, docs/cookbook/getTripDurationInHrMinSec.mjs, docs/date.md, docs/datetime.md, docs/time.md, docs/yearmonth.md, polyfill/lib/absolute.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/time.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/absolute.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/time.mjs, polyfill/test/yearmonth.mjs, spec/absolute.html, spec/date.html, spec/datetime.html, spec/time.html, spec/yearmonth.html
This PR:
a) Changes `difference()` to throw if `other` is larger than `this`, which prevents users from accidentally treating invalid negative differences as valid positive differences. Fixes #663.  
b) Because `difference()` is now unidirectional, it doesn't make sense to restrict `Time.prototype.difference` to 12 hours max. Fixes #597.  Ideally (a) and (b) would be separate PRs, but the implementation was hard to split so I combined into one PR.
Although (a) will likely be considered non-ideal ergonomics, the exception will likely be helpful to generate feedback from polyfill early adopters about what they want the behavior to be and what they think is the best long-term option, e.g.:
- option 1 - previous behavior: `difference()` returns an absolute value
- option 2 - behavior in this …
=> Throw if `difference()` is out-of-order & stop limiting `Time.prototype.difference` to 12 hours

docs/cookbook/getInstantOfNearestOffsetTransitionToInstant.mjs, docs/cookbook/getInstantWithLocalTimeInZone.mjs, docs/now.md, docs/timezone-draft.md, docs/timezone.md, polyfill/index.d.ts, polyfill/lib/ecmascript.mjs, polyfill/lib/timezone.mjs, polyfill/test/timezone.mjs, polyfill/test/usertimezone.mjs, spec/timezone.html
Replaces `TimeZone.prototype.getTransitions()` with `getPreviousTransition` and `getNextTransition` methods.  Goals of this PR: 
* Support use cases that require looking backwards in time, e.g. "was there a transition last weekend?"
* Simplify what will almost certainly be the most common use case: finding only one next/prev transition. Although actual production use will be more sophisticated than our samples, this PR reduces code (by removing calls to `.next()`, `.value`, and `.done`) in existing cookbook entries, in existing tests (except the one test specifically for array iteration), and in sample code in the docs.
Some issues needing feedback: 
* Should UTC get a fast-path special case (for both next and previous) given that it will be a common time zone used and we know it will …
=> TimeZone `getTransitions` -> `getNextTransition` & `getPreviousTransition`

polyfill/lib/calendar.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/monthday.mjs, polyfill/lib/yearmonth.mjs
This moves the registry of built-in calendars into the calendar file, so
that there is no longer a circular dependency between calendar.mjs and
ecmascript.mjs.
Closes: #674
=> Fix calendar circular dependency

spec/absolute.html, spec/abstractops.html, spec/date.html, spec/datetime.html, spec/duration.html, spec/intl.html, spec/monthday.html, spec/time.html, spec/timezone.html, spec/yearmonth.html
This is the result of running ecmarkup --lint-spec on the Temporal spec.
I have not integrated this into the build process yet because it
requires some bug fixes in ecmarkup to work correctly.
=> Lint fixes in spec

polyfill/lib/ecmascript.mjs
regex.mjs was being imported twice: once as `PARSE` and again as `REGEX`.  With this PR it's now just `PARSE`.
=> Stop importing regex.mjs twice in ecmascript.mjs

polyfill/ci_test.sh, polyfill/test/transform.test262.js
Fixes #687 which prevented Test262 tests from running in my MacOS/Node14 environment.
- if MacOS, use `sysctl -n hw.logicalcpu` instead of `nproc` in `ci_test.sh`
- defend against undefined `globalThis.__coverage__`
=> Fix Test262 on MacOS / Node14

polyfill/test/resolve.cookbook.mjs
This PR removes line breaks from the extra code added by the cookbook test resolver.
Without this change, IDE debugger breakpoints will hit the wrong lines because the sourcemap line numbers won't match the runtime line numbers.   This makes cookbook tests much harder to run under an IDE debugger.
=> Fix line numbering for debugging cookbook

.eslintrc.yml, .gitignore, docs/cookbook/localTimeForFutureEvents.mjs, docs/package.json, docs/rollup.config.ejs, package-lock.json, package.json, polyfill/lib/ecmascript.mjs, polyfill/lib/intl.mjs, polyfill/lib/intrinsicclass.mjs, polyfill/package.json, polyfill/rollup.config.js, polyfill/test/usercalendar.mjs, polyfill/test/usertimezone.mjs
While troubleshooting #687, I ended up updating all build dependencies except demitasse. Updating didn't fix the problem but all builds and tests still worked fine, so while I was in the neighborhood I figured I'd turn that work into a PR instead of rolling back. Here's what's in it:
* prettier->v2 - required a few minor spacing/line-break changes, but otherwise no changes
* rollup->v2 - Sped up builds by a few seconds (yay!). Also replaced deprecated rollup plugins. 
* replaced uglify with terser, which had a supported rollup 2.x plugin (and can minify ES6 code if we want to do that later) while uglify plugin didn't seem to be rollup 2.x-friendly
* added `--cache` option to lint step, which makes linting ~5x faster after the first run
* moved all dev dependencies into dev section in …
=> Update build dependencies

docs/ambiguity.md, docs/cookbook.md, docs/cookbook/getInstantWithLocalTimeInZone.mjs, docs/datetime.md, docs/timezone.md, polyfill/index.d.ts, polyfill/lib/ecmascript.mjs, polyfill/lib/intl.mjs, polyfill/lib/timezone.mjs, polyfill/test/datetime.mjs, polyfill/test/intl.mjs, polyfill/test/timezone.mjs, spec/abstractops.html, spec/timezone.html
Adds a new `disambiguation: 'compatible'` option to `TimeZone.prototype.getAbsoluteFor` and `DateTime.prototype.inTimeZone`, and makes this new option the default.  Fixes #318.
This new option acts like `'later'` for "Spring Forward" DST transitions, and acts like `'earlier'` for "Fall Back" DST transitions. This behavior matches the disambiguation behavior of legacy `Date`, as well as libraries like moment.js, Luxon, and date-fns that are built on top of legacy `Date`.  It also matches RFC 5545 (iCalendar) required behavior.
To maximize compatibility between Temporal and existing code and to help interop when interoperating with other apps and services, this new 'compatible' option will be the default.
Existing options `'later'`, `'earlier'`, and `'reject'` are still available and their …
=> Add disambiguation: 'compatible' option to TimeZone.prototype.getAbsoluteFor and DateTime.prototype.inTimeZone 

polyfill/index.d.ts
#649 made the time zone parameter required in `inTimeZone` methods, but in that PR I forgot to update the `Absolute.prototype.inTimeZone` TS declaration. (The declaration of `DateTime.prototype.inTimeZone` was already OK.)
=> Correct the TS declaration of `Absolute.prototype.inTimeZone` to make `tzLike` required

polyfill/.gitignore, polyfill/.npmrc, polyfill/package.json, polyfill/rollup.config.js
Summary:
This pull request as intention of adding an extra output "umd". That way i can easily use it with script tag an consume it globally.
Main reason : 
Prototype and Play with proposal-temporal from cdn without having to use import. same as the cookbook is doing with https://tc39.es/proposal-temporal/docs/playground.js
=> feat: include UMD as output target

.eslintrc.yml, docs/head.html.part, docs/package.json, docs/rollup.config.ejs, docs/rollup.config.js, package.json, polyfill/lib/absolute.mjs, polyfill/lib/calendar.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/duration.mjs, polyfill/lib/initialise.js, polyfill/lib/intrinsicclass.mjs, polyfill/lib/monthday.mjs, polyfill/lib/time.mjs, polyfill/lib/timezone.mjs, polyfill/lib/yearmonth.mjs, polyfill/package.json, polyfill/rollup.config.js
This adds a build-time debug mode, debug-only util.inspect formatters for the Node.js REPL for Temporal objects, a debug-only `_repr_` own data property that will improve devtools output in the various browsers, and a custom formatter for Chrome devtools (unfortunately only works if you enable an obscure setting.)
This is how it looks now, both expanded and unexpanded:
**Chromium** (normal)
**Chromium** (with obscure setting enabled)
**Firefox** (particularly dire as there is no way to change that `Object { … }`, unless you click the expander)
**Safari**
Closes: #643
=> Improved debug output

docs/cookbook/meetingPlanner.js, docs/cookbook/storageTank.js, docs/date.md, docs/datetime.md, polyfill/test/date.mjs, polyfill/test/datetime.mjs
The cases where it could make sense to pass a Temporal object:
- Date.with(YearMonth)
- Date.with(MonthDay)
- DateTime.with(Time)
- DateTime.with(Date)
- DateTime.with(YearMonth)
- DateTime.with(MonthDay)
Closes: #713
=> Clarify that .with() methods can accept Temporal objects

docs/cookbook/storageTank.js
Shorten the storageTank.js cookbook example slightly. Nothing major, I
just spotted this while working on another PR.
=> docs: shorten the storageTank coobook example

polyfill/lib/time.mjs, polyfill/test/time.mjs
- Fixes #735.
- Adds tests for `Time.from` when the source is `Time` or `DateTime`.
- Also corrects an inaccurate comment.
=> Fix `Time.from` when param is another `Time`

polyfill/lib/intl.mjs, polyfill/test/intl.mjs
If given, 'weekday' should be included for types where the day of the
week is defined, and excluded from types that don't have that concept.
Closes: #733
=> Fix localized weekdays

polyfill/ci_test.sh, polyfill/lib/ecmascript.mjs, polyfill/test/datetime.mjs, polyfill/test/timezone.mjs
Found by attempting to run the date-fns test suite with Temporal
=> Fix year zero leap day

docs/duration.md
modified "const" to "let" since the code sample would fail in the reassignment on the next line
=> Correct minor problem with script examples which results in an error when run

docs/buildDocs.js
For a bit of background on this PR please see this issue: #754 
Essentially a call to `slugger.slug` in the `buildDocs.js` file was causing marked's slugger to increment an internal accumulator and subsequently suffix our headings with a `-1` even though there was only one occurrence of them. This meant items in our TOC were referencing for example `frequently-asked-questions`, but marked was outputting the header with an id set to `frequently-asked-questions-1`.
This PR reverses the accumulator action erroneously caused.
=> Fix docs navigation

docs/cookbook.md, docs/cookbook/getCurrentDate.mjs
As reported in the issue, the Stack Overflow question was about getting
the current date, not the current date and time. Change our example
accordingly, but also note how to get the date and time as well.
Closes: #752
=> Clarify current date cookbook example

polyfill/README.md, polyfill/lib/ecmascript.mjs, polyfill/lib/intl.mjs
The Intl object is already patched when you require() or import the
module. In addition, if you do it from the Node.js REPL, then the Intl
binding will end up in the temporal dead zone.
Closes: #753
=> Don't need to import Intl from proposal-temporal module

CHANGELOG.md, polyfill/package.json
- Bug fixes.
- For Temporal.Date, Temporal.DateTime, and Temporal.YearMonth, now
disambiguation only applies to when the fields are internally
inconsistent. If the value is outside of the representable range, a
RangeError is always thrown.
- API renames:
- Temporal.Absolute.inTimeZone -> Temporal.Absolute.toDateTime
- Temporal.Date.getMonthDay -> Temporal.Date.toMonthDay
- Temporal.Date.getYearMonth -> Temporal.Date.toYearMonth
- Temporal.Date.withTime -> Temporal.Date.toDateTime
- Temporal.DateTime.getDate -> Temporal.DateTime.toDate
- Temporal.DateTime.getMonthDay -> Temporal.DateTime.toMonthDay
- Temporal.DateTime.getTime -> Temporal.DateTime.toTime
- Temporal.DateTime.getYearMonth -> Temporal.DateTime.toYearMonth
- Temporal.DateTime.inTimeZone -> Temporal.DateTime.toAbsolute
- …
=> Version bump

docs/buildDocs.js, docs/cookbook/getInstantWithLocalTimeInZone.mjs, docs/cookbook/getSortedLocalDateTimes.mjs, docs/cookbook/sortAbsoluteInstants.mjs, docs/package.json
I found one more instance while working on #765.
Also, on a clean clone, the `npm run build:docs` command errors because of missing target directory structure with
```sh
[Error: ENOENT: no such file or directory, open 'PROJECT_ROOT/out/docs/README.html'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '$PROJECT_ROOT/out/docs/README.html'
}
```
(multiple places, I replaced the actual value with `$PROJECT_ROOT` here).
=> Document all default values in JSDoc. Fixes #765

polyfill/package.json
The polyfill had the `main` and `browser` fields containing absolute file paths, when [they should be relative](https://docs.npmjs.com/configuring-npm/package-json#main). This caused CommonJS `require()` to fail in NodeJS when following the usage instructions in the README:
```sh
$ npm init -y
$ npm install --save proposal-temporal
$ node
Welcome to Node.js v14.0.0.
Type ".help" for more information.
> const { Temporal } = require('proposal-temporal')
Uncaught:
Error: Cannot find module '/dist/index.js'. Please verify that the package.json has a valid "main" entry
at tryPackage (internal/modules/cjs/loader.js:323:19)
at Function.Module._findPath (internal/modules/cjs/loader.js:680:18)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
at Function.Module._load …
```
=> Fix file paths to be relative in polyfill package.json

.editorConfig
A small tweak to make sure the various formatting tools don't conflict.
=> Fix EditorConfig indent size to agree with Prettier

polyfill/test/intl.mjs
When I ran the polyfill test suite on my local machine I got one test failure. Since the tests pass in CI I figured it was a time zone thing (it often is). My computer runs on `Australia/Sydney` time, so I'm used to tests that fail by complaining about being a day ahead 😉 .
This was the failure:
```
Intl
absolute.toLocaleString()
☑ (1976-11-18T14:23:30Z).toLocaleString('en-US', { timeZone: 'Europe/Vienna' })
☑ (1976-11-18T14:23:30Z).toLocaleString('de-AT', { timeZone: 'Europe/Vienna' })
☒ uses only the options in resolvedOptions
assertion: Expected values to be strictly equal:
+ actual - expected
+ 'Friday'
- 'Thursday'
expected: 'Thursday'
actual: 'Friday'
```
This PR tweaks the test in question to always format using a specific time zone. I also fixed up some test descriptions that said …
=> Fix Intl test failure when running in other time zones

docs/cookbook.md
Temporal.Absolute can't be rounded to a certain field because it doesn't
have any fields.
Closes: #800
=> Clarify that rounding cookbook example doesn't apply to Absolute

polyfill/lib/absolute.mjs, polyfill/test/absolute.mjs
Without 'weeks' listed in the unsupported units, adding a number of
weeks to a Temporal.Absolute would just return a new object with the
same timestamp. Instead, disallow arithmetic with weeks, as they are
calendar-dependent.
=> Disallow Absolute arithmetic with weeks

polyfill/lib/ecmascript.mjs, polyfill/lib/regex.mjs, polyfill/test/absolute.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/duration.mjs, polyfill/test/monthday.mjs, polyfill/test/regex.mjs, polyfill/test/time.mjs, polyfill/test/yearmonth.mjs
Minor bugs that I have run into while working on negative durations.
=> Duration fixes

polyfill/lib/ecmascript.mjs, polyfill/test/ecmascript.mjs
It puts the result in an array (though the order is irrelevant), only for the
single consumer to immediately  reduce that array to an object.
=> Simplify ES.GetFormatterParts().

docs/calendar-draft.md, docs/calendar.md, polyfill/index.d.ts, polyfill/lib/calendar.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/yearmonth.mjs
Calendar.plus -> Calendar.datePlus
Calendar.minus -> Calendar.dateMinus
Calendar.difference -> Calendar.dateDifference
Rename some methods to have `date` in the name so that if there are use
cases for a time-based calendar then later timePlus, timeMinus, and
timeDifference can be added.
Closes: #522
=> Ensure future proof for time-based calendars

docs/buildDocs.js, docs/localdatetime-draft.md
I intend to eventually adapt this into the documentation for
LocalDateTime, but given the draft status of the API this seems more
appropriate.
=> Add explainer for LocalDateTime

polyfill/test/duration.mjs
We already don't support fractional duration units other than seconds,
but at one point they were silently ignored. Add a test to make sure
they throw instead.
Closes: #788
=> Test to make sure fractional durations throw

polyfill/lib/ecmascript.mjs, polyfill/lib/timezone.mjs, polyfill/test/TimeZone/prototype/getDateTimeFor/getOffsetNanosecondsFor-invalid-type.js, polyfill/test/TimeZone/prototype/getDateTimeFor/getOffsetNanosecondsFor-invalid-value.js, polyfill/test/TimeZone/prototype/getOffsetStringFor/getOffsetNanosecondsFor-invalid-type.js, polyfill/test/TimeZone/prototype/getOffsetStringFor/getOffsetNanosecondsFor-invalid-value.js
Also add tests for the result checks.
=> Consolidate getOffsetNanosecondsFor calls into ES.GetOffsetNanosecondsFor().

polyfill/lib/ecmascript.mjs, polyfill/lib/regex.mjs, polyfill/lib/timezone.mjs, polyfill/test/absolute.mjs, polyfill/test/datetime.mjs, polyfill/test/regex.mjs, polyfill/test/time.mjs, polyfill/test/timezone.mjs, polyfill/test/validStrings.mjs, polyfill/test/yearmonth.mjs, spec/abstractops.html
Wherever a sign character is needed (in 6-digit extended years and in
time zone offsets), also accept the Unicode minus sign as well as the
normal ASCII + and -.
Closes: #814
=> Allow Unicode minus sign (U+2212) in ISO 8601 strings

polyfill/lib/index.mjs, polyfill/lib/shim.mjs, polyfill/rollup.config.js
In order to avoid breaking the web when Temporal is shipped, don't
polyfill onto the global object. We don't want any `if (typeof Temporal
=== undefined)` checks in the wild until browsers actually start
shipping Temporal.
We do still need it on the global object for the browser playground and
the test262 tests, so we now have two separate entry points to the
library: index.mjs and polyfill.mjs.
Closes: #778
=> Don't polyfill Temporal and Intl onto the global object

docs/cookbook/getElapsedDurationSinceInstant.mjs, docs/duration.md
Make a note of this in the documentation and the cookbook.
Closes: #760
=> Note that Duration.toLocaleString requires Intl.DurationFormat

docs/absolute.md, docs/datetime.md, docs/time.md, polyfill/lib/calendar.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/absolute.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/time.mjs, polyfill/test/yearmonth.mjs, spec/abstractops.html, spec/date.html, spec/datetime.html, spec/duration.html, spec/yearmonth.html
In Absolute.difference, DateTime.difference, and Time.difference, now
'milliseconds', 'microseconds', and 'nanoseconds' are valid values for
the largestUnit option.
Closes: #805
=> Allow sub-second largestUnit values

docs/absolute.md, docs/datetime.md
This PR slightly extends the Absolute and DateTime documentation added in #850 to clarify the overflow risk of nanoseconds is only 104 days. Also it includes a sample for each type illustrating the overflow case.
=> document nanoseconds duration limit of 104 days

docs/date.md, docs/datetime.md, docs/yearmonth.md, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/intl.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/intl.mjs, polyfill/test/yearmonth.mjs
In the difference() methods of Date, DateTime, and YearMonth, check if
the calendars of the two operands are different. If they are different, then throw.
This is because the result of a difference between two dates in
different calendars would be ambiguous as to which calendar the
resulting duration would be expressed in.
Makes the corresponding change for Intl.DateTimeFormat.formatRange() and
formatRangeToParts() and adds a test for that.
Closes: #587
=> Disallow difference() between two different calendars

docs/cookbook/storageTank.js, docs/date.md, polyfill/lib/date.mjs, polyfill/test/date.mjs, spec/date.html
This arises from a need identified in feedback to have a more ergonomic
way to get a Temporal.DateTime with midnight on a certain date.
Closes: #737
=> Default Date.toDateTime() argument to midnight

docs/duration.md, docs/iso-string-ext.md
These are allowed extensions in ISO 8601-2, so instead of noting that
they are not valid ISO, note that they are extensions. Remove them from
our custom ISO extensions page, since they are not custom to Temporal
anymore.
=> Remove notes about weeks combined with other units in Duration strings

polyfill/index.d.ts
#859 forgot to update the TS type declarations to remove `days` as a valid value for `largestUnit` in `Absolute.prototype.difference`.
=> Remove days as allowed unit in Absolute.difference TS type

polyfill/lib/calendar.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/time.mjs, spec/date.html, spec/datetime.html, spec/time.html, spec/yearmonth.html
The abstract operations in the spec should have all the fields split out
and passed as number values, so that the abstract operations don't try to
read the internal slots. The public APIs should do the brand checks and
read the internal slots.
Closes: #864
=> Remove brand checks from CompareTemporalDate and CompareTemporalTime

docs/absolute.md, docs/cookbook.md, docs/cookbook/roundDownToWholeHours.mjs, docs/cookbook/roundToNearestMonth.mjs, docs/datetime.md, docs/time.md, polyfill/index.d.ts, polyfill/lib/absolute.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/time.mjs, polyfill/test/absolute.mjs, polyfill/test/datetime.mjs, polyfill/test/time.mjs, spec/absolute.html, spec/abstractops.html, spec/datetime.html, spec/time.html
This is Part 1 of the implementation of rounding. It encompasses the `round()` methods of Absolute, Date, and DateTime.
(Part 2 will add rounding to the `difference()` methods of those types, and Part 3 will add a `round()` method to Duration.)
See: #827
=> Rounding, Part 1

docs/absolute.md
I think that's all there is to say about this one 😃
=> [docs] Fixes typo in example output of Absolute.toDateTime()

docs/absolute.md, docs/datetime.md, docs/time.md, polyfill/index.d.ts, polyfill/lib/absolute.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/time.mjs, polyfill/test/absolute.mjs, polyfill/test/datetime.mjs, polyfill/test/time.mjs, spec/absolute.html, spec/abstractops.html, spec/biblio.json, spec/datetime.html, spec/duration.html, spec/time.html
This adds rounding options to Temporal.Absolute.prototype.difference, Temporal.DateTime.prototype.difference, and Temporal.Time.prototype.difference.
See: #827.
=> Rounding, Part 2

polyfill/index.d.ts
Minor updates to TS types: 
* Difference options must be optional, or will break TS code
* Added JSDoc for new types and options
=> Optionality & JSDoc fixes for rounding TS types

docs/package.json, package-lock.json, package.json, polyfill/lib/ecmascript.mjs, polyfill/package.json, polyfill/test/datetime.mjs, polyfill/test/duration.mjs, polyfill/test/time.mjs
This PR fixes #949 by: 
* Updating es-abstract to pick up a fix to https://github.com/ljharb/es-abstract/issues/116 which was the root cause of #949 
* Changing polyfill/lib/ecmascript.mjs to use the ES2020 imports (previously it was using ES2019 imports)
* Adding tests to verify that #949 is indeed fixed
While I was in the neighborhood, I also bumped all dev dependencies (except demitasse) that were outdated.
=> Switch to ES2020 imports in es-abstract to fix #949

docs/monthday.md, docs/yearmonth.md, polyfill/lib/intl.mjs, polyfill/test/intl.mjs, spec/intl.html
This ensures that the calendar of a Temporal object on which the
toLocaleString() method is called, must match the calendar of the locale
which is passed to toLocaleString().
In the case of DateTime and Date, if the object's calendar is the ISO
calendar, then the locale's calendar overrides it. In the case of
YearMonth and MonthDay, the calendars must match exactly, because there's
no way to implicitly convert MonthDay and YearMonth between calendars.
Closes: #262
=> Calendar must be equal to locale calendar in toLocaleString()

docs/datetime.md
=> Minor docs clarification about DateTime.toLocaleString(..., {timeZone})

docs/calendar-draft.md, docs/monthday.md, docs/yearmonth.md, polyfill/index.d.ts, polyfill/lib/calendar.mjs, polyfill/lib/date.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/intl.mjs, polyfill/lib/monthday.mjs, polyfill/lib/slots.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/MonthDay/prototype/getISOFields/subclass.js, polyfill/test/YearMonth/prototype/getISOFields/subclass.js, polyfill/test/monthday.mjs, polyfill/test/usercalendar.mjs, polyfill/test/yearmonth.mjs, spec/monthday.html, spec/yearmonth.html
This renames YearMonth's [[RefISODay]] slot to [[ISODay]], MonthDay's
[[RefISOYear]] slot to [[ISOYear]], changes the `refISOYear` property on
the returned object from MonthDay.getISOFields() to `isoYear`, and changes
the `refISODay` property on the returned object from
YearMonth.getISOFields() to `isoDay`.
Fixes a few inconsistencies with the capitalization of ISO, and also adds
extra slots to Temporal.Date, YearMonth, and MonthDay for brand checks
(since they all otherwise have the same slots now.)
Closes: #896
=> Rename RefISODay and RefISOYear slots

spec/date.html, spec/datetime.html, spec/duration.html, spec/instant.html, spec/monthday.html, spec/time.html, spec/timezone.html, spec/yearmonth.html
This adds a section to each of the Temporal types with details about the
internal slots. It also makes the existing Temporal.Date section conform
to the way that many such sections are written in the ECMA-262 spec.
I've left the existing sections in Temporal.Calendar and
Temporal.ISO8601Calendar as they are, since it's not yet clear where we're
going with the subclassing scheme there.
Closes: #898
=> Add "properties of instances" sections to spec

polyfill/lib/calendar.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/instant.mjs, polyfill/lib/monthday.mjs, polyfill/lib/time.mjs, polyfill/lib/timezone.mjs, polyfill/lib/yearmonth.mjs, spec/abstractops.html, spec/date.html, spec/datetime.html, spec/duration.html, spec/instant.html, spec/monthday.html, spec/time.html, spec/timezone.html, spec/yearmonth.html
Previously, the abstract operation NormalizeOptionsObject was called more
than once on the same options object. This was not observable, but this
change makes the spec cleaner.
Closes: #899
=> Move NormalizeOptionsObject outside of other abstract operations

docs/ambiguity.md
This PR was split out of #922 to make reviewing #922 easier.
* Integrate LocalDateTime docs
* Integrate docs for TZ-vs-offset ambiguity
* Switch samples to use LDT
* Added generalized conceptual sections about time zone concepts
=> Update ambiguity docs page

docs/balancing.md, docs/date.md, docs/datetime.md, docs/duration.md, docs/instant.md, docs/localdatetime.md, docs/timezone.md
In general, we want to encourage using from() instead of the constructors
directly, which are considered more low-level. This replaces direct usage
of the constructors with from() in the docs, except in the code examples
of the constructors themselves.
Closes: #914
=> Avoid using Temporal constructors in documentation examples

docs/README.md, docs/ambiguity.md, docs/date.md, docs/datetime.md, docs/instant.md, docs/now.md, docs/object-model.svg, docs/time.md, docs/timezone.md, docs/zoneddatetime.md
This PR renames LocalDateTime => ZonedDateTime in the docs.  While in the neighborhood, I also:
* added docs for `epochXxx` properties on ZDT (#932)
* renamed timeZoneOffsetXxx properties to offsetXxx. (#935)
I *didn't* rename plus/minus in this PR because I didn't want to conflict with @ptomato's PR in #975.
=> Rename LocalDateTime docs to ZonedDateTime

docs/cookbook/getTimeZoneObjectFromIanaName.mjs, docs/timezone-draft.md, docs/timezone.md, docs/zoneddatetime.md, polyfill/lib/timezone.mjs, polyfill/test/TimeZone/constructor/from/argument-valid.js, polyfill/test/TimeZone/prototype/id/no-toString.js, polyfill/test/TimeZone/prototype/id/plain-custom-timezone.js, polyfill/test/regex.mjs, polyfill/test/timezone.mjs, polyfill/test/usertimezone.mjs, spec/timezone.html
This is in order to be consistent with Calendar.id.
Closes: #920
=> Rename TimeZone.name to TimeZone.id

docs/calendar.md, docs/date.md, docs/datetime.md, docs/duration.md, docs/instant.md, docs/time.md, docs/yearmonth.md, docs/zoneddatetime.md, polyfill/index.d.ts, polyfill/lib/datetime.mjs, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/instant.mjs, polyfill/lib/time.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/duration.mjs, polyfill/test/instant.mjs, polyfill/test/time.mjs, polyfill/test/yearmonth.mjs, spec/abstractops.html, spec/datetime.html, spec/duration.html, spec/instant.html, spec/time.html
~~This doesn't yet implement Duration rounding, but I was starting to accumulate enough commits preparing for it that I thought it'd be best to start getting them reviewed.~~
This implements Duration.round(). Another pull request will still follow for rounding options in add() and subtract(), and the new compare() method.
To review this, I would recommend looking at the tests to see if you find any of the expected results surprising, and if there are any edge cases that are not tested but should be. Then I'd recommend looking at the algorithm in either the spec or the polyfill. (They are as alike as I could make them.)
See: #856
=> Duration rounding part 3

docs/duration.md, polyfill/lib/duration.mjs, polyfill/test/duration.mjs, spec/duration.html
A convenience method that can be used instead of the less discoverable
duration.sign === 0.
Closes: #924
=> Add Duration.isZero

docs/instant.md, polyfill/lib/instant.mjs, polyfill/test/instant.mjs, spec/instant.html
The rationale for not allowing this was that the starting point of the
hour was not well-defined, due to Instant not having a time zone. However,
this applies to minutes as well, and so hours and minutes should either be
both allowed or both disallowed. We decide to allow them for convenience.
See: #908
=> Allow rounding to hours in Instant.round()

docs/date.md, docs/yearmonth.md, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/date.mjs, polyfill/test/yearmonth.mjs, spec/date.html, spec/yearmonth.html
=> Add rounding to Date.difference and YearMonth.difference

README.md
Tomorrow is the beginning of mid-October, so to clarify, add a link to the
milestone with open 'stable proposal' issues.
=> Note status in README

polyfill/lib/calendar.mjs, polyfill/lib/date.mjs, polyfill/lib/ecmascript.mjs, spec/abstractops.html, spec/biblio.json, spec/calendar.html, spec/date.html
=> spec: cleanup and finalize spec text for date

polyfill/index.d.ts
I had forgotten to update the TypeScript bindings to include some of the
recently merged features.
=> Fix TypeScript bindings

docs/README.md, docs/cookbook.md, docs/cookbook/all.mjs, docs/cookbook/calculateDailyOccurrence.mjs, docs/cookbook/getBusinessOpenStateText.mjs, docs/cookbook/getInstantBeforeOldRecord.mjs, docs/cookbook/getInstantOfNearestOffsetTransitionToInstant.mjs, docs/cookbook/getInstantWithLocalTimeInZone.mjs, docs/cookbook/getParseableZonedStringAtInstant.mjs, docs/cookbook/getParseableZonedStringWithLocalTimeInOtherZone.mjs, docs/cookbook/getUtcOffsetDifferenceSecondsAtInstant.mjs, docs/cookbook/sortExactTimeStrings.mjs, docs/datetime.md, docs/instant.md, docs/now.md, docs/timezone-draft.md, docs/timezone.md, docs/zoneddatetime.md
=> Use 'exact time' consistently in documentation

docs/duration.md, polyfill/index.d.ts, polyfill/lib/duration.mjs, polyfill/test/Duration/constructor/from/argument-existing-object.js, polyfill/test/Duration/constructor/from/infinity-throws-rangeerror.js, polyfill/test/Duration/constructor/from/negative-inifinity-throws-rangeerror.js, polyfill/test/Duration/constructor/from/subclass-invalid-arg.js, polyfill/test/Duration/prototype/with/infinity-throws-rangeerror.js, polyfill/test/Duration/prototype/with/negative-infinity-throws-rangeerror.js, polyfill/test/Duration/prototype/with/subclass-out-of-range.js, polyfill/test/duration.mjs, spec/duration.html
There is now a more complete way to balance in Duration.round(), so remove
the incomplete balancing from Duration.from() and Duration.with(). The way
to balance a duration is now to use round() (or, as an option to add() or
subtract()).
Closes: #974
=> Remove balancing from Duration.from() and Duration.with()

polyfill/index.d.ts, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/monthday.mjs, polyfill/lib/time.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/duration.mjs, polyfill/test/instant.mjs, polyfill/test/monthday.mjs, polyfill/test/time.mjs, polyfill/test/yearmonth.mjs, spec/abstractops.html, spec/duration.html, spec/time.html
For values of largestUnit and smallestUnit options, accept both singular and plural everywhere (except "week"), but describe only the "correct" ones in documentation, and mark the "wrong" ones as deprecated in TypeScript.
For names of properties, accept only the correct ones. Property bags must include at least one correctly-spelled property or throw a TypeError.
Closes: #325
=> Consistent handling of singular and plural field names

polyfill/index.d.ts
This undoes part of 75fcdb519566b71c55e0c718f849abb9ba0204a5 because the
property names in property bags are not supposed to be marked deprecated.
They are just ignored.
Follow up to #325.
=> Revert marking plural properties deprecated in TypeScript

polyfill/test/timezone.mjs
The only way I've found to identify demitasse test failures is to search the output for the word "expected". This PR makes this grepping easier by removing "expected" from the names of tests.
=> Remove "expected" from test names

spec/instant.html
A couple of improvements I made while working on ZonedDateTime spec.
=> Spec improvements

polyfill/lib/ecmascript.mjs, polyfill/lib/regex.mjs, polyfill/test/regex.mjs, polyfill/test/validStrings.mjs, spec/abstractops.html
=> Allow ISO strings with bracketed time zone and no offset

docs/date.md, docs/datetime.md, docs/time.md, docs/zoneddatetime.md, polyfill/index.d.ts, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/regex.mjs, polyfill/lib/time.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/time.mjs, spec/abstractops.html, spec/date.html, spec/datetime.html, spec/time.html
=> Accept strings in with() methods

spec/intl.html
Handle Instants properly in PartitionDateTimePattern (convert to
DateTime and move forward from there).
Fixes: https://github.com/tc39/proposal-temporal/issues/456
/cc @Ms2ger @sffc 
There's a bunch of bigger issues in PartitionDateTimePattern but I suppose we can solve them one at a time?
=> spec: fix instant handling in PartitionDateTimePattern

polyfill/lib/ecmascript.mjs, polyfill/lib/regex.mjs, polyfill/lib/timezone.mjs, polyfill/test/TimeZone/prototype/getOffsetStringFor/custom-timezone.js, polyfill/test/instant.mjs, polyfill/test/regex.mjs, polyfill/test/timezone.mjs, polyfill/test/usertimezone.mjs, polyfill/test/validStrings.mjs, spec/abstractops.html, spec/timezone.html
=> Sub-minute time zone offsets

spec/intl.html
/cc @sffc @ptomato @Ms2ger these should basically be enough to make `PartitionDateTimePattern` work as expected with all types. One thing I was not sure about was if one of YM and MD doesn't have a calendar (perhaps MD?), but it is impossible to tell from the docs.
=> spec: PartitionDateTimePattern improvements

docs/date.md, docs/datetime.md, docs/duration.md, docs/instant.md, docs/time.md, docs/yearmonth.md, docs/zoneddatetime.md, polyfill/index.d.ts
* Clarify roundingMode docs (fixes #1028)
* Consistent order for roundingMode options
* Clarify that `relativeTo` can also accept a Date
* Added JSDoc content to index.d.ts to mirror the docs changes above.
* Added JSDoc content for new xxxISO methods of Temporal.now
* Added JSDoc content for duration rounding options
* Renamed `offsetString` to `offset` in ZonedDateTime docs
* Ran prettier for the first time on duration.md and yearmonth.md, so many whitespace changes, code semicolons, etc. I also added prettier-ignore comments where needed to retain code formatting.
=> Misc documentation and JSDoc updates

docs/calendar-draft.md, docs/calendar.md, polyfill/index.d.ts, polyfill/lib/calendar.mjs, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/monthday.mjs, polyfill/lib/yearmonth.mjs, polyfill/test/usercalendar.mjs, spec/abstractops.html, spec/calendar.html, spec/date.html, spec/datetime.html, spec/monthday.html, spec/yearmonth.html
=> Calendar.fields method

polyfill/lib/ecmascript.mjs, spec/date.html, spec/datetime.html, spec/monthday.html, spec/yearmonth.html
Only the built-in fields (year through nanosecond, and the plural names
for Duration) should be converted to integers. Custom calendar fields
should not have any type conversion performed on them.
Closes: #1045
=> Don't convert custom calendar fields to integers

docs/calendar.md, docs/timezone.md, polyfill/index.d.ts
=> Time zone and calendar protocol best practices

spec/abstractops.html
The set of accepted values for roundingMode is intended to be the same as
whatever is standardized, not necessarily this particular set of rounding
modes and these particular names.
See: #1038
=> Add note about rounding modes

docs/calendar.md, polyfill/index.d.ts, polyfill/lib/calendar.mjs, polyfill/test/calendar.mjs, spec/abstractops.html, spec/isocalendar.html
This also clarifies which Temporal objects are accepted by which Calendar
methods.
Closes: #1030
=> Allow property bags and strings in Calendar methods

spec/date.html, spec/datetime.html, spec/instant.html, spec/temporal.html, spec/time.html, spec/timezone.html, spec/yearmonth.html
This ignores the cases that need to go through the calendar anyway (dateFromFields, etc.).
=> Pass calendars when constructing objects.

polyfill/test/intl.mjs
Tests for `toLocaleString` recently started breaking on my local machine because date formatting on my machine emits an " S" suffix for Japanese calendar dates. Presumably the " S" means "Showa". Anyway, this PR enables tests to pass with (my machine) or without (CI) the suffix.
=> Accept " S" suffix for Japanese Showa era dates to enable tests to pass on my Mac

docs/zoneddatetime.md, polyfill/index.d.ts, spec.html, spec/abstractops.html, spec/intl.html, spec/timezone.html, spec/zoneddatetime.html
This has all the entries for ZonedDateTime, although many of them are marked TODO. Includes a few minor other fixes.
See: #569
=> Partial spec for ZonedDateTime

docs/duration.md, polyfill/index.d.ts, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/duration.mjs, spec/abstractops.html, spec/duration.html
This PR fixes #584 by:
* Adding a new `total()` method on the Duration type
* Updating the `RoundDuration` abstract operation to return a remainder, which is used to calculate the fractional value returned by `total`. Other uses of `RoundDuration` will ignore the remainder.
BTW, this PR encountered problems with `RoundDuration` that I expect will be fixed by the fix to #1059. Therefore, a few of the tests in this PR are failing, but I expect them to pass after #1059's fix lands. See https://github.com/tc39/proposal-temporal/issues/1059#issuecomment-717448093 for more info on the failing tests. 
I'm very new to writing spec text so I assume I made a few mistakes in the spec. 
Questions / Open Issues: 
1. The changes to RoundDuration noted above are only one possible way to solve this …
=> Add Duration.prototype.total method

docs/calendar.md, docs/time.md, polyfill/index.d.ts, polyfill/lib/date.mjs, polyfill/lib/datetime.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/instant.mjs, polyfill/lib/slots.mjs, polyfill/lib/temporal.mjs, polyfill/lib/time.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/all.mjs, polyfill/test/date.mjs, polyfill/test/datetime.mjs, polyfill/test/exports.mjs, polyfill/test/instant.mjs, polyfill/test/time.mjs, polyfill/test/zoneddatetime.mjs, spec/abstractops.html, spec/date.html, spec/datetime.html, spec/instant.html, spec/time.html, spec/zoneddatetime.html
This includes all the "trivial" methods of ZonedDateTime and their tests (spec text already exists), and all the conversion methods from other types to ZonedDateTime, and their tests and specification text.
Unimplemented methods (with, add, subtract, until, since, round, getFields, and anything dealing with DST) throw, for the time being. Some options (offset and overflow in from()) are also not implemented yet.
=> Initial implementation of ZonedDateTime

docs/cookbook/getBusinessOpenStateText.mjs
Berlin was already in DST on 2019-04-07.
=> Fix getBusinessOpenStateText cookbook example.

docs/cookbook/sortExactTimeStrings.mjs, docs/instant.md, polyfill/lib/ecmascript.mjs, polyfill/test/Instant/constructor/from/timezone-custom.js, polyfill/test/Instant/constructor/from/timezone-from-undefined.js, polyfill/test/instant.mjs, polyfill/test/regex.mjs, polyfill/test/validStrings.mjs, spec/abstractops.html, spec/instant.html
When parsing an ISO 8601 string, Temporal.Instant.from should always
use the offset, and ignore the bracketed IANA name, even if the two
disagree.
Closes: #716
=> Make Instant.from always use the offset

docs/object-model.svg
Fixes #1098 by adding fallback fonts for Linux.  It's possible that there still may be some disparity on Linux but it should be less after this PR, and if so we can look at changing the font stack to make it more universal.
To verify this PR, visit https://raw.githubusercontent.com/justingrant/proposal-temporal/4c0b92d26ad4270f38d1d24b27f04d27dff1c3f2/docs/object-model.svg in Firefox on Ubuntu (although probably should repro in any Linux distro). 
Then compare to https://tc39.es/proposal-temporal/docs/object-model.svg, which may look broken.
If the former one looks better than the latter, then at least this PR improves things.
=> Add fallback fonts to object model diagram on docs home page

docs/README.md, docs/zoneddatetime.md, polyfill/lib/ecmascript.mjs, polyfill/lib/instant.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/zoneddatetime.mjs, spec/datetime.html, spec/instant.html, spec/zoneddatetime.html
=> ZonedDateTime hoursInDay, startOfDay, round, add, subtract

docs/cookbook/birthdayIn2030.mjs, docs/cookbook/bridgePublicHolidays.mjs, docs/monthday.md, polyfill/index.d.ts, polyfill/lib/monthday.mjs, polyfill/test/MonthDay/prototype/toDate/infinity-throws-rangeerror.js, polyfill/test/MonthDay/prototype/toDate/length.js, polyfill/test/MonthDay/prototype/toDate/negative-infinity-throws-rangeerror.js, polyfill/test/date.mjs, polyfill/test/monthday.mjs, spec/monthday.html
=> Drop the integer argument to MonthDay.toDateInYear and rename.

docs/cookbook.md, docs/cookbook/getInstantWithLocalTimeInZone.mjs, docs/cookbook/getParseableZonedStringAtInstant.mjs, docs/instant.md, polyfill/index.d.ts, polyfill/lib/ecmascript.mjs, polyfill/lib/instant.mjs, polyfill/test/instant.mjs, polyfill/test/usertimezone.mjs, spec/instant.html
This adds an option for the time zone in which to print an Instant,
instead of having it be a separate argument. Also removes printing the
bracketed name from Instant.
Closes: #741
=> Add timeZone option to Instant.toString()

docs/README.md, docs/now.md, spec/temporal.html
While building another PR, I noticed that some of the Temporal.now methods hadn't been renamed in #1120 in in a few places in the spec and docs. (polyfill code looks OK). This PR mops up those missing renames. 
Also, there's a `now.time()` method that's listed in the docs home page but isn't mentioned or implemented elsewhere in Temporal, including in the drilldown docs for `now`. This PR renames this method to `plainTime` in the docs home page, and I opened #1133 for the missing implementation.
=> Mop up missing Temporal.now renames to plainXxx

polyfill/index.d.ts, polyfill/lib/now.mjs, polyfill/test/now.mjs, spec/temporal.html, spec/zoneddatetime.html
These two `now` methods hadn't been added yet. Docs are already live. This commit includes polyfill implementation and tests. Spec updates will still be needed, and I'll file a new issue for that.
=> Add now.zonedDateTime() and now.zonedDateTimeISO()

docs/date.md, docs/datetime.md, docs/monthday.md, docs/time.md, docs/yearmonth.md, docs/zoneddatetime.md, polyfill/lib/ecmascript.mjs, polyfill/test/plaindate.mjs, polyfill/test/plaindatetime.mjs, polyfill/test/plainmonthday.mjs, polyfill/test/plaintime.mjs, polyfill/test/plainyearmonth.mjs, polyfill/test/zoneddatetime.mjs, spec/abstractops.html
This PR renames the `toString()` option property `calendar` to `calendarName`, to better match the recent rename of `timeZone` to `timeZoneName` in the same context.
=> Rename toString option `calendar`=>`calendarName`

docs/zoneddatetime.md, polyfill/lib/ecmascript.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/zoneddatetime.mjs
~~Note that the DifferenceZonedDateTime abstract operation is not final:
there is one edge case that is broken in the polyfill, which is that the
since() method needs to use `this` as the relative date for rounding.
There is a test for that which is skipped.~~
~~A follow-up commit will fix this case and add spec text for the algorithm.~~
Co-authored-by: Justin Grant <justingrant@users.noreply.github.com>
See: #569
=> Implement ZonedDateTime.until() and since() in polyfill

spec.html, spec/plaindate.html
These problems were preventing builds from completing, which in turn prevented the Temporal website from updating.
The long-term solution is to ensure that ecmarkup must pass for a PR to merge. In the meantime, here's a PR to get builds working again.
=> Fix spec lint issues

polyfill/index.d.ts
* `calendar`=>`calendarName` option for `toString`
* updated param types for toZonedDateTime conversion methods per #889
* changed type of ZDT `timeZone` field to `Temporal.TimeZone` for easier workshop coding tomorrow.
=> Misc .d.ts fixes

docs/ambiguity.md
This PR updates the code samples in ambiguity.md with the latest syntax from #889 of additive conversion methods. I also fixed a few bugs in the examples now that they actually run! ;-)
=> Update ambiguity.md with latest conversion syntax

docs/date.md, docs/datetime.md, docs/instant.md, docs/time.md, docs/yearmonth.md, docs/zoneddatetime.md, polyfill/index.d.ts, polyfill/lib/instant.mjs, polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plaintime.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/instant.mjs, polyfill/test/plaindate.mjs, polyfill/test/plaindatetime.mjs, polyfill/test/plaintime.mjs, polyfill/test/plainyearmonth.mjs, polyfill/test/zoneddatetime.mjs, spec/instant.html, spec/plaindate.html, spec/plaindatetime.html, spec/plaintime.html, spec/plainyearmonth.html
Updates the default rounding mode for until/since to match user expectations that by default these methods measure "whole units" not partial remainders.
Docs are also updated, including fixing code example results for until/since, many of which were wrong due to this PR as well as other recent changes to `until`/`since` behavior.
BTW, I ran Test262 locally and all tests passed.
Fixes #1122.
=> Change default of until/since rounding to 'trunc'

docs/README.md, docs/cookbook.md, docs/date.md, docs/datetime.md, docs/head.html.part, docs/instant.md, docs/now.md, docs/time.md, docs/timezone.md, docs/zoneddatetime.md
* Remove references to removed PlainDateTime.prototype.toInstant` & `Instant.prototype.toPlainDateTime`
* Remove docs for TimeZone.prototype.getZonedDateTimeFor method that was never implemented. Consider for V2.
* Revised the PlainDateTime summary docs
* Fixed a few code samples
* Fixed CSS color for links in a `<code>` tag
* Fixed a few typos
=> Minor docs updates

polyfill/lib/instant.mjs
Fixes #1110 by switching from using the `'UTC'` timezone to an `undefined` timezone when calling `ES.TemporalInstantToString`.
With the fix:
=> Fix Instant's _repr_ to use Z suffix not +00:00

docs/object-model.svg
This PR updates the object diagram on the Temporal home page with new PlainXxx type names.
=> Update docs type diagram with PlainXxx names

polyfill/lib/regex.mjs, polyfill/test/plaindate.mjs, polyfill/test/plaindatetime.mjs, polyfill/test/regex.mjs, polyfill/test/validStrings.mjs, polyfill/test/zoneddatetime.mjs, spec/abstractops.html
Allows and ignores the timezone part in PlainDate.from and
PlainDateTime.from, as discussed previously.
Fixes: https://github.com/tc39/proposal-temporal/issues/1082
---
I decided to keep the spec changes out for now, because the grammars list in the spec need some serious refactoring.
=> polyfill: allow and ignore timezone in from

spec/instant.html, spec/zoneddatetime.html
=> Specification for ZonedDateTime.until/since

docs/cookbook/meetingPlanner.js, polyfill/lib/intl.mjs, polyfill/test/intl.mjs, spec/intl.html
=> ZonedDateTime.toLocaleString() and last cookbook example

polyfill/lib/zoneddatetime.mjs, spec/zoneddatetime.html
=> Specify ZonedDateTime.toPlain{YearMonth,MonthDay}()

docs/cookbook/meetingPlanner.js, docs/duration.md, polyfill/lib/ecmascript.mjs, spec/abstractops.html, spec/plaindate.html, spec/zoneddatetime.html
Spotted while working on #1171
=> Misc fixes

docs/duration.md, polyfill/index.d.ts, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/duration.mjs, spec/abstractops.html, spec/duration.html
=> Duration.compare()

docs/ambiguity.md
=> Fix typo in ambiguity.md

docs/datetime.md, docs/zoneddatetime.md, polyfill/index.d.ts, polyfill/lib/ecmascript.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/plaindatetime.mjs, polyfill/test/zoneddatetime.mjs, spec/plaindatetime.html, spec/zoneddatetime.html
This PR implements a subset of the changes described in https://github.com/tc39/proposal-temporal/issues/522#issuecomment-726285736:
> * Add PlainDateTime.withPlainDate(), PlainDateTime.withPlainTime(), ZonedDateTime.withPlainDate(), and ZonedDateTime.withPlainTime() to address the use case of combining dates and times without spreading. These methods use the 'consolidate' behaviour for calendars (throw if non-ISO and different).
This PR includes docs, polyfill implementation, docs, and TS types but not spec updates for these methods. 
BTW, I found a bug in ES.ConsolidateCalendars that is fixed here. That method never worked if the second calendar was ISO.
=> withTime() and withDate() methods on ZonedDateTime and PlainDateTime

polyfill/ci_test.sh
I did a little bit of debugging into the Test262 failures. I suspect that they were caused by the *huge* size of the JSON output from these tests. When I looked at the actual JSON output, almost all of it was the `contents` key, which is the source code of the test including all included files.  But our reporting UI doesn't actually use that source code at all.
The test262 harness has a CLI option to customize which keys are emitted in the JSON output, so I added a whitelist of keys that parseResults.py is actually using. 
The result was an error-free execution of Test262 on my Mac in about 35 seconds, which is at least 10x faster than before.
As a follow-up if I have time, I'll investigate changing the reporter from python to JS via https://github.com/bocoup/test262-stream which should …
=> Fix Test262 errors and speed up tests by 10x-20x

docs/zoneddatetime.md, polyfill/lib/zoneddatetime.mjs, polyfill/test/zoneddatetime.mjs, spec/zoneddatetime.html
`ZonedDateTime.prototype.offsetNanoseconds` was present in the docs and .d.ts (and was in #700) but seems to have been missed in the official polyfill implementation of ZonedDateTime. This PR fixes that gap.  It also updates the docs for the change we made in #935 to make `offset` a field and `offsetNanoseconds` a convenience property instead of the opposite.
=> Restore `ZonedDateTime.prototype.offsetNanoseconds` convenience property

polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/duration.mjs, spec/duration.html, spec/zoneddatetime.html
This fixes rounding and totalling Durations with a ZonedDateTime `relativeTo` parameter. ~~There is still one bug in the algorithm, which is causing one rounding test to fail, and the corresponding totalling test, so those two remain skipped until I can track down the bug.~~
Closes: #1171
=> More relativeTo rounding

polyfill/lib/zoneddatetime.mjs
Do all calculations using integer math and only do a single integer-division operation at the end.
=> Reduce potential precision loss in ZDT `hoursInDay`

polyfill/ci_test.sh, polyfill/package.json, polyfill/rollup.config.js, polyfill/test/parseResults.js, polyfill/test/preprocessor.test262.js
This PR continues where #1189 left off, specifically:
* Use a preprocessor to skip non-strict tests. This is ~8% slower than skipping the tests via the `[onlyStrict]` attribute inside the tests themselves, but skipping using a preprocessor is still more than 40% faster than running all tests twice
* Increase max threads from 2 to 8. This gave me a 60% speed boost on my Mac, although I assume this gain will be environment-dependent so YMMV.
* When running tests, only transpile polyfill code the harness uses.
The net result is that tests complete (including transpilation) in ~30s on my 2015 MacBook Pro. In CI where we're running codecov tests and the hardware is slower, it will still take a few minutes... but hopefully fewer minutes than before! ;-)
=> Speed up Test262 runs another 2x-3x

docs/zoneddatetime.md
The ZDT `from` docs incorrectly stated that date/time input was in context of the user-provided calendar, but that's not true for string inputs. 
This PR fixes this mistake. 
Thanks @ryzokuken for finding this!
=> Clarify ZDT docs for `from` behavior of date/time fields

polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/duration.mjs
This PR improves precision of rounding math throughout Temporal by reducing usage of non-integer `Number` math operations, in two ways:
1) Removing unnecessary math operations that could compound errors
2) Using `BigInt` instead of `Number` math where possible, converting to `Number` only at the end, right before returning a floating point result back to the caller.
Changes include:
* Converts `ES.RoundNumberToIncrement()` to use `BigInt` instead of `Number` math.
* Fixes #1197 by switching `ES.RoundDuration` to use `BigInt` math for all rounding and by directly returning a total to the caller which removes the need for a separate `Number` operation to add an integer and a fractional remainder.
* `ES.RoundInstant` now uses `BigInt` rounding math. While in the neighborhood, this PR fixes …
=> Improve precision of rounding  math

docs/instant.md
Some of the toString sample code had a wrong first parameter `undefined`.  This PR removes it.
=> Remove incorrect parameter from toString sample in Instant docs

spec/intl.html
=> Fix spec text for determining calendar to format with in toLocaleString

spec/abstractops.html, spec/calendar.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plainyearmonth.html, spec/temporal.html, spec/timezone.html, spec/zoneddatetime.html
In order to avoid repeating ourselves in the spec text when specifying
APIs where the calendar is optional, we introduce the abstract operations
ToOptionalTemporalCalendar and GetOptionalTemporalCalendar.
The former returns the ISO 8601 calendar if given the value `undefined`,
and the latter expects an object and calls ToOptionalTemporalCalendar on
its `calendar` property.
Closes: #1209
=> ToOptionalTemporalCalendar and GetOptionalTemporalCalendar abstract operations

docs/plaindate.md, docs/plaindatetime.md, docs/plainyearmonth.md, docs/zoneddatetime.md
The documentation was not clear on this, and in the case of equals() was
actually wrong. A true result from equals() implies a zero result from
compare().
Closes: #1199
=> Document calendar comparison in compare() and equals()

docs/duration.md, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/Duration/prototype/toString/options-undefined.js, polyfill/test/duration.mjs, polyfill/test/instant.mjs, polyfill/test/plaindatetime.mjs, polyfill/test/plaintime.mjs, polyfill/test/zoneddatetime.mjs, spec/abstractops.html, spec/duration.html
I overlooked Duration in #329. This adds the same options except that the
values for smallestUnit are preferred to be plural, and 'minutes' is not
allowed.
Closes: #1257
=> Add precision options to Duration.toString()

polyfill/lib/duration.mjs, polyfill/test/duration.mjs, polyfill/test/instant.mjs, polyfill/test/plaindatetime.mjs, polyfill/test/plaintime.mjs, polyfill/test/zoneddatetime.mjs, spec/duration.html
=> Fix exception for missing units in Duration.round()

docs/calendar.md, polyfill/lib/calendar.mjs, spec/calendar.html
Allows Calendar serialization to JSON.
Fixes #1227 separate from #1245
=> Specify & implement JSON representation for Temporal.Calendar as identifier

polyfill/lib/calendar.mjs
=> Change Temporal.Date intrinsic to Temporal.PlainDate in iso8601 `era()` impl

spec/timezone.html, spec/zoneddatetime.html
=> Replace ÷ by / in the spec.

polyfill/lib/calendar.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/PlainDate/prototype/getFields/order-of-operations.js, polyfill/test/PlainDateTime/constructor/from/order-of-operations.js, polyfill/test/PlainDateTime/prototype/getFields/order-of-operations.js, polyfill/test/PlainMonthDay/prototype/getFields/order-of-operations.js, polyfill/test/PlainYearMonth/prototype/getFields/order-of-operations.js, polyfill/test/usercalendar.mjs, spec/abstractops.html, spec/calendar.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plaintime.html, spec/plainyearmonth.html, spec/zoneddatetime.html
Do not coerce {day, month, year} to integers except in ISO calendar implementation.
Fixes #1229.
=> Allow calendars to validate fields and coerce types

polyfill/lib/calendar.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/intl.mjs, polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plainmonthday.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/lib/timezone.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/TimeZone/prototype/id/no-toString.js, polyfill/test/TimeZone/prototype/id/plain-custom-timezone.js, polyfill/test/TimeZone/prototype/toJSON/custom-tostring-undefined.js, polyfill/test/TimeZone/prototype/toJSON/tostring-call.js, polyfill/test/TimeZone/prototype/toJSON/tostring-undefined-custom.js, polyfill/test/TimeZone/prototype/toJSON/tostring-undefined.js, spec/calendar.html, spec/intl.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plaintime.html, spec/plainyearmonth.html, spec/timezone.html, spec/zoneddatetime.html
See: #1294 (but does not close the discussion)
=> Remove CalendarToString and TimeZoneToString

spec/intl.html
=> Specify era/eraYear.

docs/calendar.md, docs/plaindate.md, docs/plaindatetime.md, docs/plainmonthday.md, docs/plainyearmonth.md, docs/zoneddatetime.md
This PR:
* Documents new `monthCode` and `eraYear` properties across all Temporal types where these properties are used, including docs for the getters themselves and also where they're used (esp. in `from` methods)
* Adds additional details about date field getters. For consistency, time field getters too in PlainDateTime/ZonedDateTime also get a little more detail.
* Clarifies PlainYearMonth/PlainMonthDay behavior with non-ISO calendars
* Documents which invariants hold across calendars (currently it's a short list; I assume we'll add to this list later as we realize what other invariants also hold)
* Documents best practices for writing cross-calendar code. This could be broken out into a new page if needed, but calendar.md is already a fairly specialized page for experts so it might …
=> Documentation changes for non-ISO calendars

polyfill/index.d.ts, polyfill/lib/calendar.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plainmonthday.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/PlainDate/constructor/from/negative-infinity-handled.js, polyfill/test/PlainDate/prototype/with/negative-infinity-handled.js, polyfill/test/PlainDateTime/constructor/from/negative-infinity-handled.js, polyfill/test/PlainDateTime/prototype/with/negative-infinity-handled.js, polyfill/test/PlainMonthDay/constructor/from/negative-infinity-handled.js, polyfill/test/PlainMonthDay/prototype/with/negative-infinity-handled.js, polyfill/test/PlainYearMonth/constructor/from/negative-infinity-handled.js, polyfill/test/PlainYearMonth/prototype/with/negative-infinity-handled.js, polyfill/test/calendar.mjs, polyfill/test/intl.mjs, polyfill/test/usercalendar.mjs, spec/abstractops.html, spec/calendar.html, spec/intl.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plainyearmonth.html, spec/zoneddatetime.html
**Do not merge**; RFC only in this state
This change does a few other things as well:
- Implement `era`, `eraYear` for all remaining objects.
- Implement `eraYear`/`year` split behavior for `'gregory'` and `'japanese'` calendars (NB: choice of anchor/default era in 'japanese' should be revisited with more cultural context).
I only included the specification for the new `PrepareTemporalFields` abstract operation; I'm still refactoring the spec text into all the other `ToTemporal*Fields`, `ToRelativeTemporalObject`, etc abstract operations and that's messy / incomplete at the moment. However, `PrepareTemporalFields` closely matches how ES.ToRecord was used throughout the polyfill already, so this brings the specification and polyfill much closer together.
There are a number of questions and …
=> Update validation, coercion for all built-in fields.

polyfill/lib/ecmascript.mjs, polyfill/test/plainmonthday.mjs, polyfill/test/plainyearmonth.mjs, polyfill/test/usercalendar.mjs, spec/plainmonthday.html, spec/plainyearmonth.html
In PlainYearMonth and PlainMonthDay, when constructing via the from()
method, the reference ISO day or year should always be given by the
calendar ("canonicalized") and never by user code. This was already the
case when the argument to from() is a property bag or another Temporal
object, but was not the case when the argument is a string.
This requires, slightly weirdly, calling the intrinsic PMD/PYM constructor
and then calling calendar.monthDayFromFields/yearMonthFromFields on the
result of _that_, but it is more consistent this way.
The constructor functionality remains the same, where the reference ISO
day or year is used without any change.
Closes: #1316
=> Ensure reference ISO year/day is always given by the calendar

spec/biblio.json, spec/intl.html, spec/timezone.html
The abstract operations dealing with the system time zone and the time
zone names were part of 402, but here they need to move into 262, without
obligating non-402 implementations to offer the full list of time zone
names.
Closes: #1292
=> Clarify which time zones must be supported in a non-402 implementation

polyfill/lib/ecmascript.mjs, spec/plainmonthday.html, spec/plainyearmonth.html
When reading a PlainYearMonth or PlainMonthDay from a string, if there is
no day or year (respectively) given (meaning also the calendar is ISO),
it's not necessary to construct an object twice in order to canonicalize
the reference day or year. This removes user-observable calls to calendar
methods in that case.
Follow up from #1316.
=> Avoid constructing YearMonth/MonthDay twice if possible

docs/README.md
A comma was missing from a code sample so I fixed that so it's copy and pastable.
The snippet
```js
const dateTIme1 = dateTime.with({
minutes: 17,
seconds: 19,
});
```
raised the error `Uncaught TypeError: invalid date-time-like` using the plurals. I assume that the docs should show what currently works, but if it should support `minutes` and `seconds` then I can change it back.
=> Update samples on documentation

CHANGELOG.md, polyfill/package.json
We should cut a release of the polyfill now that the API is frozen.
=> Version bump in preparation for release

.github/workflows/test.yml
Fixes #1335.  This PR changes CI to run polyfill and cookbook tests in Node 12.x, 14.x, and 15.x. 
I didn't add Test262 to this list because my assumption was that those tests were primarily used by platform (browsers, Node, etc.) to test against new versions so backwards-compat is less of an issue. If this is an incorrect assumption, it'd be easy to add 262 to multi-version testing too.
=> Run polyfill & cookbook tests in Node v[15|14|12]

docs/calendar.md
**Description of the Change**
remove balance word from calendar doc
**Release Notes**
- Fix issue [#1320](https://github.com/tc39/proposal-temporal/issues/1320)
=> fix: remove balance word

docs/plaindate.md, docs/plaindatetime.md, docs/plainyearmonth.md, docs/zoneddatetime.md, polyfill/lib/calendar.mjs, polyfill/test/calendar.mjs, polyfill/test/plainmonthday.mjs, polyfill/test/plainyearmonth.mjs, polyfill/test/zoneddatetime.mjs
This PR changes the `bc` and `ad` eras in the `gregory` calendar to `ce` and `bce`, respectively, per   
https://github.com/unicode-org/icu4x/issues/470#issuecomment-772735333.
=> Convert "bc"/"ad" eras to "bce"/"ce" in Gregorian calendar

polyfill/lib/calendar.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/intl.mjs
This PR adds initial implementations for all supported ICU non-ISO calendars, and proposes a few possible changes to the Temporal API to address issues found while building those calendars.  The goal of this PR is to validate the Temporal calendar API and to identify potential issues we may need to discuss and/or resolve. To set expectations, the calendar implementations themselves pass basic tests and match the output of `Intl.DateTimeFormat`, but are not intended to have production-ready accuracy nor performance.  Also, this PR has some gaps and unfinished parts, but I wanted to get it into GitHub so we can start discussion and resolve open issues. On a personal note, getting this PR into GitHub was helpful to keep my mind off the chaos in Washington today!  Fixes #1210. FIxes #1349.
At …
=> Initial implementation of all ICU calendars

docs/plaindatetime.md
=> Document PlainDateTime use cases

docs/plaindatetime.md
Rename a misreference from Temporal.Absolute to Temporal.Instant.
/cc @SimenB
=> docs: rename absolute to instant

polyfill/lib/ecmascript.mjs, polyfill/test/Instant/prototype/toString/precision.js
Fix a bug where Instant.prototype.toString produced the incorrect result
where the fractional part included leading zeroes and precision was not
auto or 0. Includes test262 test for the same.
Fixes: https://github.com/tc39/proposal-temporal/issues/1336
=> polyfill: fix Instant precision bug

polyfill/index.d.ts
The polyfill is missing TypeScript types for the Intl namespace and Date.toTemporalInstant.
This PR adds:
- A global type representing the result of `DateTimeFormat#formatRangeToParts`, since its currently missing from TypeScript's built-in lib.
- An `IntlPolyfill` namespace that is exported as `Intl`. The different name allows for the global `Intl` namespace to be referenced by other types, and doesn't affect the end result.
- A variant of `Intl.DateTimeFormat` that adds typing support for passing Temporal objects in.
- A variant of `formatRange` that enforces that the Temporal start and end types match each other.
- `toTemporalInstant` function that includes a `this` type.
=> Add polyfill types for Intl and Date.toTemporalInstant

docs/persistence-model.svg
This PR fixes the size of persistence-model.svg so the right edge of the diagram won't be clipped in the docs home page.
Current: 
Fixed:
=> Docs: show clipped content at right edge of persistence-model.svg

docs/plaindate.md, docs/plaindatetime.md, docs/plainmonthday.md, docs/plainyearmonth.md, docs/zoneddatetime.md
This PR is a few minor monthCode-related fixes for the docs: 
* Add missing "M" prefix in a few docs code examples that I missed in #1321
* Fix missing backticks
* Cut out a few words that weren't needed
=> Documentation fixes for monthCode

spec/calendar.html
This is subject to further change based on IETF standardization of monthCodes; it is not going to be defined by temporal.
Fixes #1348.
=> Bugfix: Make ISO monthCode abstract operations match polyfill.

docs/plaindate.md, docs/plaindatetime.md, docs/plainmonthday.md, docs/plaintime.md, docs/plainyearmonth.md, docs/zoneddatetime.md
=> docs: Clarify that the from() overflow option doesn't apply to strings

docs/cookbook-nyse.md, docs/cookbook.md, docs/cookbook/stockExchangeTimeZone.mjs, polyfill/package.json
This PR adds a cookbook sample with a proof-of-concept of a custom time zone that implements an "NYSE Time Zone" where there are no valid PlainDateTIme values except when the market is open. When the market is closed, PlainDateTime values are disambiguated forward to the opening bell of the next market day.
This makes it easy to identify the "market day" for any particular Instant or PlainDateTime and other similar use cases. This PR implements the following use cases as tests:
1. What is the market day associated with the Instant of a financial transaction?
2. Is the stock market open on a particular date?
3. For a particular date, when is the next market day?
4. For a particular date and time somewhere in the world, is the market open right now? If it's open, then when will it close? If …
=> Add NYSE custom time zone cookbook sample

spec/biblio.json, spec/intl.html
WIP series of commits rebasing the Temporal 402 spec on top of the spec from the DateTimeFormat.p.formatRange proposal.
Trying to make editorial cleanups or improvements where possible.
/cc @ptomato @Ms2ger 
Refs: https://github.com/tc39/ecma402/pull/532
=> Rebase on top of DateTimeFormat.formatRange

docs/README.md, docs/duration.md
There were a few incomplete or incorrect code samples in the Duration docs. This PR fixes them. I made a few minor tweaks in the Duration docs while I was in the neighborhood.
=> Fix Duration docs code samples

polyfill/lib/ecmascript.mjs, polyfill/test/calendar.mjs
The current algorithm for calculating the ISO week number is wrong for dates that belong to an ISO week from the previous year. For example `Temporal.Calendar.from("iso8601").weekOfYear("2021-01-01")` returns 52 but the correct answer is 53.
The problem is in the function `ES.WeekOfYear`: This function computes first the expression `const week = MathFloor((doy - dow + 10) / 7);` and then, if the answer is 0, this means that the day belongs to the last ISO week of the previous year. So the result of the function must be the number of ISO weeks of the *previous* year, which is 53 if the previous year ends on a Thursday (regardless if its a leap or not) or if ends on a Friday and is a leap. Otherwise the result must be 52 ([source](https://en.wikipedia.org/wiki/ISO_week_date#Weeks_per_year)). …
=> polyfill: Fix iso week number

polyfill/lib/ecmascript.mjs, polyfill/test/duration.mjs
Due to a missing argument, Temporal.Duration.from({ hours: 1 }).toJSON()
would return "PT1H0.0S" instead of "PT1H". The same goes for
toLocaleString() in the absence of Intl.DurationFormat.
No change needed to the spec text or documentation, which are already
correct.
Closes: #1371
=> Duration.toJSON() should not print unwanted zeroes

polyfill/index.d.ts
I noticed some of the TypeScript definitions for the `Temporal.now` methods had slightly incorrect descriptions (mostly looked like copy/paste errors).
This tidies up the descriptions to be consistent, and also fixes a couple of other typos I found elsewhere in the file.
=> Tidy up TypeScript descriptions for .now methods

polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/duration.mjs, spec/abstractops.html, spec/calendar.html, spec/duration.html, spec/intl.html, spec/plaindate.html, spec/plainyearmonth.html
Fix bug where largestUnit: 'auto' is considered to be no unit provided.
Fixes #1379.
=> Duration.prototype.round: Throw on no largest or smallest unit provided.

spec/temporal.html
I found another spec discrepancy while auditing docs code samples, where the docs+polyfill disagree with spec.
`Temporal.now.{plainDate,plainDateTime,zonedDateTime}()` should accept undefined calendar because they all delegate to [SystemDateTime](https://tc39.es/proposal-temporal/#sec-temporal-systemdatetime) which uses `ToOptionalTemporalCalendar`. However, calendarLike isn't listed as an optional argument.
Which is the correct behavior? Assuming the spec is correct, this makes the polyfill match and adds some optionality-brackets to the spec for clarity.
=> Spec: Throw on undefined calendar in Temporal.now

docs/calendar.md, polyfill/lib/ecmascript.mjs, polyfill/lib/intl.mjs, polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plainmonthday.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/lib/timezone.mjs, polyfill/lib/zoneddatetime.mjs, spec/calendar.html, spec/duration.html, spec/intl.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plainyearmonth.html, spec/timezone.html, spec/zoneddatetime.html
Encountered while investigating #1294
=> Various bugfixes and making things consistent

polyfill/lib/calendar.mjs, polyfill/lib/ecmascript.mjs, polyfill/test/plainmonthday.mjs, spec/calendar.html, spec/plainmonthday.html
ToTemporalMonthDay accepts 'month' without 'monthCode' or 'year' when no calendar has been specified, for users writing calendar-insensitive code. However, when a calendar has been specified, ISOMonthDayFromFields will still accept 2/29/2001 specified via month and year. This change makes ISOMonthDayFromFields reject or constrain 02-29 when month + year are specified, and keeps acceptance of 02-29 when only monthCode + day are specified. See the added test case for some examples.
=> ISOMonthDayFromFields: Reject leap day in appropriate cases when calendar is specified.

docs/README.md, docs/duration.md, docs/plaindate.md, docs/plaindatetime.md, docs/plainmonthday.md, docs/plaintime.md, docs/plainyearmonth.md, docs/zoneddatetime.md, spec/calendar.html, spec/instant.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plaintime.html, spec/plainyearmonth.html, spec/timezone.html, spec/zoneddatetime.html
'Immutable' is not the correct word to describe Temporal JavaScript
objects. Change documentation to refer to Temporal objects representing fixed
moments in time, and strike all uses of immutability from the spec text.
Fixes #1387.
=> Remove all references to immutability.

polyfill/lib/ecmascript.mjs, spec/abstractops.html, spec/duration.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plaintime.html, spec/plainyearmonth.html, spec/timezone.html, spec/zoneddatetime.html
Fix a number of small bugs where variables in spec text are used without being
defined, defined without being used; a wide range of small bugs exposed by a
quick-and-dirty linter I wrote. Common culprits look like:
- Referencing undefined _calendar_ instead of _someObject_.[[Calendar]]
- Set _thing_ to ? Create... instead of Let _thing_ be ? Create...
=> Fix undefined / unused variables in spec text.

polyfill/lib/calendar.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plainmonthday.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/lib/timezone.mjs, polyfill/lib/zoneddatetime.mjs, spec/abstractops.html, spec/calendar.html, spec/duration.html, spec/instant.html, spec/intl.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plainyearmonth.html, spec/timezone.html, spec/zoneddatetime.html
For all abstract operations that operate exclusively on ISO-valued or ISO-named
fields/slots, rename them to prepend ISO to the relevant part of the operation
name. E.g. "RegulateDate" => "RegulateISODate".
Fixes #1389.
=> Clarify names of abstract operations applying to internal ISO data model

polyfill/lib/ecmascript.mjs, spec/duration.html
Rounding durations to years was an operation that was previously of the
order O(Years), since it looped over the number of days. This commit
optimizes that logic by deferring that to calendar-specific PlainDate
arithmetic, essentially making it O(1).
Fixes: https://github.com/tc39/proposal-temporal/issues/1242
/cc @cjtenny @ptomato @justingrant
=> polyfill: optimize rounding durations to years

spec/timezone.html
These operations were renamed to have "ISO" in the name while I was
working on the patch that defined the operations in which they were
called.
Closes: #1416
=> Fix abstract operation names

spec/instant.html, spec/intl.html
I had forgotten this one, see https://github.com/tc39/proposal-temporal/issues/1292#issuecomment-790932668
=> Fix Instant.toLocaleString 402 split

docs/duration.md, docs/instant.md, docs/plaindate.md, docs/plaindatetime.md, docs/plaintime.md, docs/plainyearmonth.md, docs/zoneddatetime.md, polyfill/index.d.ts, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/instant.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plaintime.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/duration.mjs, polyfill/test/instant.mjs, polyfill/test/plaindate.mjs, polyfill/test/plaindatetime.mjs, polyfill/test/plaintime.mjs, polyfill/test/plainyearmonth.mjs, polyfill/test/zoneddatetime.mjs, spec/abstractops.html, spec/duration.html, spec/instant.html, spec/plaindatetime.html, spec/plaintime.html
In the ECMA-402 meeting of 2021-02-11, 'nearest' was renamed to
'halfExpand'. By definition, Temporal uses the same names for rounding
modes as in that proposal.
See: #1038
=> Sync rounding mode names with Intl.NumberFormat v3

README.md, docs/head.html.part, polyfill/README.md
Here's a few small readme and docs changes now that we're in Stage 3!  I wasn't sure if there's particular wording we should be using for our new status, so I tried to keep it simple.
When saving, Prettier made a few whitespace changes that seemed harmless, so I left them in instead of reverting them.
=> Readme & doc changes for Stage 3

docs/head.html.part
On my iPhone X, the docs header text wraps to three lines and obscures the H1 title. This commit removes an unnecessary word to limit the header to 2 lines.
=> Fix docs header on iPhone devices

docs/zoneddatetime.md
Some examples in the `ZonedDateTime` docs page got missed when adding the `Temporal.now.zonedDateTimeISO()` API.
Fixes #1437
=> Fix broken Temporal.now examples in ZonedDateTime docs

polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/PlainDate/constructor/compare/use-internal-slots.js, polyfill/test/PlainDateTime/constructor/compare/use-internal-slots.js, polyfill/test/zoneddatetime.mjs, spec/plaindate.html, spec/plaindatetime.html, spec/plainyearmonth.html, spec/zoneddatetime.html
This commit changes different compare methods on types that include
calendars to not take them into account. With this, two instances that
have different calendars attached but map to the same points in the ISO
calendar are compared to be "equal".
Fixes: https://github.com/tc39/proposal-temporal/issues/1431
/cc @bakkot
=> compare methods should not include calendar

docs/README.md, docs/calendar-review.md
This PR fixes some code sample formatting issues on the new calendar design document and adds a link to it from the "other documentation" section on the docs home page. 
* Fixed the formatting of one code sample in the calendar review page
* Added a link to the calendar review page from the docs home page
* Fixed a too-wide docs homepage code sample (was horizontal scrolling)
* Split paragraphs into separate lines, which will make subsequent PRs easier
* Prettier made a bunch of other harmless changes
=> Minor fixups to two docs pages

docs/calendar-review.md
This PR adds content to the calendar review page: 
* A new "Why are Calendars a Higher Priority for ECMAScript vs. Other Platforms?" section 
* A third option for mitigating the Unexpected Calendar Problem which is patching Temporal.
=> Update "calendar review" docs content

spec/timezone.html
Remove CompareTimeZone which no spec text referring to
close #1475
=> Remove dangling CompareTimeZone

docs/README.md, docs/ambiguity.md, docs/balancing.md, docs/calendar-review.md, docs/calendar.md, docs/cookbook/getUtcOffsetStringAtInstant.mjs, docs/duration.md, docs/instant.md, docs/parse-draft.md, docs/plaindate.md, docs/plaindatetime.md, docs/plainmonthday.md, docs/plaintime.md, docs/plainyearmonth.md, docs/timezone.md, docs/zoneddatetime.md, polyfill/lib/plainmonthday.mjs
Running all the code samples in the docs through a tolerant markdown snippet parser + execution environment revealed many errors. #1395, #1391, #1380, and this patch's one-line fix in plainmonthday.mjs were all bugs revealed by the documentation code samples. Many of the changes in this patch are slight syntactic changes to make the samples testable and more clear.
Common classes of smaller issues fixed:
- Examples did not include seconds in string representations
- Examples contained extra zeroes of precision when not requested
- Old calling conventions used; arguments needed to be changed
- Some options bags are now used in dedicated places rather than alongside other methods
Though the documentation tester I wrote isn't included in this patch, because it's messy, one-off, and would be …
=> Correct + make runnable documentation code samples.

polyfill/lib/ecmascript.mjs, polyfill/test/PlainDateTime/prototype/until/balance.js, spec/plaindatetime.html
This ensures cases such as months=1, hours=-1 are balanced correctly.
Fixes #1415.
=> Handle opposite date/time signs in DifferenceISODateTime.

polyfill/lib/ecmascript.mjs, spec/calendar.html, spec/timezone.html
=> Short-circuit common case of comparing a calendar or time zone to itself

polyfill/lib/calendar.mjs, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/instant.mjs, polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plainmonthday.mjs, polyfill/lib/plaintime.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/lib/timezone.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/ecmascript.mjs, spec/abstractops.html, spec/calendar.html, spec/duration.html, spec/instant.html, spec/intl.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plaintime.html, spec/plainyearmonth.html, spec/timezone.html, spec/zoneddatetime.html
This eventually landed as GetOptionsObject in the 2021 edition of ECMA-402
so update the name, and note in the amendments section that the operations
are to be moved from ECMA-402 into ECMA-262.
Closes: #1249
=> Update to the version of NormalizeOptionsObject in ECMA-402

polyfill/index.d.ts
Pulling this one-line fix out of #1497.
=> Add missing parameter in Duration.p.toString

docs/duration.md
Fixes a typo in the docs for `Duration.p.round()`
=> FIx typo: PlainDateTime => Duration

polyfill/test/PlainDate/prototype/getISOFields/field-names.js, polyfill/test/PlainDate/prototype/getISOFields/field-traversal-order.js, polyfill/test/PlainDateTime/prototype/getISOFields/field-names.js, polyfill/test/PlainDateTime/prototype/getISOFields/field-traversal-order.js, polyfill/test/PlainMonthDay/prototype/getISOFields/field-names.js, polyfill/test/PlainMonthDay/prototype/getISOFields/field-traversal-order.js, polyfill/test/PlainTime/prototype/getISOFields/field-names.js, polyfill/test/PlainTime/prototype/getISOFields/field-traversal-order.js, polyfill/test/PlainYearMonth/prototype/getISOFields/field-names.js, polyfill/test/PlainYearMonth/prototype/getISOFields/field-traversal-order.js, polyfill/test/ZonedDateTime/prototype/getISOFields/field-names.js, polyfill/test/ZonedDateTime/prototype/getISOFields/field-traversal-order.js, spec/plaindatetime.html, spec/zoneddatetime.html
Fixes the names of properties on the return value from ZonedDateTime.getISOFields, which were missing the `iso` prefix.
Fixes the definition order of properties on the return value from PlainDateTime.getISOFields, which was incorrectly alphabetized.
Adds test262 tests for these fixes to all getISOFields methods.
Closes: #1508
=> Normative: Fix inconsistent property names/order returned by `getISOFields()`

docs/README.md, docs/balancing.md, docs/calendar-review.md, docs/calendar.md, docs/cookbook/futureDateForm.js, docs/cookbook/getElapsedDurationSinceInstant.mjs, docs/cookbook/stockExchangeTimeZone.mjs, docs/duration.md, docs/instant.md, docs/plaindate.md, docs/plaindatetime.md, docs/plaintime.md, docs/plainyearmonth.md, docs/zoneddatetime.md
Fixes #1486 to prefer singular names of units in `smallestUnit`/`largestUnit`/`unit` option values. 
Includes a few other minor changes (mostly whitespace) due to running prettier on docs code samples.
=> Prefer singular unit names in documentation

polyfill/index.d.ts
Fixes #1487. Also fixes bugs in the unit options declaration for PlainTime's `until`/`since`.  
While building this I also discovered an unrelated bug that's PR-ed in #1500.
=> Prefer singular unit names in TS types

spec/abstractops.html, spec/calendar.html, spec/duration.html, spec/instant.html, spec/intl.html, spec/plaindate.html, spec/plaindatetime.html, spec/plaintime.html, spec/plainyearmonth.html, spec/zoneddatetime.html
Both singular and plural names remain accepted everywhere, and 'week' is
now accepted where previously only 'weeks' was. However, the singular form
is now preferred for Temporal.Duration as well, and the spec text should
reflect this.
Ensure that options objects passed to user code have the correct singular
unit strings on them.
Closes: #1491
=> Normative: Use singular unit names throughout

.github/workflows/test.yml, polyfill/test/intl.mjs
This PR: 
* Fixes Node 14 test failures caused by fixes to underlying Node 14 Intl implementations that make tests pass that previously were expected to fail.
* Updates the CI config to use Node 16 instead of Node 15.
=> Fix Node 14 Tests and switch Node 15->16

docs/plainmonthday.md
Replaced `PlainDateTime` (wrong) with `PlainMonthDay` in the docs for `PlainMonthDay.p.equals`. Also added examples using string and object parameters.
=> Change `PlainMonthDay.p.equals` docs code sample to use correct type

docs/ambiguity.md
Fix references to outdated "DateTime" type name
=> Update ambiguity.md to remove outdated "DateTime" type name

spec/abstractops.html, spec/calendar.html, spec/duration.html, spec/instant.html, spec/intl.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plaintime.html, spec/plainyearmonth.html, spec/temporal.html, spec/timezone.html, spec/zoneddatetime.html
=> Editorial: Fix various issues

spec/instant.html
=> _epochNanoseconds_ in CreateTemporalInstant 
There are no _ns_ defined in CreateTemporalInstant now.
https://tc39.es/proposal-temporal/#sec-temporal-createtemporalinstant
@ptomato @sffc @justingrant
=> Editorial: fix ns => epochNanoseconds in CreateTemporalInstant

docs/plaintime.md
Add a warning in the docs to provide guidance on comparing times on days where DST ends. 
See https://github.com/tc39/proposal-temporal/issues/1547#issuecomment-864291946
=> Add DST warning to `PlainTime.p.compare()` docs

docs/README.md
Fixes #1553. Also clarifies language in the top section.
=> Clarifications for docs home page

docs/calendar.md
=> Try to clarify Calendar#fields documentation.

polyfill/lib/zoneddatetime.mjs, polyfill/test/ZonedDateTime/prototype/round/div-zero.js, spec/zoneddatetime.html
=> Editorial: Avoid dividing by zero in ZonedDateTime#round.

spec/timezone.html
I think we have some problem with current logic in the TimeZone
First of all, let's assume the spec support only the "minimum implementation", which mean
IsValidTimeZoneName only return true if the timeZone is a case-insiitive verison of "UTC" and CanonicalizeTimeZoneName only return "UTC".
https://tc39.es/proposal-temporal/#sec-isvalidtimezonename
https://tc39.es/proposal-temporal/#sec-canonicalizetimezonename
Now, we can see some issue in the rest of the spec
https://tc39.es/proposal-temporal/#sec-temporal.timezone
notice if the identifier is something like "+12", "-12:34" "+12:34:56" it will then satisfied 
"3.  If identifier satisfies the syntax of a TimeZoneNumericUTCOffset (see 13.33), then"
and step 3.b will be run
b. Let canonical be ! …
=> Move assert down in CreateTemporalTimeZone

spec/duration.html
Make it clear that precision is not "minute" in the beginning of TemporalDurationToString
Currently, it is not very clear that the precision cannot be "minute" in this Abstract Operation
So when we look at step 21
In TemporalDurationToString
https://tc39.es/proposal-temporal/#sec-temporal-temporaldurationtostring
21-c. If precision is "auto", then
21-c-i. Set decimalPart to the longest possible substring of decimalPart starting at position 0 and not ending with the code unit 0x0030 (DIGIT ZERO).
21-d. Else if precision ≠ 0, then
21-d-i. Set decimalPart to the substring of decimalPart from 0 to precision.
It has an illusion that , step 21-d and 21-d-i could be troublesome because the precision could be "minute" but  the fact is the precision will never be "minute" from the caller, but that …
=> Assert precision in TemporalDurationToString

spec/plaintime.html
Step 3 should be 
3. Let minute be minute formatted as a two-digit decimal number, padded to the left with a zero if necessary.
not
3. Let hour be minute formatted as a two-digit decimal number, padded to the left with a zero if necessary.
@sffc @ptomato @justingrant @Ms2ger @ryzokuken
=> fix typo in TemporalTimeToString

spec/plaintime.html
Current spec text pass one extra "auto" as the second precision to TemporalTimeToString in 
4.3.21 Temporal.PlainTime.prototype.toLocaleString ( [ locales [ , options ] ] )
https://tc39.es/proposal-temporal/#sec-temporal.plaintime.prototype.tolocalestring
and pass the calendar and one extra "auto" as another precision to TemporalTimeToString in
4.3.22 Temporal.PlainTime.prototype.toJSON ( )
https://tc39.es/proposal-temporal/#sec-temporal.plaintime.prototype.tojson
This make the three different calls to TemporalTimeToString all pass different number of arguments. 
We should make it only passing one precision and no calendar in all cases.
@sffc @justingrant @ptomato @Ms2ger  @ryzokuken
=> Correct argument to TemporalTimeToString

docs/iso-string-ext.md
This is a typo of {hebrew} right? I cannot find {} syntax in the ISO8601 grammar
=> Change unsupported {hebrew} to [u-ca=hebrew]

spec/plaindatetime.html, spec/plaintime.html, spec/timezone.html, spec/zoneddatetime.html
And do the same for operations that are now infallible as well.
=> Editorial: Mark BalanceTime as infallible.

polyfill/lib/zoneddatetime.mjs
=> Fix typo in error message

README.md, polyfill/README.md
This PR makes a few changes to main and ./polyfill README content to prepare for deprecation of the old polyfill. 
There's a new "Polyfills" table in the README that will point readers to any available polyfills. Initially there's only one entry in the table for @js-temporal/polyfill but developers of polyfills are encouraged to add theirs to the table too.  The champions of this proposal have no opinion about which polyfill developers should use; we just want polyfills to be easily discoverable. 
While I was in the neighborhood, I made some minor edits to other content on these pages.
=> README changes to prepare for polyfill deprecation

polyfill/CHANGELOG.md, polyfill/package.json
Final version, adding a deprecation notice.
Also moving changelog from root folder to polyfill/, as it applies only to
the polyfill.
=> Version bump and changelog for 0.9.0

spec/abstractops.html
Table  Table 13: Temporal field requirements is only used by
https://tc39.es/proposal-temporal/#table-temporal-field-requirements
https://tc39.es/proposal-temporal/#sec-temporal-preparetemporalfields
13.46 PrepareTemporalFields ( fields, fieldNames, requiredFields )
and PrepareTemporalFields is NOT used by Temporal.Duration
The fieldNames could only come from one of two places
1. the return of CalendarFields
2. the return of CalendarMergeFields
and according to the spec the iso8601 calendar will not output any token in the plural form from the Temporal.Calendar.prototype.fields and Temporal.Calendar.prototype.mergeFields and I believe there are no reason a custom calendar subclass from that or builtin for i18n has the need or should return a field name in the plural forms.
Notice this is …
=> Editorial: Remove plural rows and add "timeZone" in Table 13

spec/plainmonthday.html, spec/plainyearmonth.html
No need to check the if, the concat of empty string is the same.
=> Editoral: rm test _calendarString_ is empty before concat

polyfill/lib/calendar.mjs
I was wrong about what was making non-ISO calendars so slow. I thought the problem was `formatToParts()`, but it turns out that the `DateTimeFormat` constructor is really slow and also allocates ridiculous amounts of RAM. See more details here: https://bugs.chromium.org/p/v8/issues/detail?id=6528
@littledan in https://bugs.chromium.org/p/v8/issues/detail?id=6528#c4 recommended to cache DateTimeFormat instances, so that's what this commit does.
The result is about a ~~6x~~ 10x speedup in non-ISO calendar tests.
* Before: 6398.83ms
* After: ~~1062.26ms~~ 626.64ms (UPDATE: final code is even faster) 
I also added proper caching of global builtins like other Temporal code uses. 
Many thanks to @fer22f for uncovering this optimization (and its root cause) in …
=> Speed up non-ISO calendar tests about 10x by caching DateTimeFormat instances

polyfill/lib/ecmascript.mjs
Creating `Intl.DateTimeFormat` instances in V8 is slow and memory heavy. `ES.GetFormatterParts` and `ES.GetCanonicalTimeZoneIdentifier` are functions that are called many times when using Temporal, and they used to create new instances of Intl.DateTimeFormat for each call. In this commit, we cache them using the time zone identifier as the key.
It should be noted that doing the same to SystemTimeZone was avoided. This is due to the fact that user's time zone may change during the execution of a program. An example: `Temporal.now.zonedDateTimeISO()` should always output the correct time zone. This shouldn't be a problem for server-side code that usually doesn't (or rather, shouldn't) use the time zone from the environment for calculations.
This PR was ported from …
=> Speed up TimeZone and ZonedDateTime code and tests

spec/timezone.html
11.6.1 ParseTemporalTimeZone ( string )
in step 4 currently Return result.[[TimeZoneName]].
where in step 2. Let result be ? ParseTemporalTimeZoneString(string).
But ParseTemporalTimeZoneString in
https://tc39.es/proposal-temporal/#sec-temporal-parsetemporaltimezonestring
only 
Return the new Record: { [[Z]]: "Z", [[OffsetString]]: "+00:00", [[Name]]: undefined }. in step 4a 
OR
Return the new Record: { [[Z]]: undefined, [[OffsetString]]: offsetString, [[Name]]: name }.
in either case, there are no [[TimeZoneName]] in the return record.
I believe this is a typo and should change from result.[[TimeZoneName]]  to result.[[Name]] 
in ParseTemporalTimeZone
Otherwise, ParseTemporalTimeZone will always only return either "UTC" or undefined
=> Use correct filed from return

spec/duration.html, spec/instant.html, spec/intl.html, spec/legacydate.html, spec/plaintime.html, spec/temporal.html, spec/timezone.html, spec/zoneddatetime.html
The CreateTemporalInstant abstract operation will never return an abrupt
completion when invoked with a single argument. Communicate this
invariant using the specification's `!` shorthand.
This change makes it clear that the SystemInstant abstract operation
will never return an abrupt completion. Communicate this invariant by
removing the assertion from the operation's two call sites.
=> Editorial: communicate infallible instant ops

spec/abstractops.html, spec/plaindate.html
Remove the else if the end of the IF block is return or throw to simplify the logic.
=> Editorial: Remove unncessary Else

spec/abstractops.html
Split it to make it simpler to understand.
=> Editorial: Split Asserts in ToLargestTemporalUnit

polyfill/lib/ecmascript.mjs, polyfill/lib/intl.mjs, polyfill/test/intl.mjs
Port of https://github.com/js-temporal/temporal-polyfill/pull/12
=> Speed up toLocaleString ~2.5x by optimizing creation of Intl.DateTimeFormat instances

package-lock.json, package.json
This includes a fix for https://github.com/tc39/ecmarkup/issues/333, which should make the table of contents work correctly for sections such as [this one](https://tc39.es/proposal-temporal/#sup-time-zone-names), where the header of the section contains a link.
=> Meta: bump ecmarkup to 8.0.1

spec/instant.html
The internal slot of Temporal.Instant does not have a [[EpochNanoseconds]] field but only [[Nanoseconds]] field.
If we do not fix this, then AddInstant() will be called with undefined as the first argument.
=> Fix typo of EpochNanoseconds

spec/plaindatetime.html
Temporal.PlainDateTime objects don't have a [[Second]] internal slot, the correct name is [[ISOSecond]] for the "isoSecond" property.
=> Editorial: Fix internal slot name in Temporal.PlainDateTime.prototype.getISOFields

spec/abstractops.html
`ToInteger` got renamed to `ToIntegerOrInfinity` a while ago. The link in the generated HTML links to the right abstract operation already.
Found by @IdanHo while implementing it in SerenityOS's LibJS.
=> Editorial: Replace use of ToInteger with ToIntegerOrInfinity in PrepareTemporalFields

spec/calendar.html, spec/duration.html, spec/instant.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plaintime.html, spec/plainyearmonth.html, spec/timezone.html, spec/zoneddatetime.html
See https://github.com/tc39/ecma262/pull/2360
Bring the language around this in line with the main ECMA-262 text, using
the same unordered list form and the same bullet points everywhere.
=> Editorial: Remove "designed to be subclassable"

polyfill/lib/now.mjs, polyfill/lib/shim.mjs, polyfill/test/Now/toStringTag/prop-desc.js, polyfill/test/Now/toStringTag/string.js, polyfill/test/Temporal/toStringTag/prop-desc.js, polyfill/test/Temporal/toStringTag/string.js, spec/temporal.html
=> Normative: Add Temporal[@@toStringTag].

spec/calendar.html
CreateTemporalCalendar cannot return an abrupt completion record when
invoked with a single parameter.
=> Editorial: document infallability of AO invocation

spec/calendar.html, spec/instant.html, spec/intl.html, spec/plaintime.html, spec/temporal.html, spec/zoneddatetime.html
Whether an ECMAScript implementation uses the "default" version of
IsBuiltinCalendar proposed for ECMA262 or a version which satisfies the
constraints proposed for ECMA402, the GetISO8601Calendar abstract
operation never returns an abrupt completion.
=> Editorial: document infallibility of abstract op.

spec/temporal.html
In Temporal.now.plainDate and Temporal.now.plainDateISO, the
CreateTemporalDate abstract operation predictably returns a normal
completion record. The arguments are derived from a PlainDateTime object
which is known to be valid because it was produced from a successful
invocation of the SystemDateTime abstract operation.
The invocation of CreateTemporalTime in Temporal.now.plainTimeISO will
always return a normal completion record by the same logic.
=> Editorial: document infallible AO invocations

spec/abstractops.html
There is only one place in the spec call DurationHandleFractions
inside 13.40 ParseTemporalDurationString ( isoString )
in step 19
19. Let result be ? DurationHandleFractions(fHours, minutes, fMinutes, seconds, 0, milliseconds, 0, microseconds, 0, nanoseconds, 0).
https://tc39.es/proposal-temporal/#sec-temporal-durationhandlefractions
and it ALWAYS pass in 0 for fSeconds, fMilliseconds, fMicroseconds, fNanoseconds. Therefore we really do not need to pass in these values since it will always be 0.
13.5 DurationHandleFractions ( fHours, minutes, fMinutes, seconds, fSeconds, milliseconds, fMilliseconds, microseconds, fMicroseconds, nanoseconds, fNanoseconds )
We can therefore remove thse arguments as well as simply the logic and avoid unnecessary check in the IF statement.
=> Editorial: Simplify  DurationHandleFractions

polyfill/index.d.ts
_(ported from https://github.com/js-temporal/temporal-polyfill/pull/25)_ 
The TS types file is missing overloads for `PlainDate.prototype.toZonedDateTime()` when the argument is a timezone string or a TimeZoneProtocol object.
The current TS types support only object-bag arguments like these:
```ts
Temporal.Now.plainDateISO().toZonedDateTime({ timeZone: 'Asia/Tokyo' })
Temporal.Now.plainDateISO().toZonedDateTime({ timeZone: 'Asia/Tokyo', plainTime: '10:00' });
```
This PR adds TS types for the following overloads which work fine in the polyfill and spec but cause errors in TS: 
```ts
Temporal.Now.plainDateISO().toZonedDateTime(Temporal.Now.timeZone());
Temporal.Now.plainDateISO().toZonedDateTime('Asia/Tokyo');
```
=> TS types for missing overloads of `PlainDate.p.toZonedDateTime()`

spec/duration.html
I do not believe it will throw in these two calls
=> change from ? to ! in abs and negate

spec/zoneddatetime.html
These two functions are largely identical except for the very last step, where they either use `CreateTemporalDate` or `CreateTemporalTime`. For that reason we can easily make the previous steps of both functions identical by adding a separate step to get the `zonedDateTime.[[Calendar]]` slot instead of inlining that in `BuiltinTimeZoneGetPlainDateTimeFor`.
---
`toPlainDate` for comparison:
```
1. Let _zonedDateTime_ be the *this* value.
1. Perform ? RequireInternalSlot(_zonedDateTime_, [[InitializedTemporalZonedDateTime]]).
1. Let _timeZone_ be _zonedDateTime_.[[TimeZone]].
1. Let _instant_ be ! CreateTemporalInstant(_zonedDateTime_.[[Nanoseconds]]).
1. Let _calendar_ be _zonedDateTime_.[[Calendar]].
1. Let _temporalDateTime_ be ? BuiltinTimeZoneGetPlainDateTimeFor(_timeZone_, _instant_, …
```
=> Editorial: Make ZonedDateTime.prototype.toPlainTime consistent with toPlainDate

polyfill/lib/ecmascript.mjs, spec/plaindate.html
In every case where _mid_.[[Month]] = _end_.[[Month]], it also holds that
_mid_.[[Year]] = _end_.[[Year]]. In other words, due to the preceding
algorithm steps, _mid_ is always in the previous month, the same month, or
the following month compared to _end_. There is never a case where _mid_
and _end_ are 12 months apart.
Therefore, the second part of this comparison was unnecessary and would
never be compared due to short-circuiting. Replace it with an assertion.
Closes: #1649
=> Editorial: Remove dead code in tautological comparison

polyfill/lib/ecmascript.mjs, polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plainmonthday.mjs, polyfill/lib/plaintime.mjs, polyfill/lib/plainyearmonth.mjs, spec/abstractops.html, spec/plaindate.html, spec/plaindatetime.html, spec/plainmonthday.html, spec/plaintime.html, spec/plainyearmonth.html
This adds a new ToIntegerThrowOnInfinity abstract operation which allows
simplifying several long checks for infinity into something more
readable.
See, for original discussion: #1638
=> Editorial: Simplify text with new ToIntegerThrowOnInfinity abstract op

spec/plaindatetime.html
The spec text described accesses to the wrong Record slots from the return
value of BalanceDuration, so this was unimplementable as is.
Closes: #1722
=> Editorial: Fix broken return from DifferenceISODateTime

polyfill/test/Duration/constructor/compare/relativeto-string-invalid.js, polyfill/test/Duration/constructor/compare/relativeto-string-plaindatetime.js, polyfill/test/Duration/constructor/compare/relativeto-string-zoneddatetime-no-z.js, polyfill/test/Duration/constructor/compare/relativeto-string-zoneddatetime.js, polyfill/test/Duration/prototype/add/relativeto-string-invalid.js, polyfill/test/Duration/prototype/add/relativeto-string-plaindatetime.js, polyfill/test/Duration/prototype/add/relativeto-string-zoneddatetime-no-z.js, polyfill/test/Duration/prototype/add/relativeto-string-zoneddatetime.js, polyfill/test/Duration/prototype/round/relativeto-string-invalid.js, polyfill/test/Duration/prototype/round/relativeto-string-plaindatetime.js, polyfill/test/Duration/prototype/round/relativeto-string-zoneddatetime-no-z.js, polyfill/test/Duration/prototype/round/relativeto-string-zoneddatetime.js, polyfill/test/Duration/prototype/subtract/relativeto-string-invalid.js, polyfill/test/Duration/prototype/subtract/relativeto-string-plaindatetime.js, polyfill/test/Duration/prototype/subtract/relativeto-string-zoneddatetime-no-z.js, polyfill/test/Duration/prototype/subtract/relativeto-string-zoneddatetime.js, polyfill/test/Duration/prototype/total/relativeto-string-invalid.js, polyfill/test/Duration/prototype/total/relativeto-string-plaindatetime.js, polyfill/test/Duration/prototype/total/relativeto-string-zoneddatetime-no-z.js, polyfill/test/Duration/prototype/total/relativeto-string-zoneddatetime.js, polyfill/test/expected-failures.txt, spec/abstractops.html
A string given as the value of the relativeTo option must be parsed as a
Temporal.ZonedDateTime if possible, and otherwise as a PlainDateTime.
This is hopefully an editorial change, because the spec text as written
was unimplementable. There were no [[TimeZoneOffset]] or
[[TimeZoneIANAName]] fields on the Record returned from ParseISODateTime.
Closes: #1738
=> Editorial: Correctly parse relativeTo string

spec/plaindatetime.html
Most places use dateTime but some places use temporalDateTime referring to "this". Make it consistent.
=> Editorial: Consistently use dateTime instead

spec/plainyearmonth.html
only one plcae use plainYearMonth to refer to this, change it to alos use yearMonth
=> Editorial: Consistenly use yearMonth

spec/duration.html
use unbalancedResult for UnbalanceDuration
https://tc39.es/proposal-temporal/#sec-temporal.duration.compare
Step 7a and 7b
```
a. Let balanceResult1 be ? UnbalanceDurationRelative(one.[[Years]], one.[[Months]], one.[[Weeks]], one.[[Days]], "day", relativeTo).
b. Let balanceResult2 be ? UnbalanceDurationRelative(two.[[Years]], two.[[Months]], two.[[Weeks]], two.[[Days]], "day", relativeTo).
c. Let days1 be balanceResult1.[[Days]].
d. Let days2 be balanceResult2.[[Days]].
```
@ptomato @ryzokuken @Ms2ger
=> Editorial: fix variable name to match operation

spec/plaindate.html
@ptomato as I understand it, this usage is not affected by the problem you are correcting with gh-1709. Does that sound right to you?
=> Editorial: use "modulo" operator

docs/ja/README.md
`Temporal.now` was changed to `Temporal.Now` in #1645.
The Japanese documentation added in #1668 is still using `Temporal.now`.
=> Rename Temporal.now to Temporal.Now in Japanese docs

spec/duration.html
_secondsPart_ is already concatated into _timePart_ 4 lines above and should not be concancated again.
@ptomato @justingrant @sffc @Ms2ger
=> Normative: Remove extra "secondsPart"

polyfill/test/Duration/constructor/from/string-with-skipped-units.js, polyfill/test/validStrings.mjs, spec/abstractops.html
Previously, the grammar in the spec text would reject strings like
"PT1H1S", with a missing time unit in between two other time units, or
"P1Y1D", with missing calendar units in between two other calendar units.
This was never intended, but is now a normative change.
Closes: #1682
=> Normative: Adjust grammar of Duration ISO 8601 strings

polyfill/test/Instant/prototype/round/options-wrong-type.js, spec/instant.html
Make the Instant.prototype.round() throw also TypeError instead of RangeError if options is undefined.
See https://github.com/tc39/proposal-temporal/issues/1639#issuecomment-880355197
@justingrant @ptomato @Ms2ger @ryzokuken
=> Normative: Throw TypeError in Instant.round if options is undefined

spec/duration.html
3. Let offsetBefore be ? GetOffsetNanosecondsFor(relativeTo.[[TimeZone]], instant).
4. Let after be ? AddZonedDateTime(relativeTo.[[Nanoseconds]], relativeTo.[[TimeZone]], relativeTo.[[Calendar]], y, mon, d, h, min, s, ms, mus, ns).
6. Let offsetAfter be ? GetOffsetNanosecondsFor(relativeTo.[[TimeZone]], instantAfter).
would throw
@ptomato @ljharb @jugglinmike @justingrant @Ms2ger
=> Normative: Change ! to ? for calling CalculateOffsetShift

spec/plaindatetime.html
The note (and the algorithm itself) claims:
> time within 24 hours (8.64 × 10^16 nanoseconds)
This is incorrect, 24 hours are 8.64 × 10^13 nanoseconds, which is the
value that was intended to be used here (it's already correctly used in
other places). 8.64 × 10^16 nanoseconds are actually 24000 hours.
=> Normative: Change offset in ISODateTimeWithinLimits to actually 24h

polyfill/test/Duration/constructor/compare/relativeto-undefined-throw-on-calendar-units.js, polyfill/test/Duration/prototype/round/relativeto-undefined-throw-on-calendar-units.js, polyfill/test/Duration/prototype/total/relativeto-undefined-throw-on-calendar-units.js, spec/duration.html
I believe the IF check is on weeks not days based on the logic below.
I am not 100% sure this is right but the later 3 while looks on checking on 
years, months and weeks != 0 but the if check is on years, months and days, which does not make sense to me.
@ljharb @Ms2ger @ryzokuken @ptomato @jugglinmike @justingrant
=> Normative: Fix typo of days -> weeks

polyfill/lib/ecmascript.mjs, polyfill/lib/plaintime.mjs, polyfill/lib/zoneddatetime.mjs, polyfill/test/Duration/constructor/compare/calendar-dateadd-called-with-options-undefined.js, polyfill/test/Duration/prototype/add/calendar-dateadd-called-with-options-undefined.js, polyfill/test/Duration/prototype/round/calendar-dateadd-called-with-options-undefined.js, polyfill/test/Duration/prototype/subtract/calendar-dateadd-called-with-options-undefined.js, polyfill/test/Duration/prototype/total/calendar-dateadd-called-with-options-undefined.js, polyfill/test/PlainDate/prototype/toZonedDateTime/calendar-dateadd-called-with-options-undefined.js, polyfill/test/PlainDateTime/prototype/toZonedDateTime/calendar-dateadd-called-with-options-undefined.js, polyfill/test/PlainTime/prototype/toZonedDateTime/calendar-dateadd-called-with-options-undefined.js, polyfill/test/TimeZone/prototype/getInstantFor/calendar-dateadd-called-with-options-undefined.js, polyfill/test/ZonedDateTime/prototype/round/calendar-dateadd-called-with-options-undefined.js, polyfill/test/ZonedDateTime/prototype/round/dateadd-options.js, polyfill/test/ZonedDateTime/prototype/since/calendar-dateadd-called-with-options-undefined.js, polyfill/test/ZonedDateTime/prototype/startOfDay/calendar-dateadd-called-with-options-undefined.js, polyfill/test/ZonedDateTime/prototype/until/calendar-dateadd-called-with-options-undefined.js, polyfill/test/ZonedDateTime/prototype/withPlainDate/calendar-dateadd-called-with-options-undefined.js, polyfill/test/ZonedDateTime/prototype/withPlainTime/calendar-dateadd-called-with-options-undefined.js, polyfill/test/expected-failures.txt, polyfill/test/helpers/temporalHelpers.js, spec/timezone.html
Fix https://github.com/tc39/proposal-temporal/issues/1664
1. Pass (insert) in dateTime.[[Calendar]] as the missing 10th argument of calendar
2. change string "constain" to *undefined* so Temporal.Calendar.prototype.dateAdd won't throw when call GetOptionsObject and allow the default overflow 'constrain' to perform the 'constrain'.
@ptomato @ljharb @justingrant @Ms2ger @ryzokuken
=> Normative: Fix AddDateTime arguments

polyfill/lib/plainyearmonth.mjs, polyfill/test/PlainYearMonth/prototype/add/calendar-daysinmonth-wrong-value.js, polyfill/test/PlainYearMonth/prototype/subtract/calendar-daysinmonth-wrong-value.js, spec/plainyearmonth.html
Coerce the return value of CalendarDaysInMonth in Temporal.PlainYearMonth.prototype.(add|subtract) method becasue calendar can return any kind of value.
Address https://github.com/tc39/proposal-temporal/issues/1713
I am not sure this should be Editoral or Normative since the current spec text does not hold the Assertion
@sffc @ptomato @Ms2ger @ljharb @justingrant
=> Normative: Coerce return of CalendarDaysInMonth

polyfill/test/Duration/prototype/toString/blank-duration-precision.js, spec/duration.html
The shortcut of returning PT0S became incorrect after we added options to
control the precision of the toString output.
Closes: #1697
=> Normative: Handle precision for blank Durations as intended

polyfill/lib/plainmonthday.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/test/PlainMonthDay/prototype/toPlainDate/argument-not-object.js, polyfill/test/PlainYearMonth/prototype/toPlainDate/argument-not-object.js, polyfill/test/helpers/temporalHelpers.js, spec/plainmonthday.html
The spec text was inconsistent about whether the type check on the
argument or the calendar.fields checks should occur first. In
Temporal.PlainMonthDay.prototype.toPlainDate, the fields checks were
first. In Temporal.PlainYearMonth.prototype.toPlainDate, the type check
was first. This changes the PlainMonthDay algorithm to match the
PlainYearMonth one, and adds tests to both.
Closes: #1702
=> Normative: Consistent order of operations in PMD.toPD and PYM.toPD

polyfill/lib/ecmascript.mjs, polyfill/test/Duration/constructor/from/non-integer-throws-rangeerror.js, polyfill/test/Duration/prototype/add/non-integer-throws-rangeerror.js, polyfill/test/Duration/prototype/subtract/non-integer-throws-rangeerror.js, polyfill/test/Duration/prototype/with/non-integer-throws-rangeerror.js, polyfill/test/Duration/prototype/with/order-of-operations.js, polyfill/test/Instant/prototype/add/non-integer-throws-rangeerror.js, polyfill/test/Instant/prototype/subtract/non-integer-throws-rangeerror.js, polyfill/test/PlainDate/prototype/add/non-integer-throws-rangeerror.js, polyfill/test/PlainDate/prototype/subtract/non-integer-throws-rangeerror.js, polyfill/test/PlainDateTime/prototype/add/non-integer-throws-rangeerror.js, polyfill/test/PlainDateTime/prototype/subtract/non-integer-throws-rangeerror.js, polyfill/test/PlainTime/prototype/add/non-integer-throws-rangeerror.js, polyfill/test/PlainTime/prototype/subtract/non-integer-throws-rangeerror.js, polyfill/test/PlainYearMonth/prototype/add/non-integer-throws-rangeerror.js, polyfill/test/PlainYearMonth/prototype/subtract/non-integer-throws-rangeerror.js, polyfill/test/ZonedDateTime/prototype/add/non-integer-throws-rangeerror.js, polyfill/test/ZonedDateTime/prototype/subtract/non-integer-throws-rangeerror.js, spec/duration.html
Unintentionally forgot with() when rejecting non-integer Duration fields
in issue #938.
Adds tests for anywhere Duration property bags are accepted, fixes a test
that would fail under the new spec text, and brings the testing polyfill
code in alignment with the new spec text.
Closes: #1704
=> Normative: Reject non-integer Duration fields in Duration.with()

polyfill/test/PlainDateTime/prototype/since/calendar-dateuntil-called-with-copy-of-options.js, polyfill/test/PlainDateTime/prototype/until/calendar-dateuntil-called-with-copy-of-options.js, polyfill/test/ZonedDateTime/prototype/since/calendar-dateuntil-called-with-copy-of-options.js, polyfill/test/ZonedDateTime/prototype/until/calendar-dateuntil-called-with-copy-of-options.js, spec/zoneddatetime.html
In ZonedDateTime.prototype.until() and ZonedDateTime.prototype.since(),
the main invocation of calendar.dateUntil() should get a copy of the
user-originated options object (with largestUnit adjusted), just like
the same methods on PlainDateTime do.
(This doesn't hold for the NanosecondsToDays step in
DifferenceZonedDateTime, which must be called with blank options. So, for
the ZonedDateTime tests we choose values that don't go through that path.)
Closes: #1721
=> Normative: Pass user difference options into calendar.dateUntil() from ZDT

polyfill/lib/ecmascript.mjs, polyfill/test/ZonedDateTime/constructor/from/balance-negative-time-units.js, polyfill/test/ZonedDateTime/prototype/with/balance-negative-time-units.js, spec/timezone.html, spec/zoneddatetime.html
In the current spec text algorithm, there was an unnecessary call to
timeZone.getPossibleInstantsFor(), which potentially calls observably into
user code. Fix the algorithm so it doesn't make any more calls than
necessary.
=> Normative: Optimize calls into user code in InterpretISODateTimeOffset

polyfill/lib/duration.mjs, polyfill/test/Duration/prototype/total/options-wrong-type.js, polyfill/test/duration.mjs, spec/duration.html
=> Normative: Throw TypeError on missing options from Duration.total

polyfill/lib/ecmascript.mjs, polyfill/test/PlainDate/prototype/with/calendar-merge-fields-returns-primitive.js, polyfill/test/PlainDateTime/prototype/with/calendar-merge-fields-returns-primitive.js, polyfill/test/PlainMonthDay/prototype/toPlainDate/calendar-merge-fields-returns-primitive.js, polyfill/test/PlainMonthDay/prototype/with/calendar-merge-fields-returns-primitive.js, polyfill/test/PlainYearMonth/prototype/toPlainDate/calendar-merge-fields-returns-primitive.js, polyfill/test/PlainYearMonth/prototype/with/calendar-merge-fields-returns-primitive.js, polyfill/test/ZonedDateTime/prototype/with/calendar-merge-fields-returns-primitive.js, polyfill/test/helpers/temporalHelpers.js, spec/calendar.html
In each case where CalendarMergeFields is called, it is later asserted in
PrepareTemporalFields that Type(_fields_) is Object. Previously the spec
text failed this assertion.
The tests check that a TypeError is thrown in this case, as well as that
the TypeError is thrown before the value is passed to any dateFromFields()
or similar method.
=> Normative: Ensure an Object is returned from calendar.mergeFields()

.eslintrc.yml, polyfill/test/intl402/DateTimeFormat/prototype/format/temporal-objects-resolved-time-zone.js, polyfill/test/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-resolved-time-zone.js, polyfill/test/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-resolved-time-zone.js, polyfill/test/intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-resolved-time-zone.js, polyfill/test/intl402/Temporal/PlainDate/prototype/toLocaleString/resolved-time-zone.js, polyfill/test/intl402/Temporal/PlainDateTime/prototype/toLocaleString/resolved-time-zone.js, polyfill/test/intl402/Temporal/PlainMonthDay/prototype/toLocaleString/resolved-time-zone.js, polyfill/test/intl402/Temporal/PlainTime/prototype/toLocaleString/resolved-time-zone.js, polyfill/test/intl402/Temporal/PlainYearMonth/prototype/toLocaleString/resolved-time-zone.js, spec/intl.html
In the PlainDate, PlainDateTime, PlainMonthDay, PlainTime, and
PlainYearMonth cases, the _timeZone_ variable was never set before it was
used. This is an error in the spec text. It should be equal to the
time zone in the DateTimeFormat's resolvedOptions.
Add tests proving that this time zone is used when converting the Plain
objects to exact time, so that the wall time in the same time zone is used
when formatting them.
=> Normative: Fix undefined variables in HandleDateTimeValue

polyfill/lib/calendar.mjs, polyfill/test/Calendar/prototype/fields/argument-throws-duplicate-keys.js, polyfill/test/Calendar/prototype/fields/argument-throws-invalid-keys.js, polyfill/test/Calendar/prototype/fields/non-string-element-throws.js, spec/calendar.html, spec/intl.html
As discussed in #1610, we restrict values returned by the iterator to be no more than the ten known values, prohibiting duplicates. The check for String values has been removed as all of those values are Strings, so the value restriction is plenty.
This does not address the question of return value validation.
=> Validate input to Calendar.prototype.fields

polyfill/lib/calendar.mjs, polyfill/lib/duration.mjs, polyfill/lib/ecmascript.mjs, polyfill/lib/plaindate.mjs, polyfill/test/Calendar/prototype/dateAdd/balance-smaller-units.js, polyfill/test/Calendar/prototype/dateAdd/duration-argument-string-negative-fractional-units.js, polyfill/test/PlainDate/prototype/add/balance-smaller-units.js, polyfill/test/PlainDate/prototype/subtract/balance-smaller-units.js, spec/calendar.html, spec/duration.html, spec/intl.html, spec/plaindate.html
Fixes a discrepancy between how durations are treated depending on whether
they are passed to PlainDate.prototype.add() or
Calendar.prototype.dateAdd(). The treatment should be the same in both
cases.
In the case of PlainDate.prototype.subtract(), the duration should be
negated before being passed to Calendar.prototype.dateAdd().
Closes: #1708
=> Normative: Duration operations should be the same in PlainDate.add and Calendar.dateAdd

polyfill/ci_test.sh
Allow the prelude used with the Test262 harness to be specified via an
environment variable so other Temporal polyfills can re-use the test
harness.
This is in preparation for fixing https://github.com/js-temporal/temporal-polyfill/issues/4.
=> Allow other repositories to re-use the Test262 setup.

spec/plaintime.html
Currently defined as:
> 1. Assert: hour, minute, second, millisecond, microsecond and nanosecond are integers.
> 2. Let hour be hour formatted as a two-digit decimal number, padded to the left with a zero if necessary.
> 3. Let minute be minute formatted as a two-digit decimal number, padded to the left with a zero if necessary.
> 4. Let seconds be ! FormatSecondsStringPart(second, millisecond, microsecond, nanosecond, precision).
> 5. Return the string-concatenation of hour, the code unit 0x003A (COLON), minute, and seconds.
And clearly none of this can throw.
=> Editorial: Mark TemporalTimeToString as infallible

polyfill/lib/calendar.mjs, polyfill/test/intl.mjs
This PR fixes non-ISO calendars' `mergeFields` implementation that was crashing when using `with` for for Japanese calendars to set the day to a day outside the current era.
The root cause was that mergeFields was merging the original `year`,`era`, and `eraYear` with the user-provided `day` field. This fails in calendars like Japanese where eras start and/or end mid-month. So by changing the `day`, suddenly the calculated era won't match the `era` field and we'll throw.  The fix was to omit `era`/`eraYear` from the results in this case because `year` is sufficient.
Fixes #1784
=> Fix crash setting `day` outside current era bounds

spec/abstractops.html
This sets `offsetString` to `timeZoneResult.[[OffsetString]]` and overwrites it in the next step if necessary, but the `[[TimeZoneOffsetString]]` field in the returned record uses `timeZoneResult.[[OffsetString]]` again instead of `offsetString` as intended.
This change is needed to actually make the fix attempted in f6ac475 work.
=> Normative: Fix [[TimeZoneOffsetString]] value in ParseTemporalInstantString

polyfill/ci_test.sh, polyfill/test/parseResults.js
This PR enables running Test262 in debuggers like VSCode:
* Adds a `TIMEOUT` environment variable (in msecs) to prevent the harness from killing the process while you're debugging it. Default is 10,000ms === 10 seconds. (same as existing default)
* Works around a problem where passing tests were mistakenly labelled as failures when run in the debugger because of Node's debug-related console output.
js-temporal/temporal-polyfill#46 depends on this PR to work properly.
=> Easier debugging and troubleshooting of Test262 tests

spec/abstractops.html
Introduce a TimeZoneIANANameTail and CalendarNameTail to grammar to make TimeZoneIANAName and CalendarName unambigously addressable from the spec.
Also change  TimeZoneIANAName from left recursion to right recussion which is easier for the implementation to replace with iteration loop of parsing from recursive parsing.
The spec text in [13.44 ParseTemporalTimeZoneString ( isoString )](https://tc39.es/proposal-temporal/#sec-temporal-parsetemporaltimezonestring)
stats
```
3. Let ... and name be the parts of isoString produced respectively by the ... and TimeZoneIANAName productions, or undefined if not present.
```
But before the change there could be multiple TimeZoneIANAName productions from a valid  TemporalTimeZoneString since the TimeZoneIANAName is recursive in the grammar therefore …
=> Editoral:Unique TimeZoneIANAName and CalendarName

docs/buildDocs.js
Currently, in
https://github.com/tc39/proposal-temporal/README.md
Temporal 文档(zh_CN) (translated a part of the English document into Chinese)
is pointing to https://tc39.es/proposal-temporal/docs/zh_CN/
but got a 404, try to fix the build rule to push it to https://tc39.es/proposal-temporal/docs/zh_CN/
I hope I did the right thing here....
@ryzokuken @sititou70 @ptomato @sxyazi
=> Fix build for zh_CN  docs

spec/zoneddatetime.html
between "minute" and "second in step 3 of InterpretISODateTimeOffset
=> Editorial: correct "." to ","

spec/duration.html
Always pass relativeTo as PlainDateTime to MoveRelativeDate
Assert the relativeTo
Convert to PlainDateTime inside 
RoundDuration
https://tc39.es/proposal-temporal/#sec-temporal-roundduration
Address https://github.com/tc39/proposal-temporal/issues/1782
@ptomato @justingrant @ryzokuken @Ms2ger
=> Editorial: pass relativeTo as PlainDateTime MoveRelativeDate

spec/abstractops.html
Return result.[[Calendar]] in ParseTemporalZonedDateTimeString from 
```
3. Let result be ! ParseISODateTime(isoString).
```
so in ToTemporalZonedDateTime
step 4-i will have 
```
i. Let calendar be ? ToTemporalCalendarWithISODefault(result.[[Calendar]]).
```
Without this fix the spec won't work becuase result won't have [[Calendar]]
Address https://github.com/tc39/proposal-temporal/issues/1676
@ptomato @justingrant @Ms2ger @ryzokuken
=> Editorial: Return [[Calendar]] in ParseTemporalZonedDateTimeString

spec/abstractops.html, spec/zoneddatetime.html
Rename the reading of [[Z]] to [[TimeZoneZ]]  
ParseTemporalZonedDateTimeString is called inside
ToTemporalZonedDateTime https://tc39.es/proposal-temporal/#sec-temporal-totemporalzoneddatetime
```
step 4
c. Let result be ? ParseTemporalZonedDateTimeString(string).
...
f. If result.[[Z]] is true, then
```
But
ParseTemporalZonedDateTimeString 
https://tc39.es/proposal-temporal/#sec-temporal-parsetemporalzoneddatetimestring
return that field as [[TimeZoneZ]]
```
5. Return the Record { [[Year]]: result.[[Year]], [[Month]]: result.[[Month]], [[Day]]: result.[[Day]], 
[[Hour]]: result.[[Hour]], [[Minute]]: result.[[Minute]], [[Second]]: result.[[Second]], 
[[Millisecond]]: result.[[Millisecond]], [[Microsecond]]: result.[[Microsecond]], 
[[Nanosecond]]: result.[[Nanosecond]], [[TimeZoneZ]]: …
```
=> Editorial: Read [[TimeZoneZ]]  instead of [[Z]]

spec/zoneddatetime.html
Remove "or *undefined*" from the assert of offsetNanoseconds in InterpretISODateTimeOffset
This is no longer needed. offsetNanoseconds now will not be undefined after the merge of 
https://github.com/tc39/proposal-temporal/commit/f6ac475e6131ab0f11dc641ae55dcf72e6ab1118
It used to accept undefined but the above commit set that value to 0 so all the possible cases are now all integer
@ptomato @justingrant @ljharb @ryzokuken @Ms2ger 
There are 4 Callers of InterpretISODateTimeOffset
6.3.30 Temporal.ZonedDateTime.prototype.with ( temporalZonedDateTimeLike [ , options ] )
https://tc39.es/proposal-temporal/#sec-temporal.zoneddatetime.prototype.with
```
25. Let offsetNanoseconds be ? ParseTimeZoneOffsetString(offsetString).
26. Let epochNanoseconds be ? InterpretISODateTimeOffset(...
``` …
=> Editorial: Remove "or *undefined*" from  InterpretISODateTimeOffset assert

spec/timezone.html
Pass in TemporalPlainDateTime to GetPossibleInstantsFor
Fix the issue that DisambiguatePossibleInstants pass Record return from AddDateTime into Invoke inside GetPossibleInstantsFor reported in https://github.com/tc39/proposal-temporal/issues/1816
I mark this as Editorial because the current spec text is unimplementable w/o this fix.
@ptomato @justingrant @Ms2ger @ljharb @ryzokuken
=> Editorial: Pass in T*PlainDateTime to GetPossibleInstantsFor

polyfill/lib/ecmascript.mjs, polyfill/lib/plainyearmonth.mjs, polyfill/test/PlainYearMonth/prototype/add/calendar-arguments-extra-options.js, polyfill/test/PlainYearMonth/prototype/add/calendar-arguments.js, polyfill/test/PlainYearMonth/prototype/subtract/calendar-arguments-extra-options.js, spec/plaindatetime.html, spec/plainyearmonth.html
… to prevent user-modified objects from interfering with later operations.
Fixes #1686
=> Copy options object for PlainYearMonth.{add,subtract} and InterpretTemporalDateTimeFields

polyfill/lib/regex.mjs, polyfill/test/regex.mjs
Per the spec:
>      DateMonth :
>           0 NonzeroDigit
>           10
>           11
>           12
>
>      DateDay :
>           0 NonzeroDigit
>           1 Digit
>           2 Digit
>           30
>           31
The following will now throw `RangeError`
```
Temporal.Instant.from("1976-40-18T00:00:00Z");
Temporal.Instant.from("1976-11-50T00:00:00Z");
Temporal.PlainDateTime.from("1976-40-18T00:00:00");
Temporal.PlainDateTime.from("1976-11-50T00:00:00");
etc
```
Note that `yearmonth` and `monthday` were changed for consistency but `Temporal.PlainYearMonth.from` and `Temporal.PlainMonthDay.from` already validate these values at a higher level
=> Tighten ISO parsing of month and day values

polyfill/lib/ecmascript.mjs, polyfill/test/timezone.mjs
This is the same as https://github.com/js-temporal/temporal-polyfill/pull/58.
=> Treat System Epoch in nanoseconds as bigint.BigInteger.

docs/plaindate.md, docs/plaindatetime.md, docs/plainmonthday.md, docs/plainyearmonth.md, docs/zoneddatetime.md, polyfill/index.d.ts
Updates TS types to port changes from temporal-polyfill:
* Calendar/CalendarProtocol types' options parameters should be optional
* `calendar` parameters in constructors accept string IDs too
The latter change also affects docs, so docs changes are included too.
=> Update TS types, docs w/ temporal-polyfill changes

package-lock.json, polyfill/lib/plaindate.mjs, polyfill/lib/plaindatetime.mjs, polyfill/lib/plainmonthday.mjs, polyfill/lib/plainyearmonth.mjs
TS found a bug in several callers of `CalendarEquals`. This bug didn't break any tests because it only executed when non-calendar units were equal, but the new code matches the spec. 
Also, including the Test262 submodule broke my git repo, so I had to re-clone my local repo from GitHub. When I ran `npm install` after doing this, there was a one-line change made in package-lock.json. I assume this is OK.
=> Fix usage of ES.CalendarEquals

spec/zoneddatetime.html
in Temporal.ZonedDateTime.prototype.with we need to call ToString before passing that string to ParseTimeZoneOffsetString
https://tc39.es/proposal-temporal/#sec-temporal.zoneddatetime.prototype.with
offsetString could be anything after the Get but ParseTimeZoneOffsetString assert on the argument to be String
@ptomato @Ms2ger @ljharb
=> Editoral: Call ToString before ParseTimeZoneOffsetString

polyfill/index.d.ts
We recently made progress in adding more typing to the [temporal-polyfill](https://github.com/js-temporal/temporal-polyfill) TS implementation, and doing this exposed quite a few bugs in our old types. Also, it made sense to add some new types for options and units.
This PR rolls up recent changes from the prod polyfill:
* Options properties are now all marked as optional
* Different implementation of singular vs. plural unit-name string literal types
* Prevent `RoundOptions<'bogus'>`
* New exported unit-name literal types: `DateUnit`, `TimeUnit`, `DateTimeUnit`
* `PluralUnit<T>` type to convert singular to plural.
* new types: `LargestUnitOption<T>`, `SmallestUnitOption<T>`, `TotalUnitOption<T>`
* Narrowed parameter types of `Calendar` and CalendarProtocol methods, e.g. requiring either …
=> Port latest index.d.ts from temporal-polyfill

spec/instant.html, spec/zoneddatetime.html
Lots of `!`, no `?`.
```
5.5.1 GetEpochFromISOParts ( year, month, day, hour, minute, second, millisecond, microsecond, nanosecond )
1. Assert: year, month, day, hour, minute, second, millisecond, microsecond, and nanosecond are integers.
2. Assert: ! IsValidISODate(year, month, day) is true.
3. Assert: ! IsValidTime(hour, minute, second, millisecond, microsecond, nanosecond) is true.
4. Let date be ! MakeDay(𝔽(year), 𝔽(month − 1), 𝔽(day)).
5. Let time be ! MakeTime(𝔽(hour), 𝔽(minute), 𝔽(second), 𝔽(millisecond)).
6. Let ms be ! MakeDate(date, time).
7. Assert: ms is finite.
8. Return ℝ(ms) × 10^6 + microsecond × 10^3 + nanosecond.
```
`ISODateTimeWithinLimits`, `Temporal.TimeZone.prototype.getPossibleInstantsFor`, and `DisambiguatePossibleInstants` already have it correctly.
=> Editorial: Mark GetEpochFromISOParts as infallible

spec/abstractops.html
Fixes #1758, which is clearly a spec bug, and also reduces nearby ambiguity by eliminating context-free references to |TimeFractionalPart|. I'd further like to bring _fSeconds_ into alignment as well, but left that out here to avoid cluttering up the diff.
=> Normative: Fix the scale adjustment of fractional duration string components

spec/abstractops.html
fraction in ParseTemporalTimeZoneString is referring to TimeZoneUTCOffsetFraction which include the "." in the first char.
Therefore the substring of fraction from 0 to 9 is ".12345678" but not "123456789' .
change it from 0 to 9 to 1 to 10 will make it to be "123456789'
Fix https://github.com/tc39/proposal-temporal/issues/1795
Also an editoral change based on the text in ParseTimeZoneOffsetString which  state 
"... consisting of the code units with indices **start** (inclusive) through **end** (exclusive)."
@ptomato @justingrant @Ms2ger @ljharb @gibson042
=> Normative: shift substring index by 1 to count "."

spec/timezone.html
The current spec will format negative offset incorrectly with extra '-' in front of hours ,  minutes  and seconds
-07:30 will be formated as --07:-30
we need to store the absolute value of offsetNanoseconds into offsetNanoseconds to calcuate 
hours, minutes and seconds correctly, not just the nanoseconds
@ptomato @ljharb @justingrant @Ms2ger @ryzokuken
=> Normative: Fix FormatTimeZoneOffsetString

spec/duration.html
See https://github.com/tc39/proposal-temporal/issues/1859
@ptomato @ljharb @justingrant @ryzokuken @Ms2ger
=> Normative: Fix precision 0 issue in TemporalDurationToString

spec/plainyearmonth.html
Notice currently the NegateTemporalRoundingMode got called twice in 
https://tc39.es/proposal-temporal/#sec-temporal.plainyearmonth.prototype.since
```
12. Set roundingMode to ! NegateTemporalRoundingMode(roundingMode).
...
25. Set roundingMode to ! NegateTemporalRoundingMode(roundingMode).
```
and there are no code to use roundingMode between step 12 and step 25. I believe the one in step 25 is extra, which  "revert" the negation of the rounding mode in step 12.
@ptomato @justingrant @ljharb @ryzokuken @Ms2ger
=> Normative: Remove extra  NegateTemporalRoundingMode which revert the effect of the first one.

spec/plaintime.html
Need to call BalanceTime with the amount timed by sign
w/o this PR the spec won't pass at least the following 15 tests
=== test262/built-ins/Temporal/PlainDateTime/prototype/since/balance-negative-duration ===
=== test262/built-ins/Temporal/PlainDateTime/prototype/since/argument-zoneddatetime-balance-negative-time-units ===
=== test262/built-ins/Temporal/PlainDateTime/prototype/since/balance-negative-time-units ===
=== test262/built-ins/Temporal/PlainDateTime/prototype/since/round-negative-duration ===
=== test262/built-ins/Temporal/PlainDateTime/prototype/until/argument-plaindate ===
=== test262/built-ins/Temporal/PlainDateTime/prototype/until/balance-negative-time-units ===
=== test262/built-ins/Temporal/PlainDateTime/prototype/until/balance-negative-duration ===
=== …
=> Normative: Fix DifferenceTime

spec/duration.html
UnbalanceDurationRelative has this guard:
```
12. Else,
a. If any of years, months, and days are not zero, then
```
However, it takes action based on `years`, `months`, and _`weeks`_, not `days`.
Swapping the variable seems to match what the [polyfill](https://github.com/rkirsling/proposal-temporal/blob/patch-1/polyfill/lib/ecmascript.mjs#L2633) actually does, but it's not the only possible solution—note that the handling of `days` in this AO is currently pretty weird:
-  If `days` is the only non-zero unit and `relativeTo` is undefined, then (as of this proposed change), we throw just when the unit is `"month"` or `"week"`.
- But nothing in this AO performs a calculation based on `days`—in particular, the `"month"` and `"week"` paths do not differ from the Else path in this respect, so …
=> Normative: Fix typo in UnbalanceDurationRelative.

spec/abstractops.html
1. Add  a new FractionalPart to the grammar to represen what used to be TimeFractionalPart
so in ParseISODateTime TimeFractionalPart  is referring to an unambigous FractionalPart
2. Add a TimeZoneUTCOffsetFractionalPart to fix  ParseTemporalTimeZoneString
3. Change ParseTemporalTimeZoneString to refer to TimeZoneUTCOffsetFractionalPart instead of TimeZoneUTCOffsetFraction to exclude the "." to fix the algorithm.
I am not 100% sure this is the best fix for these two problem and maybe there are some negative consequence I am not aware, but the current spec text has these two problems that I cannot implement the parser correctly. 
Try to fix https://github.com/tc39/proposal-temporal/issues/1795 and https://github.com/tc39/proposal-temporal/issues/1794
@Ms2ger @ljharb @ptomato @sffc …
=> Normative: Fix problem in ParseISODateTime and ParseTemporalTimeZoneString

spec/zoneddatetime.html
Fix https://github.com/tc39/proposal-temporal/issues/1892 to avoid deadcode
Needed to fulfil 
https://github.com/tc39/test262/blob/main/test/built-ins/Temporal/ZonedDateTime/from/offset-undefined.js
https://github.com/tc39/test262/blob/main/test/built-ins/Temporal/ZonedDateTime/from/options-undefined.js
@pdunkel @ptomato @jugglinmike @Ms2ger @ljharb @justingrant
=> Normative: add "offset" to fieldNames in ToTemporalZonedDateTime
